### ISSUE TITLE
import-caffe.py Memory Error on Windows 7 

### ISSUE THREAD

**Issue by kilickaya** [vlfeat/matconvnet#100]
Hi,

I am running MatConvNet on a 64 bit Windows machine. 

I am using import-caffe.py to convert a proposed model (http://places.csail.mit.edu/) to MatConvNet format. It succesfully converts the model until the 15th layer. 

However, after that, I receive a 'Memory Error'. I suspect this is due to the fact that Windows only allows 1 GB RAM usage for a single (python) process. 

I would like to ask if there is any workaround exists for such error?

**Comment by lenck** [comment]
Hmm, we did all the conversions on Linux machines :( But I'm surprised that there is such a limit and I was not able to find any further information, only similar thing was (here)[https://stackoverflow.com/questions/18087793/increase-memory-usage-for-python-process-on-windows] which suggests to use newer version of numpy...

**Comment by tommeke9** [comment]
Hey kilickaya,
Did you manage to convert the Places database to MatConvNet?
Which version of the pertained cnn did you use? Alexnet or VGG16?

**Comment by kilickaya** [comment]
I manage to convert Places (along with HYBRID etc.) not by Windows (due to Python Memory issues) but by Linux

**Comment by tommeke9** [comment]
@kilickaya Do you mind sharing the files used to convert the places-database to Matconvnet?
 It would be really helpful!

**Comment by Jansenns** [comment]
I am also trying to convert the places2-DB to matconvnet. Which files did you have to change? Only the import-ref-models.sh? Or did you also change import-caffe.py?

**Comment by kilickaya** [comment]
First, places is not a database, it is a CNN architecture (sharing the same architecture with famous AlexNet) where MIT researchers trained to recognize scenes -or places in paper's jargon- (instead of ImageNet objects).

Then, Yes I can share these models (along with the HYBRID model) via DropBox or Google Drive, will update this when upload is complete.

**Comment by tommeke9** [comment]
Thank you! Let me know when you have the link :)
(I meant a 'CNN trained on the places database', but you are absolutely right that I wrote it incorrect)

**Comment by salmaneme** [comment]
Hi @kilickaya , Could you please share the models in Matconvnet format?

Thanks,

**Comment by munawarhayat6** [comment]
I have been trying to convert the Places 205 VGG CNN model, everything runs fine, but the weight matrices are empty. Dont know where is it going wrong. Can you please share your converted models, and possibly the scripts.

**Comment by Drronan** [comment]
Hi guys, I'm also looking for the Places 205 VGG CNN model in matconvnet format can someone share it please?
Thanks a lot.

**Comment by DongXingshuai** [comment]
Hi, @kilickaya Could you please share the Places models in Matconvnet format? Thank you so much!

**Comment by Necole123** [comment]
hi,guys, I am a newer in python and caffe, I want to convert a pre-trained caffemodel to matconvnet format, does anyone could tell me how to use the import-caffe.py?  what are the inputs? Thanks a lot
