### ISSUE TITLE
the difference between opts.train.learningRate and net.params(i).learningRate

### ISSUE THREAD

**Issue by JoyLuo** [vlfeat/matconvnet#1002]
（1）opts.train.learningRate can be setting for all layer
（2）net.params(i).learningRate can be setting for specific layer
and the question is that which one is the real learningRate in the training process. and the difference.

**Comment by fengyunxiaozi** [comment]
opts.train.learningRate is the basic learning rate and net.params(i).learningRate is the multiply factor, just like the learningRate set in Caffe. For example, if net.params(i).learningRate=1, then the weights of convolutional layers will be opts.train.learningRate.

**Comment by JoyLuo** [comment]
@fengyunxiaozi very clear answer, and thanks for your kindly
