### ISSUE TITLE
302 Tests failed, 302 incomplete. CUDA and cuDNN Enabled

### ISSUE THREAD

**Issue by nmerrill67** [vlfeat/matconvnet#1022]
There are an absurd amount of errors when I run `vl_testnn('gpu', 1)`

They all stem from cuDNN. I won't give you the entire output of vl_testnn (it's very long as you know) , but here are examples of the two cuDNN errors I am receiving (it appears to be repeats of the same errors):

Error occurred in nnsimplenn[dataType=single,device=gpu]/precious and it did not run to completion.

    ---------
    Error ID:
    ---------
    'VLMX:InvalidArgument'

    --------------
    Error Details:
    --------------
    Error using vl_nnconv
    forward: cuDNN error [cudnn:
    "/home/nate/Libraries/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu":141
    (CUDNN_STATUS_BAD_PARAM)]
    
    Error in vl_simplenn (line 300)
          res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...
    
    Error in nnsimplenn/precious (line 95)
          res = vl_simplenn(net_, test.x, [], [], 'conserveMemory', true);

and

================================================================================
Error occurred in nnconvt[dataType=single,device=gpu]/upsample_crop(upx=value2,upy=value1,padx1=value1,pady1=value1,padx2=value1,pady2=value1) and it did not run to completion.

    ---------
    Error ID:
    ---------
    ''

    --------------
    Error Details:
    --------------
    Error using vl_nnconvt
    backward: cuDNN error [cudnn:
    "/home/nate/Libraries/matconvnet/matlab/src/bits/impl/nnconv_cudnn.cu":431
    (CUDNN_STATUS_NOT_SUPPORTED)]
    
    Error in nnconvt/upsample_crop (line 40)
          y = vl_nnconvt(x,f,b,opts{:}) ;

I have compiled with:
`
vl_compilenn('enableGpu', true, ...
               'cudaRoot', '/usr/local/cuda-8.0', ...
                'cudaMethod', 'nvcc',...
               'enableCudnn', true, ...
               'cudnnRoot', '/usr/local/cudnn-5',...
               'cudaArch', '-gencode=arch=compute_50,code=\"sm_50,compute_50\" '...
               ,'verbose', 1) ;
`
I hard coded the architecture as a possible solution, as I have tried many things.

I am using cuda 8.0, cuDNN 5.1, and an nvidia GeForce GTX 960M gpu 

I executed 

`export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/usr/local/cuda-8.0/lib64/libcudart.so.8.0:/usr/local/cuda-8.0/lib64/libcublas.so.8.0:/usr/lib/x86_64-linux-gnu/libprotobuf.so.9`

`export LD_LIBRARY_PATH=/usr/local/cudnn-5/lib64:$LD_LIBRARY_PATH`

in hopes that this would help cuDNN errors, but to no avail.

**Comment by DAA233** [comment]
Same problem, does anyone have any ideas?

**Comment by alexattia** [comment]
Same issue with Cuda 9 and matlab 2017b on Ubuntu

**Comment by oakal** [comment]
same here, on ubuntu 16.04, cuda 8 and matlab 2017a.
I've a temporary solution which is  `opts.train.cudnn = false;` that comes with a cost of loosing speed. Anyone found a real solution?

**Comment by GreenALan** [comment]
i have the same problem, who solves it?

**Comment by nmerrill67** [comment]
This is a lost cause. Switch to tensorflow, caffe, pytorch, or even darknet.
