### ISSUE TITLE
Anyone has implemented "full convolution"?

### ISSUE THREAD

**Issue by xcyan** [vlfeat/matconvnet#103]

**Comment by vedaldi** [comment]
If by this you mean fully connected layers, yes, these are implemented by vl_nnconv as a special case. There is really no need to distinguish them from standard convolution (but the code does recognise it and  runs an optimised computational path).

**Comment by xcyan** [comment]
Actually, I mean "full convolution" rather than "fully connected layer". As
far as I know, matconvnet is implemented based on "valid convolution" but
"full convolution" might be helpful in "convolutional auto-encoders". It is
true that "full convolution" can be implemented using "padding" with "valid
convolution", but the memory becomes a problem if "filter size" is too
large.

**Comment by vedaldi** [comment]
Hi, ok, so you mean "full convolution" as in the conv() function of MATLAB. In that case, yes, the answer is padding. In term of memory usage, clearly padding increases the memory somewhat (e.g. a padding of size comparable to the image would multiply the memory usage by four with the basic algorithm). I would suggest to see if the cuDNN variant of the convolution code (which is used by default is cuDNN is compiled in), would have this problem. It is supposed to be much less memory demanding than the usual im2row + BLAS algorithm.

**Comment by rose100** [comment]
hello, how to define full connected layer?
