### ISSUE TITLE
EEG Data Classification

### ISSUE THREAD

**Issue by rabiaali95** [vlfeat/matconvnet#1035]
Hello,
Sir/Maam i need some help. I have EEG data. I want to classify that using Convolutional Neural Network. I have to see which kind of movement it is either the left hand or the right hand movement. I have taken STFT of the EEG data. The resulting image is of Time And Frequency. This time-frequency image should be the input of CNN. Different epochs in EEG data have different Time-Frequency images. On the bases of this time-frequency analysis the movements have to classified. How can this be done in MATLAB? Which pretrained model is best for this job

**Comment by fengyunxiaozi** [comment]
Nobody can tell you which pre-trained model is best for the job, you need to try! If you do not know how to use MatConvNet, just see the examples such as mnist and cifar provided.
