### ISSUE TITLE
Issue with vl_nnconv (CPU)

### ISSUE THREAD

**Issue by saurabhme** [vlfeat/matconvnet#104]
The outputs vary between cpu and gpu

x = rand(1, 1, 10, 'single', 'gpuArray');
f = rand(5, 5, 10, 'single', 'gpuArray');
b = gpuArray(single(1));

t = ceil(size(f, 1)/2);
pad = t - 1;
disp([ ... 
sum(x.*f(t, t, :))+b;
vl_nnconv(x, f, b, 'pad', pad, 'stride', 1); 
vl_nnconv(gather(x), gather(f), gather(b), 'pad', pad, 'stride', 1); 
]);

The outputs are different if f is 5x5x* but same if f is 3x3x*

**Comment by lenck** [comment]
Hehe, my Matlab just freezes when running the CPU version :)

**Comment by lenck** [comment]
Hmm, in my case matlab just freezes for the CPU code...

**Comment by saurabhme** [comment]
Awesome.Thanks.
