### ISSUE TITLE
cudnn library

### ISSUE THREAD

**Issue by kjw0612** [vlfeat/matconvnet#106]
Anyone successful using cuddn?
It seems matconvnet requires cudnn candidate release 2, but I cannot find the location for it.
The version currently on the official Nvidia website seems not working and they do not offer older candidates.
Can anyone send me the cudnn libraries that work with matconvnet (jiwon at alum.mit.edu)?
Thank you in advance.

**Comment by kjw0612** [comment]
I've got a compatible library from Umut Güçlü.
Works great!

**Comment by wangchuanxd** [comment]
@kjw0612  Hi. Can you send me a compatible cudnn library? (chuanxd@126.com) Thank you !
