### ISSUE TITLE
vl_compilenn('enableGpu', true) fails due to error in vl_compilenn

### ISSUE THREAD

**Issue by srlakhe** [vlfeat/matconvnet#1062]
I am using Matlab R2017b with MatConvNet 1.0-beta25 with CUDA 8.0

Error using vl_compilenn>nvcc_compile (line 615)
Command "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc" -c -o
"C:\matconvnet-1.0-beta25\matlab\mex\.build\bits\data.obj" "C:\matconvnet-1.0-beta25\matlab\src\bits\data.cu"
-DENABLE_GPU -DENABLE_DOUBLE -O -DNDEBUG -D_FORCE_INLINES --std=c++11 -I"C:\Program Files\MATLAB\R2017b\extern\include"
-I"C:\Program Files\MATLAB\R2017b\toolbox\distcomp\gpu\extern\include" -gencode=arch=compute_35,code=\"sm_35,compute_35\"
--compiler-options=/MD --compiler-bindir="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\..\VC\bin"  failed.

Error in vl_compilenn (line 487)
      nvcc_compile(opts, srcs{i}, objfile, flags) ;

**Comment by ZeyuFu** [comment]
Hi there, have you solved this issue?

**Comment by primasanjaya** [comment]
i have same issue

**Comment by foreignkey** [comment]
I solved this. I used matconvnet 1.0-beta24 version.

**Comment by daofeng2007** [comment]
@srlakhe Did you install beta25 successfully? I got the same problem with yours. I also have Matlab R2017b with MatConvNet 1.0-beta25 with CUDA 8.0, plus windows 10.

**Comment by AnnieZhong** [comment]
I changed matconvnet version to 1.0-beta24, but still ocurring error. Anybody have solutions?

**Comment by AnnieZhong** [comment]
Thank God! I have successfully made it! For almost one week! I changed cudnn version to 5.1, and it worked. I used cudnn7.1,the newest version of CUDA8.0 before.
Now, my version matching is:
Matlab2017a
Visual Studio professional 2015
CUDA8.0
cudnn5.1
win7
Hope it can help.

**Comment by chaitingloveziyou** [comment]
You can try this. It works.
cd F:\matconvnet
addpath matlab
vl_compilenn('enableGpu', true, ...
'cudaRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1', ...
'cudaMethod', 'nvcc')
My configuration is:  win10+vs2017(with 2015 C++ library)+matlab2017b+CUDA9.1+CUDNN7.0

**Comment by jawadMansoor** [comment]
So I have been stuck at this for 2 weeks and finally got it working.

I followed these steps exactly
1) uninstall anything NVIDIA including your current driver. (restart)
2) delete anything NVIDIA from program files and program files x86 
3) install visual studio (i Used 13)
4) install cuda 8.0
5) install cudNN 5.1
6) upgrade display driver (you might have to restart)
7) used Matconvnet beta 24

and it works

I have windows 10, gtx 1050, vs13, cuda8, and cudNN 5.1

I hope it helps

**Comment by CHONSPQX** [comment]
i use matlabR2018a ,vs2017 community ,cuda9.2 ,cudnn7.14 and matconvnet1.0-beta25.
i have the same problem.
i found the path 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\bin' don't exist .
then i create a new folder 'bin' in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC'.
then it works.

i think you should check for the existencee of **--compiler-bindir** .

**Comment by worstkid92** [comment]
@CHONSPQX I use matlab 2018b,vs2017,cuda9.1 cudnn9.1
And i tried  creating a new empty bin folder ,still same error

**Comment by worstkid92** [comment]
@CHONSPQX  could you tell me how to check --compiler-bindir ,I don;t know how to use this command line in this situation

**Comment by CHONSPQX** [comment]
> @worstkid92
if you find string like "--compiler-bindir="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC..\VC\bin" failed." after you read the error message, then you should create the bin folder in the right place.
if you have created the bin folder, i suggest you runing matlab as administrator to make sure that your compiler has the permission to access the folder.

**Comment by ShaodeYuOutlook** [comment]
% (2)  "--compiler-bindir="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC..\VC\bin" failed
%      (a) Check the directory and find NO this folder 
%      (b) Create the folder named 'bin'
%      (c) Add the directory to the Environment settings
% https://github.com/vlfeat/matconvnet/issues/1062

**Comment by jingyao16** [comment]
@CHONSPQX Great thanks! Me with matlab 2017b, vs 2017 professional, cuda 10.0, cudnn 10.1, follow your tips, it works!

**Comment by panjialei** [comment]
compiler-bindir="C:\Program Files
(x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\Hostx64"  failed
not  "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC..\VC\bin"
how can l do it

**Comment by BassantTolba1234** [comment]
> So I have been stuck at this for 2 weeks and finally got it working.
> 
> I followed these steps exactly
> 
> 1. uninstall anything NVIDIA including your current driver. (restart)
> 2. delete anything NVIDIA from program files and program files x86
> 3. install visual studio (i Used 13)
> 4. install cuda 8.0
> 5. install cudNN 5.1
> 6. upgrade display driver (you might have to restart)
> 7. used Matconvnet beta 24
> 
> and it works
> 
> I have windows 10, gtx 1050, vs13, cuda8, and cudNN 5.1
> 
> I hope it helps

can you kindly share the link you installed these version ?? please

**Comment by BassantTolba1234** [comment]
> Thank God! I have successfully made it! For almost one week! I changed cudnn version to 5.1, and it worked. I used cudnn7.1,the newest version of CUDA8.0 before.
> Now, my version matching is:
> Matconvnet 1.0-beta24
> Matlab2017a
> Visual Studio professional 2015
> CUDA8.0
> cudnn5.1
> win7
> Hope it can help.

can you kindly share the link you installed these version ?? please
