### ISSUE TITLE
nnpooling_cudnn.cu(49):error:identifier "cudnnTensorDescriptor_t" is undefined

### ISSUE THREAD

**Issue by wangchuanxd** [vlfeat/matconvnet#108]
Hi,

my current configuration:
      Ubuntu 14.04
      cuda-6.5
      MatlabR2013a

I compile matconvnet with:
 vl_compilenn('verbose', true, 'enableGpu', true, 'cudaRoot', '/usr/local/cuda-6.5', 'cudaMethod', 'nvcc', 'enableCudnn', true, 'cudnnRoot', '/home/wangchuan/matconvnet_install/local') ;

Before I compile, I installed cuDNN by:
                sudo tar -xvf cudnn-6.5-linux-R1.tgz
                sudo cp cudnn.h   /home/wangchuan/matconvnet_install/local
                sudo cp lib*  /home/wangchuan/matconvnet_install/local

second:  
                enter into the file: /home/wangchuan/matconvnet_install/local
                sudo ln -sf libcudnn.so.6.5.18 libcudnn.so.6.5
                sudo ln -sf libcudnn.so.6.5 libcudnn.so

third: 
                sudo gedit /etc/bash.bashrc
       add: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/wangchuan/matconvnet_install/local
               export LD_LIBRARY_PATH

       then: sudo ldconfig

After I installed cuDNN, cd  /home/wangchuan/matconvnet_install/matlab, revise Makefile, cause the compilation of GPU and CPU version was right before, I revised the following comment:
    
                ENABLE_CUDNN ?= y
                CUDNNROOT ?= /home/wangchuan/matconvnet_install/local

then I started matlab and typed the following command:

              >> addpath matlab
              >> vl_compilenn('verbose', true, 'enableGpu', true, 'cudaRoot', '/usr/local/cuda-6.5', 'cudaMethod', 'nvcc', 'enableCudnn', true, 'cudnnRoot', '/home/wangchuan/matconvnet_install/local') ;

the result is I got one of the errores as described in title, I want to find out the mistake I have made, anyone could tell me why? thank you so much!

**Comment by vedaldi** [comment]
Note: the makefile and vl_compilenn are entirely independent.

My suggestion would be to try with a newer MATLAB version (e.g. 2014b). Mathworks has changed the MEX compilation system quite a bit at some point after 2013a. While it is likely possible that this problem could be fixed in 2013a, it may be easier to switch!

**Comment by wangchuanxd** [comment]
@vedaldi I try with MATLAB version 2014b, and my final goal is to use vl_nnconv() function, at first, with r2013a, it failed, and I thought I would compile cudnn first, however, it appeared bugs as the tittle described. I reinstalled Matlabr201b according to your suggestion, and it worked! Thank you very much!
