### ISSUE TITLE
Issue: Error in vl_compilenn (line 487)       nvcc_compile(opts, srcs{i}, objfile, flags) ;

### ISSUE THREAD

**Issue by primasanjaya** [vlfeat/matconvnet#1088]
I have windows 10, GTX1080Ti, cuda toolkit 8, VS2015, cudnn v.7 and download matconvnet v.1-25

when i compile matconvnet v.1-25, i got this error:

Error using vl_compilenn>nvcc_compile (line 615)
Command "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc" -c -o
"E:\projects\matconvnet25\matlab\mex\.build\bits\data.obj" "E:\projects\matconvnet25\matlab\src\bits\data.cu" -DENABLE_GPU
-DENABLE_DOUBLE -DENABLE_CUDNN -I"local\cudnn\include" -O -DNDEBUG -D_FORCE_INLINES --std=c++11 -I"C:\Program
Files\MATLAB\R2016a\extern\include" -I"C:\Program Files\MATLAB\R2016a\toolbox\distcomp\gpu\extern\include"
-gencode=arch=compute_61,code=\"sm_61,compute_61\"  --compiler-options=/MD --compiler-bindir="C:\Program Files
(x86)\Microsoft Visual Studio 14.0\VC\..\VC\bin"  failed.

Error in vl_compilenn (line 487)
      nvcc_compile(opts, srcs{i}, objfile, flags) ;

Any sugestion why and how to solve?

**Comment by llddan** [comment]
hi，i have same problem with you，did you solve it？
Can you help me?
Thanks.

**Comment by primasanjaya** [comment]
i solved it, change your compiler. i used windows 10 SDK and everything's work.

**Comment by llddan** [comment]
Can you speak more in detail?：)Thank you very much.

**Comment by PeterHuang2015** [comment]
@primasanjaya Same here, it's interesting, did u mean that the error was caused by lack of windows sdk update?

**Comment by Jinxinshao** [comment]
can you say it in detail? thank you very much
