### ISSUE TITLE
error compiling with gpu

### ISSUE THREAD

**Issue by ManiShiyam** [vlfeat/matconvnet#110]
Hi,

I am new to this site. I am getting the following error. How can I compile it successfully?

Error using vl_compilenn>mex_link (line 429)
LINK : fatal error LNK1181: cannot open input file
'E:\matconvnet-master\matlab\mex\.build\vl_nnnormalize.obj'

Error in vl_compilenn>(parfor body) (line 388)
  mex_link(opts, objs, mex_dir, flags.link) ;

Error in vl_compilenn (line 385)
parfor i = 1:numel(mex_src)

**Comment by ssampang** [comment]
Hey, check my [issue](https://github.com/vlfeat/matconvnet/issues/113). My solution might work for you.

**Comment by pzhu10** [comment]
@Siyamalan, I also meet this issue, have your problem got solved ?

**Comment by Siyamalan** [comment]
No still having the same problem

**Comment by demondan** [comment]
Hi, I also meet this issue, have anyone solved the probelm?

**Comment by pzhu10** [comment]
Hey,@demondan,check my issue, My solution might work for you.
