### ISSUE TITLE
CudaArch compiler arguments not sent to compiler when using nvcc

### ISSUE THREAD

**Issue by KapSteR** [vlfeat/matconvnet#111]
vl_compilenn.m fails when compiling for GPU using nvcc.

I have tracked the error down to the following.

The pooling function fails due to an undefined atomic add function.
This function is not supported on CUDA architectures 1.3 and below.
The compiler thinks it needs to support all architectures and hence fails.

The reason the compiler thinks it need to support all architectures is, that an error in vl_compilenn.m causes the correct compiler arguments, that specify architecture, not to be send to nvcc.

**Comment by lenck** [comment]
Hi, sorry, your GPU is probably too old to be supported. In order to make it work on your GPU, you would have to rewrite the critical section of the pooling layer :/
