### ISSUE TITLE
CUDA_ERROR_UNKNOWN after compilation with GPU and cuda dnn

### ISSUE THREAD

**Issue by ssampang** [vlfeat/matconvnet#113]
Hi all,

As the title implies, I've gotten matconvnet to compile successfully on Ubuntu 14.04, Matlab R2013a with cuda-7.0 and the enableGPU and enableCudnn flags set to true.

When I try to run the net on a preprocessed image as instructed on this page (http://www.vlfeat.org/matconvnet/pretrained/), I get the following error:

Error using vl_nnconv
An unexpected error occurred during CUDA execution. The CUDA error was:
CUDA_ERROR_UNKNOWN

Error in vl_simplenn (line 153)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;
 
Since the error itself isn't giving us much info, I'm not sure how to fix this. Any help would be greatly appreciated.

EDIT: I forgot to mention that when I first tried to run the code, I also got this error:

Invalid MEX-file '/home/sid/Projects/matconvnet/matlab/mex/vl_nnconv.mexa64': libcudart.so.7.0: cannot open shared object file: No such file or directory

and this error:

Invalid MEX-file '/home/sid/Projects/matconvnet/matlab/mex/vl_nnconv.mexa64': libcudnn.so.6.5: cannot open shared object file: No such file or directory

I fixed them by symlinking the libraries to /usr/local/MATLAB/R2013a/bin/glnxa64 and that brought me to my current error.

**Comment by ssampang** [comment]
I figured it out. This occurred due to an error with the cuda libraries working with the graphics driver I had installed. When I installed the toolkit (7.0), I opted to install the driver that was supplied with it just to be safe even though it was actually a downgrade (I had something like 346.46 and the toolkit came with 331). I thought this would ensure that the toolkit worked, but it actually caused me problems. 

To see if this is your issue, first make sure that you can run the example code you get with cuda by following the steps at http://docs.nvidia.com/cuda/cuda-getting-started-guide-for-linux/#recommended-post. If you get to the steps of running deviceQuery and bandwidthTest and they error out with a message about not being able to communicate with cuda or the gpu for 30 tries, then you probably have the same problem I did. Sorry, I rebooted my system and don't have access to the exact error messages now since I fixed the problem.

You should also be getting some errors when you run:
sudo modinfo nvidia-uvm

and:

sudo modprobe -v nvidia-uvm

The fix is simply to download and install the latest drivers from nvidia (http://www.nvidia.com/Download/index.aspx?lang=en-us). Make sure you get it straight from the site and not through Ubuntu, which caused problems for me.

After this, execute the 2 commands above to check that the driver is installed correctly, then check if the cuda examples work, and if they both do, you should be set to run matconvnet.

**Comment by lenck** [comment]
Thanks for the tips! :)

**Comment by CharlesShang** [comment]
@ssampang  Thanks for your tips! 
For more details,
I did remove nvidia-331 
    apt-get remove nvidia-331 
and install NVIDIA-Linux-x86_64-346.72.run.
   # goto Ctrl+Alt+F1 to stop mdm(or gdm, lightdm)
   sudo stop mdm
   sudo init 3
   sudo ./NVIDIA-Linux-x86_64-346.72.run
   # after it was installed, start mdm, and goto Ctrl+Alt+F8
   sudo start mdm
Reinstall cuda-7-0 using apt-get

**Comment by vivoutlaw** [comment]
Use this and everything is fixed. No need to reinstall cuda.

export LD_PRELOAD=/usr/lib64/libstdc++.so.6
export LD_LIBRARY_PATH=/usr/local/cuda-7.0/lib64:$LD_LIBRARY_PATH  

Thanks and best, Vivek
