### ISSUE TITLE
Add regression layer to MatConvNet

### ISSUE THREAD

**Issue by hajizadeh** [vlfeat/matconvnet#115]
Hi
I have implemented a smile detection system based on deep learning. The bottom layer is the output of the system and has 10 output according to the amount of the person's smile. I want to convert these ten output with a numeric output in the range of 1 to 10 with a regression layer.
How can I do this in MatConvNet.
Thanks

**Comment by bazilas** [comment]
You have to write a new loss function to perform regression. Have a look on:  #15

cheers,
Vasilis

**Comment by umuguc** [comment]
I have a Euclidean loss implementation here:
https://github.com/umuguc/matconvnet/blob/master/examples/mnistAutoencoder/euclideanloss.m
If you are using vl_simplenn.m, you should modify it accordingly.

**Comment by hajizadeh** [comment]
thank you so much, i have got it.

**Comment by prashnani** [comment]
@umuguc Can you suggest how to change the error function in cnn_train to Mean Squared Error for the regression problem?

**Comment by kbenahmed89** [comment]
@prashnani did you find a way to change the error function to mean squared error ?

**Comment by prashnani** [comment]
@kbenahmed89 #15 #97 and #115 give an idea of how this can be done. Thanks!
