### ISSUE TITLE
vl_test_imreadjpeg failed: SSSE3 instruction set not enabled

### ISSUE THREAD

**Issue by ssampang** [vlfeat/matconvnet#118]
Hi all,

As the title says, when I try to run vl_test_imreadjpeg, my Matlab crashes. When compiling, I noticed a warning message:
`In file included from matlab/src/bits/impl/imread_libjpeg.cpp:14:0:
matlab/src/bits/impl/imread_helpers.hpp:35:2: warning: #warning "SSSE3 instruction set not enabled. Using slower image conversion routines." [-Wcpp]
 #warning "SSSE3 instruction set not enabled. Using slower image conversion routines."`

I also get a whole bunch of these:

```Warning: You are using gcc version "4.8.2".  The version
         currently supported with MEX is "4.4.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/```

but I am assuming that's less important. Any help would be greatly appreciated as I'm guessing that this will slow training down. 

After some googling, I saw posts recommending that I add flags to the makefile (eg. `-march=native` or `-msse4`), but I wasn't sure where I should be putting them. I tried putting them in the MEXFLAGS and NVCCFLAGS variables as that's where the `-ssse3` flag is also set, but there was no change after recompiling. I'm running on Ubuntu btw.

Thanks,
Sid

**Comment by vedaldi** [comment]
Hi,

the non-SSSE3 version is only marginally slower so I would not worry too much (although it is odd that your CPU does not support it). The second message about 4.8.2 is rarely a problem.

Of course, the crash is much more serious. Could you please let me know your MATLAB, Linux, CPU versions/models? Does the crash occur with any image? If not, can you provide a minimal example with an image that causes the crash?

**Comment by ssampang** [comment]
Hi,

I'm running Matlab 2013a on ubuntu 14.04 with an i5 4670K and a gtx760. I'm unclear about what you mean by "occur with any image". Could you please clarify? Are you referring to an actual image thats fed into vl_imreadjpeg as an argument? After setting breakpoints, the crash seems to be occurring on the calls to vl_imreadjpeg associated with "Test inserting a non-image file" and "Test inserting a non-existing file". If I comment these two lines out (and the associated assert statements), the code runs fine. Let me know if you need anymore info.

 Also, as I was answering this question, I checked the "About this computer" page on ubuntu and noticed that it said "GeForce GTX 760/PCIe/SSE2" for my graphics card. Is that SSE2 associated with the issue I'm having with ssse3?
