### ISSUE TITLE
Got nvcc error   : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)  when I compile matconvnet

### ISSUE THREAD

**Issue by AlphaGoMK** [vlfeat/matconvnet#1201]
I'm using matlab r2018a with vs2017 community and cuda 9.0.
When I download the latest version of matconvnet and compile it using `vl_compilenn`  in matlab, I got nvcc error
```
0x00007FF64188ADD0 (0x0000000000000000 0x000001E56C1C7F18 0x000066BA00000001 0x00000004000304ED) 
0x00007FF641886F3D (0x0000009EBEFFE798 0x0000000000000000 0x0000000000000000 0x000001E56C1DCE20) 
0x00007FF641888713 (0xnvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored. 
data.cu 
nvcc error   : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION) 
Error using vl_compilenn>nvcc_compile (line 615)
Command "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc" -c -o
"D:\Matlab\matconvnet-1.0-beta25\matconvnet-1.0-beta25\matlab\mex\.build\bits\data.obj"
"D:\Matlab\matconvnet-1.0-beta25\matconvnet-1.0-beta25\matlab\src\bits\data.cu" -DENABLE_GPU -DENABLE_DOUBLE
-DENABLE_CUDNN -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -O -DNDEBUG -D_FORCE_INLINES
--std=c++11 -I"D:\Matlab\extern\include" -I"D:\Matlab\toolbox\distcomp\gpu\extern\include"
-gencode=arch=compute_52,code=\"sm_52,compute_52\"  --compiler-options=/MD --compiler-bindir="C:\Program
Files (x86)\Microsoft Visual Studio\2017\Community\VC\bin"  failed.

Error in vl_compilenn (line 487)
      nvcc_compile(opts, srcs{i}, objfile, flags) ;
```

Any advice will be appreciated.

**Comment by AlphaGoMK** [comment]
Problem solved after I uninstalled the CUDA 9.0 and reinstalled CUDA 10.0.
It seems that Visual Studio 2017 may not work well with Cuda 9.0 and Matlab R2018a.

**Comment by HXZhong1997** [comment]
Hello, @AlphaGoMK . I'm encountering the same error here. I'm using matlab r2017b + vs2017 community + CUDA 10.1 + cudnn 7.5.  Could you plz give me some advice on this problem? 
I don't think it's reasonable if there is a problem of VS2017 not working with newer CUDA version, but please do give me some advice if  you suggest reinstalling sth. 
Thank you so much. 
![error-clip](https://user-images.githubusercontent.com/33387338/53680442-a0ed6c80-3d16-11e9-8bc0-a88562e523be.png)

**Comment by AlphaGoMK** [comment]
> Hello, @AlphaGoMK . I'm encountering the same error here. I'm using matlab r2017b + vs2017 community + CUDA 10.1 + cudnn 7.5. Could you plz give me some advice on this problem?
> I don't think it's reasonable if there is a problem of VS2017 not working with newer CUDA version, but please do give me some advice if you suggest reinstalling sth.
> Thank you so much.
> ![error-clip](https://user-images.githubusercontent.com/33387338/53680442-a0ed6c80-3d16-11e9-8bc0-a88562e523be.png)

Maybe you could try to install CUDA 10.0 instead of 10.1?

BTW, I wrote a blog for how to install on Zhihu in **CHINESE**.    
[Link](https://zhuanlan.zhihu.com/p/57132601)  
Feel free to ask if you need an English version.

**Comment by HXZhong1997** [comment]
> > Hello, @AlphaGoMK . I'm encountering the same error here. I'm using matlab r2017b + vs2017 community + CUDA 10.1 + cudnn 7.5. Could you plz give me some advice on this problem?
> > I don't think it's reasonable if there is a problem of VS2017 not working with newer CUDA version, but please do give me some advice if you suggest reinstalling sth.
> > Thank you so much.
> > ![error-clip](https://user-images.githubusercontent.com/33387338/53680442-a0ed6c80-3d16-11e9-8bc0-a88562e523be.png)
> 
> Maybe you could try to install CUDA 10.0 instead of 10.1?
> 
> BTW, I wrote a blog for how to install on Zhihu in **CHINESE**.
> [Link](https://zhuanlan.zhihu.com/p/57132601)
> Feel free to ask if you need an English version.

It turned out that my CUDA version is too high, I changed it to v9.0 and it worked.
Thanks for your blog in Zhihu, it does help a lot.
谢谢~ ;-)

**Comment by AlphaGoMK** [comment]
Solved
