### ISSUE TITLE
vl_imreadjpeg not working: Returns images that are almost binary

### ISSUE THREAD

**Issue by ssampang** [vlfeat/matconvnet#121]
Hi all,

I've tried varying images, but vl_imreadjpeg cant seem to read them in correctly. I need to eventually work with grayscale images, but even if I use color RGB jpeg input images, vl_imreadjpeg returns images with pixel intensities that are either 0, 255 or very close to one or the other. Any help is appreciated. 

Running Matlab 2013a on Ubuntu with cuda-7.0 and compiling with gpu support and cudnn.

**Comment by vedaldi** [comment]
Hi, could you please send an example of an input image that does not work?

Also, are you running in Windows, Linux, or Mac? the function uses the native OS image reading functions so bugs are likely to be platform-dependent.

**Comment by ssampang** [comment]
Hi,

Here's an example of an image: http://i.imgur.com/0YBmIRQ.jpg
Here's the output I get from vl_imreadjpeg: http://i.imgur.com/RwvsKdh.jpg

I'm running on Linux (Ubuntu). Do you by any chance know how I can test the native image reading functions? My team mate is running the library on Mac and having the same issue, so I suspect both of us are making the same mistake somewhere....I have mentioned a possibly related issue in #118. 

Here are the steps I go through to setup matconvnet as soon as I open matlab and before I run vl_imreadjpeg: 

`addpath matlab/
vl_compilenn
vl_compilenn('enableGpu',true,'enableImreadJpeg',true,'cudaRoot','/usr/local/cuda-7.0','cudaMethod','nvcc','enableCudnn','true','cudnnRoot','cudnn-6.5-linux-x64-v2/')`


Thanks,
Sid

**Comment by vedaldi** [comment]
Hi, I think this is fine. MATALB expects images to be in the range 0,1 if they are floating point. MatConvNet uses the range 0,255 for compatibility with most NN implementation (mainly Caffe actually). In short, just use

imagesc(im/255)

to visualise the image (or similar for imwrite to save it).

**Comment by ssampang** [comment]
Thanks a lot!
