### ISSUE TITLE
 vl_compilenn>nvcc_compile (line 521) please help me!!!

### ISSUE THREAD

**Issue by CC-Cola** [vlfeat/matconvnet#1216]
Now i have some new problem,please help me!!!  When I compiled matconvnet-beta-20 with CUDA 9.2, I had the following problems as follows:

C:/Users/Administrator/Desktop/matconvnet-1.0-beta20/matlab/src/bits/impl/nnconv_cudnn.cu(137): error: too few arguments in function call 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with dataType=vl::vlTypeFloat]"  
(542): here 
 
C:/Users/Administrator/Desktop/matconvnet-1.0-beta20/matlab/src/bits/impl/nnconv_cudnn.cu(354): error: too few arguments in function call 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with dataType=vl::vlTypeFloat]"  
(542): here 
 
C:/Users/Administrator/Desktop/matconvnet-1.0-beta20/matlab/src/bits/impl/nnconv_cudnn.cu(137): error: too few arguments in function call 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with dataType=vl::vlTypeDouble]"  
(545): here 
 
C:/Users/Administrator/Desktop/matconvnet-1.0-beta20/matlab/src/bits/impl/nnconv_cudnn.cu(354): error: too few arguments in function call 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<dataType>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with dataType=vl::vlTypeDouble]"  
(545): here 
 
4 errors detected in the compilation of "C:/Users/ADMINI~1/AppData/Local/Temp/tmpxft_0000119c_00000000-10_nnconv_cudnn.cpp1.ii". 
nnconv_cudnn.cu 
错误使用 vl_compilenn>nvcc_compile (line 521)
Command "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\nvcc" -c
"C:\Users\Administrator\Desktop\matconvnet-1.0-beta20\matlab\src\bits\impl\nnconv_cudnn.cu" -DNDEBUG -DENABLE_GPU -DENABLE_CUDNN
-Ilocal\cudnn-9.2-windows10-x64-v7.4.1.5\cuda\include -DENABLE_DOUBLE -D__SSSE3__
-gencode=arch=compute_61,code=\"sm_61,compute_61\"  -I"E:\MATLAB\R2016b\extern\include"
-I"E:\MATLAB\R2016b\toolbox\distcomp\gpu\extern\include"  -gencode=arch=compute_61,code=\"sm_61,compute_61\"  -Xcompiler /MD -o
"C:\Users\Administrator\Desktop\matconvnet-1.0-beta20\matlab\mex\.build\bits\impl\nnconv_cudnn.obj" failed.

出错 vl_compilenn (line 466)
      nvcc_compile(opts, srcs{i}, objfile, flags.nvcc) ;
 

I don't know how to solve it. Please help me, I'm going to cry!!!

**Comment by yummycats** [comment]
你好！我遇到了和你一样的问题，请问你解决了吗!wuwuwu

**Comment by CC-Cola** [comment]
你好，我还没有解决呢，这几天没在单位，待会到了后我再挣扎挣扎 (ง •̀_•́)ง------------------ 原始邮件 ------------------
发件人: "yummycats"<notifications@github.com>
发送时间: 2019年5月28日(星期二) 凌晨2:23
收件人: "vlfeat/matconvnet"<matconvnet@noreply.github.com>;
抄送: "CC-Cola"<2084595068@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vlfeat/matconvnet]  vl_compilenn>nvcc_compile (line 521) pleasehelp me!!! (#1216)



你好！我遇到了和你一样的问题，请问你解决了吗!wuwuwu
 
&mdash;

**Comment by CC-Cola** [comment]
你好，我弄好了，换了个稍低版本的cudnn，还是版本不匹配问题。------------------ 原始邮件 ------------------
发件人: "yummycats"<notifications@github.com>
发送时间: 2019年5月28日(星期二) 凌晨2:23
收件人: "vlfeat/matconvnet"<matconvnet@noreply.github.com>;
抄送: "CC-Cola"<2084595068@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vlfeat/matconvnet]  vl_compilenn>nvcc_compile (line 521) pleasehelp me!!! (#1216)



你好！我遇到了和你一样的问题，请问你解决了吗!wuwuwu
 
&mdash;

**Comment by yummycats** [comment]
你好！我的是matlab2018b+cuda9.1+cudnn4（因为前面报错于是改成了非常低的版本），不知道楼主式用什么版本cudnn？

**Comment by CC-Cola** [comment]
你好，我的是matlab2016b+cuda9.2+cudnn7.1.4。原来的cudnn版本是7.4.1。------------------ 原始邮件 ------------------
发件人: "yummycats"<notifications@github.com>
发送时间: 2019年6月3日(星期一) 晚上6:03
收件人: "vlfeat/matconvnet"<matconvnet@noreply.github.com>;
抄送: "CC-Cola"<2084595068@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [vlfeat/matconvnet]  vl_compilenn>nvcc_compile (line 521) pleasehelp me!!! (#1216)



你好！我的是matlab2018b+cuda9.1+cudnn4（因为前面报错于是改成了非常低的版本），不知道楼主式用什么版本cudnn？
 
&mdash;

**Comment by yummycats** [comment]
好的谢谢！我用这个版本也成功了！

> 你好，我的是matlab2016b+cuda9.2+cudnn7.1.4。原来的cudnn版本是7.4.1。------------------ 原始邮件 ------------------ 发件人: "yummycats"<notifications@github.com> 发送时间: 2019年6月3日(星期一) 晚上6:03 收件人: "vlfeat/matconvnet"<matconvnet@noreply.github.com>; 抄送: "CC-Cola"<2084595068@qq.com>;"State change"<state_change@noreply.github.com>; 主题: Re: [vlfeat/matconvnet] vl_compilenn>nvcc_compile (line 521) pleasehelp me!!! (#1216) 你好！我的是matlab2018b+cuda9.1+cudnn4（因为前面报错于是改成了非常低的版本），不知道楼主式用什么版本cudnn？ &mdash; You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by CC-Cola** [comment]
不客气😁😁------------------ 原始邮件 ------------------
发件人: "yummycats"<notifications@github.com>
发送时间: 2019年6月3日(星期一) 晚上8:36
收件人: "vlfeat/matconvnet"<matconvnet@noreply.github.com>;
抄送: "CC-Cola"<2084595068@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [vlfeat/matconvnet]  vl_compilenn>nvcc_compile (line 521) pleasehelp me!!! (#1216)



好的谢谢！我用这个版本也成功了！
  
你好，我的是matlab2016b+cuda9.2+cudnn7.1.4。原来的cudnn版本是7.4.1。------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "yummycats"notifications@github.com 发送时间: 2019年6月3日(星期一) 晚上6:03 收&#x4EF6;人: "vlfeat/matconvnet"matconvnet@noreply.github.com; 抄送: "CC-Cola"2084595068@qq.com;"State change"state_change@noreply.github.com; 主题: Re: [vlfeat/matconvnet] vl_compilenn>nvcc_compile (line 521) pleasehelp me!!! (#1216) 你好！我的是matlab2018b+cuda9.1+cudnn4（因为前面报错于是改成了非常低的版本），不知道楼主式用什么版本cudnn？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
  
&mdash;
