### ISSUE TITLE
Compatibility with Caffe -- R-CNN question

### ISSUE THREAD

**Issue by eakbas** [vlfeat/matconvnet#124]
I know that matconvnet is not fully compatible with Caffe as it doesn't implement all type of layers that Caffe has. What I'm interested in specifically is the R-CNN model (Girschick et al CVPR 2014). Here is its Caffe definition https://github.com/rbgirshick/rcnn/blob/master/model-defs/pascal_finetune_deploy.prototxt  Could somebody tell me whether this Caffe model is compatible with matconvnet? 

Would running import-caffe.py tell me whether a saved R-CNN (i.e. Caffe) model is compatible with matconvnet? 

Thanks.

**Comment by lenck** [comment]
Hi, the vanilla R-CNN should be running fine with MatConvNet. However, you would have to add some machinery to perform the selective search, image cropping and non-maxima suppression...
