### ISSUE TITLE
multi GPU support

### ISSUE THREAD

**Issue by xcyan** [vlfeat/matconvnet#128]
Hi,

I did compare the multiGPU version and singleGPU version of matconvnet. But unfortunately, the multiGPU version is much slower than singleGPU version. While running cnn_train.m, the most of time was spent on "spmd" command.

Anyone has similar problems?

**Comment by vedaldi** [comment]
Hi, the multi-GPU version makes sense only if batches are sufficiently expensive as the communication overhead is very significant.

Also, MATLAB needs to create a temporary file to support communication (see the options). You may want to make sure that this file is in ramdisk.

**Comment by Jerrynet** [comment]
@vedaldi Hi, did you consider using 'gplus' or 'gop' function in spmd?

**Comment by itaykez** [comment]
Hi Andrea, 
Why do you write to a file (and read) and not using MPI operations?

**Comment by venkat-purdue** [comment]
I was looking for an example with multi-GPU support. I did come across https://github.com/vlfeat/matconvnet/issues/101. However, I was not able to find an example of using the multi-GPU support in the current master brach. Is there such an example available ?

**Comment by lenck** [comment]
Hi, it is quite simple, just specify more gpus, e.g.:
```
cnn_imagenet_train('train', struct('gpus', [1, 2]))
```
