### ISSUE TITLE
vl_test_nnlayers cannot work

### ISSUE THREAD

**Issue by mowangphy** [vlfeat/matconvnet#13]
Hi,

I have compile MatconvNet successfully on Linux by using the command 'make ENABLE_GPU=y ENABLE_IMREADJPEG=y ARCH=glnxa64 MATLABROOT=/eecs/local/pkg/matlab-r2014a CUDAROOT=/eecs/local/pkg/cuda-6.5.14'. However, when I installed MatconvNet in matlab and tried to run vl_test_nnlayers, the error happened, and the outputs are shown below:

test number 1
testing vl_nnsoftamxloss multiple images convolutional
test number 2
testing vl_nnloss multiple images convolutional
testing vl_nnloss multiple images
testing vl_nnloss
test number 3
testing vl_nnsoftmax
test number 4
testing vl_nnconv with fully connected identity filters
Attempt to execute SCRIPT vl_nnconv as a function:
/eecs/research/asr/hengyue/matconvnet-1.0-beta7/matconvnet-1.0-beta7/matlab/vl_nnconv.m

Error in vl_test_nnlayers (line 110)
      y = vl_nnconv(x,[],b,'verbose') ;

Seems like there are some problem about the script vl_nnconv.m. Is anyone have some hint to deal with this problem? Thank you:-)

**Comment by sunilrao43** [comment]
@vedaldi  will it work for matlab 2013a and cuda 6.5 or should downgrade it

**Comment by vedaldi** [comment]
Hi, it should probably work with the ‘nvcc’ method. See here: http://www.vlfeat.org/matconvnet/install/#nvcc <http://www.vlfeat.org/matconvnet/install/#nvcc>

However, 2013a uses the old-style .sh configuration files for the compiler. It should work, but it may require some tweaks.

**Comment by sunilrao43** [comment]
@vedaldi 

Error using mex (line 206)
Unable to complete successfully.

Error in vl_compilenn>mex_compile (line 376)
mex(mopts{:}) ;

Error in vl_compilenn>(parfor body) (line 345)
    mex_compile(opts, srcs{i}, toobj(bld_dir,srcs{i}), flags.mexcc) ;

Error in vl_compilenn (line 337)
parfor i = 1:numel(horzcat(lib_src, mex_src))

Caused by:
    Error using mex (line 206)
    Unable to complete successfully.

**Comment by sunilrao43** [comment]
@vedaldi  same error mentioned above when i try the testlayer on CPU

**Comment by talenz** [comment]
change the name of the file "vl_nnconv.m" to "vl_nnconv_backup.m"

**Comment by gracejo** [comment]
I'm not using GPU, just CPU and i've have such an error as well. currently using matlab 2014a. Hope i can get some help here. 

>> vl_test_nnlayers
testing the CPU code
test number 1
testing vl_nnsoftamxloss multiple images convolutional
test number 2
testing vl_nnloss multiple images convolutional
testing vl_nnloss multiple images
testing vl_nnloss
test number 3
testing vl_nnsoftmax
test number 4
testing vl_nnconv with fully connected identity filters
Attempt to execute SCRIPT vl_nnconv as a function:
C:\Users\Josephine\Desktop\Matconvnet\matconvnet-1.0-beta11.tar\matconvnet-1.0-beta11\matconvnet-1.0-beta11\matlab\vl_nnconv.m

Error in vl_test_nnlayers (line 124)
      y = vl_nnconv(x,[],b,'verbose') ;

**Comment by mowangphy** [comment]
@gracejo don't care about this problem, just try to run the cnn demos in the folder 'examples' ...

**Comment by zijunwei** [comment]
I have similar problem, I found if commented this line:
```
addpath('matlab')
```

everything goes fine.

**Comment by vedaldi** [comment]
Hi, are these problems solved in beta 13?

Were did you find the addpath(‘matlab’) line?

**Comment by zijunwei** [comment]
Sorry for the confusion.
I cloned code directly from github. In my own code I added addpath('matlab') trying to directly calling the interfaces the authors provided. It turns out to be not necessary and mistake.
try this:
```
vl_comiplenn(true,'cudaRoot','yourdir');
run matlab/vl_setupnn
addpath('matlab')
vl_test_nnlayers(true)
```
the above code will reproduce the error. The error goes away if you run:
 
```
vl_comiplenn(true,'cudaRoot','yourdir');
run matlab/vl_setupnn
vl_test_nnlayers(true)
```

**Comment by vedaldi** [comment]
Hi, ok, great ! Thanks.
