### ISSUE TITLE
Problem with batchSize>35 

### ISSUE THREAD

**Issue by ssampang** [vlfeat/matconvnet#130]
Hi all,

We're trying to train a net with input image size (400,400,3) that works fine on CPU and GPU with batch sizes of 35 or less, but gives us the following error if we exceed that:
```
learning rate changed (0.000000 --> 0.010000): resetting momentum
training: epoch 01: processing batch   1 of   4 ...Error using vl_nnpool
nnpooling_backward: : cuda error [cuda: pooling_*_backward: : invalid
argument]

Error in vl_simplenn (line 206)
        res(i).dzdx = vl_nnpool(res(i).x, l.pool, res(i+1).dzdx, ...

Error in cnn_train (line 136)
    res = vl_simplenn(net, im, one, res, ...

Error in cnn_drnet (line 50)
[net,info] = cnn_train(net, imdb, fn, opts.train, 'conserveMemory', true) ;
```

We're running on matlab 2015a on Ubuntu with a K40 and cudnn enabled. Any tips?

Thanks,
Sid

**Comment by xcyan** [comment]
I think you need to monitor the memory usage.

**Comment by ssampang** [comment]
Sorry for the late reply. We did monitor the memory usage and there was roughly 4-5 gigs of unused memory.

**Comment by zoharby** [comment]
Had the same problem, updated to beta13 and now it's gone.
