### ISSUE TITLE
Issue with vl_nnconv

### ISSUE THREAD

**Issue by xcyan** [vlfeat/matconvnet#132]
A = vl_nnconv(gpuArray(randn(1,1,10,2,'single')), gpuArray(randn(2,2,10,5,'single')), gpuArray(randn(1,5,'single')), 'pad', [1 1 1 1], 'stride', 1); % doesn't work

A = vl_nnconv(randn(1,1,10,2,'single'), randn(2,2,10,5,'single'), randn(1,5,'single'), 'pad', [1 1 1 1], 'stride', 1); % work

**Comment by Jerrynet** [comment]
Hi, I tested your code, both cpu and gpu code executed normally.
Environment: 
os: ubuntu 14.04, gpu: titan x, cuda version: 6.5, matlab version: 2014b

**Comment by xcyan** [comment]
Have you tried to run this command with cudnn acceleration?

**Comment by Jerrynet** [comment]
I didn't.
And there is a bug of cuDNN v2 on linux, see comment of vl_nnconv.m

> If compiled in, the function will use cuDNN convolution routines
> (with the exception of asymmetric left-right or top-bottom
> padding and a few corner cases such as 1x1 filters in Linux that
> trigger current bugs in cuDNN)

Also described a solution -> just disable the cuDNN support

> You can use the 'NoCuDNN' option
> to disable cuDNN or 'cuDNN' to activate it back again (the choice
>sticks until MATLAB purges the MEX files for any reason).

**Comment by vedaldi** [comment]
Hi, I believe that some of these bugs have been ironed out in the recent cuDNN versions. If you compile against those it should be ok. MatConvNet now should use CuDNN for 1x1 filters too.
