### ISSUE TITLE
Problem with vl-compilenn

### ISSUE THREAD

**Issue by sumo8291** [vlfeat/matconvnet#133]
I am using 64bit Matlab 2013a in Windows 7.  I am trying to compile the CPU version of the library. Compilers installed in my system are Microsoft C++ Visual Studio 2012, and Microsoft SDK 7.1. I am getting an error as shown 
![image](https://cloud.githubusercontent.com/assets/8149573/7466982/420ce162-f2a3-11e4-8936-f0ccf07392a9.png).

Can you please help how to remove the error?

thanks a lot

**Comment by willard-yuan** [comment]
I also compile it failed on Matlab2013, but you can find a compiled version and it's can be used on Matlab 2013 directly @sumo8291.

**Comment by liangzimei** [comment]
can you share the compiled version with me ? thanks...@willard-yuan

**Comment by liangzimei** [comment]
hello ,have you solved the problem?@sumo8291

**Comment by willard-yuan** [comment]
Sure, you can down the complied version from [here](https://github.com/willard-yuan/CNN-for-Image-Retrieval/blob/master/matconvnet-1.0-beta10.rar?raw=true),@liangzimei

**Comment by liangzimei** [comment]
thank you very much .i find it is the same as the version on the homepage of matconvnet, is it?@willard-yuan

**Comment by willard-yuan** [comment]
Sorry for replying later. I have update it and you can download the complied version from [here](https://github.com/willard-yuan/CNN-for-Image-Retrieval/blob/master/matconvnet-1.0-beta10.rar?raw=true). @liangzimei

**Comment by sumo8291** [comment]
i have installed matlab 2014 b version.. and it got compiled properly

**Comment by mingtop** [comment]
I download 2015a , fixed this problom

**Comment by RichelLi** [comment]
vl_compilenn('verbose',2)
vl_compilenn: * Compiler and linker configurations *
vl_compilenn: 	intermediate build products directory: E:\闫鹏刚\数据和程序\下载\Vlfeat\matconvnet-1.0-beta10 (1)\matconvnet-1.0-beta10\matlab\mex\.build
vl_compilenn: 	MEX files: E:\闫鹏刚\数据和程序\下载\Vlfeat\matconvnet-1.0-beta10 (1)\matconvnet-1.0-beta10\matlab\mex/
vl_compilenn: 	MEX compiler options: -v -DNDEBUG -D__SSSE3__ -cxx
vl_compilenn: 	MEX linker options: -v -lmwblas -lgdiplus
vl_compilenn: * Reading images *
vl_compilenn: 	vl_imreadjpeg enabled
vl_compilenn: 	image library: gdiplus
vl_compilenn: 	image library compile flags: 
vl_compilenn: 	image library link flags: -lgdiplus
Starting parallel pool (parpool) using the 'local' profile ... 
vl_compilenn: MEX: -outdir E:\闫鹏刚\数据和程序\下载\Vlfeat\matconvnet-1.0-beta10 (1)\matconvnet-1.0-beta10\matlab\mex\.build matlab\src\vl_imreadjpeg.cpp -c -v -DNDEBUG -D__SSSE3__ -cxx
错误使用 vl_compilenn>mex_compile (line 411)
未找到 E:\闫鹏刚\数据和程序\下载\Vlfeat\matconvnet-1.0-beta10
(1)\matconvnet-1.0-beta10\matlab\matlab\src\vl_imreadjpeg.cpp；请检查您是否位于正确的当前文件夹，并检查
'E:\闫鹏刚\数据和程序\下载\Vlfeat\matconvnet-1.0-beta10
(1)\matconvnet-1.0-beta10\matlab\matlab\src\vl_imreadjpeg.cpp' 的拼写。

出错 vl_compilenn>(parfor body) (line 380)
    mex_compile(opts, srcs{i}, toobj(bld_dir,srcs{i}), flags.mexcc) ;

出错 vl_compilenn (line 371)
parfor i = 1:numel(horzcat(lib_src, mex_src))

**Comment by RichelLi** [comment]
I don't know how to deal with it

**Comment by ArmentiGuglimo** [comment]
link to compiled version not working

**Comment by vedaldi** [comment]
Hi, thanks for helping. R2013 is a bit too old for us to support, mainly given that it does not have GPU support I believe. We recommend using at least R2014b.

(Having said that, it should be possible to make the CPU version work with older MATLABs too)

**Comment by lenck** [comment]
Hi, this has been, hopefully solved with [this pull request](https://github.com/vlfeat/matconvnet/pull/381).
