### ISSUE TITLE
error compiling with gpu cannot open input file vl_nnconv.obj

### ISSUE THREAD

**Issue by pzhu10** [vlfeat/matconvnet#134]
Error using vl_compilenn>mex_link (line 449)
LINK : fatal error LNK1181:cannot open input file
“E:\MATLAB\matconvnet\matlab\mex\.build\vl_nnconv.obj”
I compiled the MatConvNet (version 1.0-beta11) in windows7 64bits + VS2010 + cuda6.5,
could anybody help me out ?

@Siyamalan, have your problem got solved ? 
@lenck could you help me ?

**Comment by Siyamalan** [comment]
No still having the same problem.

**Comment by pzhu10** [comment]
I think i just pass this problem, I use the following compiling command:
vl_compilenn('enableGpu', true, ...
               'cudaRoot', 'D:\CUDA65\Toolkit', ...
               'cudaMethod', 'nvcc', ...
               'enableCudnn', 'true', ...
               'cudnnRoot', 'D:\CUDA65\cuDNNV2/')
and it goes well, but this means you need a GPU card whose compute capability >=3 
@Siyamalan  hope helpful for you.
