### ISSUE TITLE
running cnn_cifar on GPU

### ISSUE THREAD

**Issue by charlesboes** [vlfeat/matconvnet#142]
Hi, 
I am having some trouble running can_cifar on a GPU unit. 
the compilation of Matconvnet with GPU enabling seemed to have worked, but when I am trying to run can_cifar I get this message of error:

Error using vl_nnconv
nnconv_forward_blas<>: : gemm<>:  [cublas error] [cublas:cublasSgemm
(CUBLAS_STATUS_EXECUTION_FAILED)]

I get the same type of error running can_mnist.

I am using Matlab R2013a
CUDA-7.0
GPU: 'GeForce GTX 980'

Best Regards

**Comment by charlesboes** [comment]
Actually it seems like it's a cublas issue which is an cudaErrorInvalidTexture.
You can get rid of this error using cudNN implementation. One may also want to comment l.350-367 of vl_nnconv.cu to avoid using cublas for fully connected layers.

**Comment by RomainBUAA** [comment]
i use cundd ,but this error doesn't disappear

**Comment by RomainBUAA** [comment]
i use cudnn ,but this error doesn't disappear
