### ISSUE TITLE
overfeat port in matconvnet?

### ISSUE THREAD

**Issue by tumble-weed** [vlfeat/matconvnet#148]
Hi,
I wanted to know if the overfeat model was available for matconvnet, or suggestions on how to port it?

**Comment by lenck** [comment]
Hi, unfortunately the overfeat model is not available. AFAIK, it is using the spatial pyramid pooling on top of conv5 which is not implemented in MatConvNet. But if you would find a caffe model for it (I think there is one in the SPP R-CNN repository), you may try to convert the conv layers to MatConvNet model first and the the FC layers (by having two separate prototxt files).
