### ISSUE TITLE
vl_compilenn strrep

### ISSUE THREAD

**Issue by ankush-me** [vlfeat/matconvnet#155]
Lines 367-369 in https://github.com/vlfeat/matconvnet/blob/dev-dag/matlab/vl_compilenn.m :  
```matlab
objs = strrep(objs,'.cpp',['.' objext]) ;
objs = strrep(objs,'.cu',['.' objext]) ;
objs = strrep(objs,'.c',['.' objext]) ;
````
Can incorrectly replace paths which have these '.c' etc. substrings in them.
A better alternative is:
```matlab
objs = regexprep(objs,'.cpp$',['.' objext]) ;
objs = regexprep(objs,'.cu$',['.' objext]) ;
objs = regexprep(objs,'.c$',['.' objext]) ;
````
which will only match with these substrings if they occur at the end of the string.

**Comment by lenck** [comment]
Thanks for pointing this out!
