### ISSUE TITLE
Unsupported gpu architecture 'compute_21'

### ISSUE THREAD

**Issue by llyydd007** [vlfeat/matconvnet#156]
I have same problem when I am trying to enable compilation for the GPU for matconvet-1.0beta-12. It ended on this error: Unsupported gpu architecture 'compute_21' .  The CPU version is OK. And I have used matconvet-1.0beta-7 for a long time.  This seems have the same problem with issue#143. Can someone give a solution to the 'compute_21' problem? Thank you !  Here is the hardware:
Name: 'GeForce GTX 550 Ti'
                     Index: 1
         ComputeCapability: '2.1'
            SupportsDouble: 1
             DriverVersion: 5.5000
            ToolkitVersion: 5.5000
I have successfully compiled matconvet-1.0beta-12 in another machine with a Tesla M2075 which has  ComputeCapability: '2.0'. Are there any methods to solve the problem instead  of changing the gpu. Thank you very much! @vedaldi @lenck

**Comment by lenck** [comment]
Hey, this has been already fixed. Sorry that it took so long to get back to you.
