### ISSUE TITLE
Error in vl_test_nnlayers

### ISSUE THREAD

**Issue by gracejo** [vlfeat/matconvnet#157]
I'm not using GPU, just CPU and i've have such an error as well. currently using matlab 2014a. Hope i can get some help here.

vl_test_nnlayers
testing the CPU code
test number 1
testing vl_nnsoftamxloss multiple images convolutional
test number 2
testing vl_nnloss multiple images convolutional
testing vl_nnloss multiple images
testing vl_nnloss
test number 3
testing vl_nnsoftmax
test number 4
testing vl_nnconv with fully connected identity filters
Attempt to execute SCRIPT vl_nnconv as a function:
C:\Users\Josephine\Desktop\Matconvnet\matconvnet-1.0-beta11.tar\matconvnet-1.0-beta11\matconvnet-1.0-beta11\matlab\vl_nnconv.m

Error in vl_test_nnlayers (line 124)
y = vl_nnconv(x,[],b,'verbose') ;

**Comment by gaush123** [comment]
How did you solve this problem.
