### ISSUE TITLE
Needing help in non-linear gating

### ISSUE THREAD

**Issue by Mona77** [vlfeat/matconvnet#159]

**Comment by Mona77** [comment]
First, thank you so much for this great work. 
I was following the tutorial and sometimes I need clarification on the output results. I was wondering if there is a forum or google group similar to Pylearn2/Torch7/Caffe that I can ask my questions? 
Thanks.

**Comment by lenck** [comment]
Another stale issue, sorry. Yes, we have started a [google group](https://groups.google.com/forum/#!forum/matconvnet) some time ago.
