### ISSUE TITLE
vl_compilenn error

### ISSUE THREAD

**Issue by lgbwust** [vlfeat/matconvnet#160]
when I run vl_compilenn , the error is as follows:

 vl_compilenn
    Usage: 
        MEX [option1 ... optionN] sourcefile1 [... sourcefileN] 
            [objectfile1 ... objectfileN] [libraryfile1 ... libraryfileN] 
 
    Use the -help option for more information, or consult the MATLAB API Guide. 
 
 
  D:\APPLIC~1\MATLAB64\R2013A\BIN\MEX.PL: Error: Unrecognized switch: -cxx. 
 
Error using mex (line 206)
Unable to complete successfully.

Error in vl_compilenn>mex_compile (line 434)
mex(mopts{:}) ;

Error in vl_compilenn>(parfor body) (line 396)
    mex_compile(opts, srcs{i}, toobj(bld_dir,srcs{i}), flags.mexcc) ;

Error in vl_compilenn (line 387)
parfor i = 1:numel(horzcat(lib_src, mex_src))

Caused by:
    Error using mex (line 206)
    Unable to complete successfully.

Unrecognized switch: -cxx. ,what's the reason???

**Comment by MicHan87** [comment]
I am getting the same error , have you found any fix for this in the meantime ???

**Comment by slegall56** [comment]
In matlab 2014 it will work but not on 2013 I think

**Comment by naumanthunder22** [comment]
Just commenting the lines in vl_compilenn.m seems to work for compiling in Matlab R2013a. All the tests ran fine.

**Comment by lenck** [comment]
Duplicate to issue #133
