### ISSUE TITLE
An "interesting" GPU memory problem

### ISSUE THREAD

**Issue by HuiZeng** [vlfeat/matconvnet#163]
when I use the gpu accelaration to extract mutli scale CNN features, I meet an "interesting" "Out of memory" problem.
The codes are below:

im_ = gpuArray(im_);   % the size of im_ is 768x1024x3
net.layers = net.layers(1:37);   % in order to save memory cost
net = vl_simplenn_move(net, 'gpu');
for i = 1:10 % this is just for testing
     res = vl_simplenn(net, net);
end

There is no problem in the first loop, the "out of memory" problem happens in the second loop. It seems that the memory is still occupied after the fist loop? I tried to use the command "gpuDevice(1)" to reset the gpu but another problem occured.
Is there any simple method to solve this problem except buying a lager memory GPU.

**Comment by vedaldi** [comment]
Hi, you could try to use smaller batch sizes. The latest version of can_train allows splitting a batch in smaller chunks to allow working with less memory.

**Comment by HuiZeng** [comment]
Thanks for your replay!
I have found a simple way to solve this problem. I just clear the unused data in former layers which seems to consume the most of memory, only preserving the certen layers data I want to use.
