### ISSUE TITLE
Custom Vector Normalization - Back Propogation derivative 

### ISSUE THREAD

**Issue by pramodyn** [vlfeat/matconvnet#169]
I have a (15,15,3) matrix of Surface Normals (nx,ny,nz)  which needs to be normalized so that each surface normal is a Unit Vector. After which the error between the predicted and groundtruth normals is the dot-product. 

During the L2 normalization operation, for the back propagation step, the derivative of this operation has to be computed. For a vector, the normalization operation returns another vector. The derivative of Normalization is actually a Matrix. How will i process this as i would get a matrix for every (1,1,:) vector in the (15,15,3) output ?

**Comment by lenck** [comment]
Hi, sorry that it took so long to respond. This has been implemented in the [`vl_nnnormalizelp`](https://github.com/vlfeat/matconvnet/blob/master/matlab/vl_nnnormalizelp.m).
