### ISSUE TITLE
speed comparison - cpu vs gpu

### ISSUE THREAD

**Issue by shahrma** [vlfeat/matconvnet#170]
Hello. 
Thanks for this great matconvnet package. 

I wanted to examine the improvement that I can get from my GPU card ( GeForce GTX 780).
My setup is 
 Win7-64bit , 2x6 i7 core , 48GB ram.  
Matlab 2014a-64bit, 
GeForce GTX 780 + Toolkit\CUDA\v6.5 .
matconvnet-1.0-beta12

After compiling the package in both CPU and GPU modes, I tested the cnn_mnist (default parameters) in both modes, and got the following results: 
cpu ~1500 data/s . 
gpu ~2800 data/s.

Is this the improvement,  that should be expected ?

Thanks
shahar.

**Comment by vedaldi** [comment]
Hi, MNIST is a very small dataset and GPUs may not achieve such a big speedup compared to the CPU version. On larger models the speedup is typically > 10x. However, I suggest to compile with cuDNN. I think you should be able to achieve at least 5000 images/s on the GPU on MNIST.

**Comment by shahrma** [comment]
Thanks, 
I'll try the cuDNN.

**Comment by shahrma** [comment]
I tried the cudnn and it improved the gpu training speed from 2800 data/s to 8100 data/s.
So, it gives me factor x5 on the cpu .


Thanks a lot, 
Shahar
