### ISSUE TITLE
How to convert GoogLeNet to MatConvNet?

### ISSUE THREAD

**Issue by CharlesShang** [vlfeat/matconvnet#171]
GoogLeNet's caffe prototxt is written as
   
     layer{ type :"..." }  # a little different from vgg net

and has a Concat Layer. ( Does Matconvnet support concat?) 
How  to convert it into matfile in a smart way?

**Comment by vedaldi** [comment]
Hi, that architecture requires support for DAGs. This is definitely possible, but requires some extra work. We do have  working version of that architecture internally.

We are releasing DAG support hopefully in a week or two.

**Comment by CharlesShang** [comment]
So excited to hear that! :-)
