### ISSUE TITLE
Issue with GPU installation

### ISSUE THREAD

**Issue by aakashiisc** [vlfeat/matconvnet#172]
Hi, 
I am using MATLAB 2015a, CUDA toolkit 6.5 and visual studio 2013.

I am able to compile the CPU version. but here is the error I get while compiling GPU version.

Error using vl_compilenn>mex_link (line 452)
LINK : fatal error LNK1181: cannot open input file
'C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\im2row_gpu.obj'

Error in vl_compilenn>(parfor body) (line 404)
  mex_link(opts, objs, mex_dir, flags.link) ;

Error in vl_compilenn (line 401)
parfor i = 1:numel(mex_src)
 

*****************verbose mode of the above error********************

vl_compilenn('enableGpu', true,'verbose',1)
vl_compilenn: * CUDA configuration *
vl_compilenn:	CUDA: seraching for the CUDA Devkit (use the option 'CudaRoot' to override):
	| valid |   ver | NVCC path                                                              |
	|     1 | 60513 | C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin\nvcc       |
	|     0 |     0 | .                                                                      |
	|     0 |     0 | C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe   |
	|     0 |     0 | C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.0\bin\nvcc.exe   |
	|     1 | 60513 | C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin\nvcc.exe   |
	|     0 |     0 | C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin\nvcc.exe   |
	|     0 |     0 | /usr/local/cuda/bin/nvcc                                               |
vl_compilenn:	CUDA: choosing NVCC compiler 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\bin\nvcc' (version 60513)
vl_compilenn:	CUDA: using CUDA Devkit 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5'.
vl_compilenn:	CUDA: determining GPU compute capability (use the 'CudaArch' option to override)
vl_compilenn:	CUDA: NVCC architecture string: '-gencode=arch=compute_21,code=\"sm_21,compute_21\" '.
vl_compilenn:	CUDA: MEX config file: 'C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml'
vl_compilenn: * Compiler and linker configurations *
vl_compilenn: 	intermediate build products directory: C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build
vl_compilenn: 	MEX files: C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex/
vl_compilenn: 	MEX compiler options: -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx
vl_compilenn: 	MEX linker options: -lmwblas -lgdiplus -LC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\lib\x64 -lcudart -lcublas -lgpu -largeArrayDims
vl_compilenn: 	MEX compiler options (CUDA): -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
vl_compilenn: * Reading images *
vl_compilenn: 	vl_imreadjpeg enabled
vl_compilenn: 	image library: gdiplus
vl_compilenn: 	image library compile flags: 
vl_compilenn: 	image library link flags: -lgdiplus
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\copy_gpu.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\subsample_gpu.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\im2row_gpu.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\datacu.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\normalize_gpu.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\pooling_gpu.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\nnsubsample.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\nnfullyconnected.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\nnconv.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\datamex.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\data.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\vl_nnconvt.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\vl_nnpool.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\vl_nnnormalize.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\vl_imreadjpeg.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\vl_nnconv.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\imread_gdiplus.cpp -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\subsample_cpu.cpp -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\im2row_cpu.cpp -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\nnbias.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\nnnormalize.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\nnpooling.cu -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx -f C:\Program Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml NVCCFLAGS=-gencode=arch=compute_21,code=\"sm_21,compute_21\" $NVCC_FLAGS
Building with 'NVIDIA CUDA Compiler'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\tinythread.cpp -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\normalize_cpu.cpp -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\pooling_cpu.cpp -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
vl_compilenn: MEX CC: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\src\bits\impl\copy_cpu.cpp -c -DNDEBUG -DENABLE_GPU -D__SSSE3__ -largeArrayDims -cxx
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
vl_compilenn: MEX LINK: -outdir C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex -lmwblas -lgdiplus -LC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5\lib\x64 -lcudart -lcublas -lgpu -largeArrayDims C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\vl_nnconv.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\data.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\datamex.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\nnconv.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\nnfullyconnected.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\nnsubsample.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\nnpooling.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\nnnormalize.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\nnbias.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\im2row_cpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\subsample_cpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\copy_cpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\pooling_cpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\normalize_cpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\tinythread.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\im2row_gpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\subsample_gpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\copy_gpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\pooling_gpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\normalize_gpu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\datacu.obj C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\imread_gdiplus.obj
Building with 'Microsoft Visual C++ 2013 Professional (C)'.
Error using vl_compilenn>mex_link (line 452)
LINK : fatal error LNK1181: cannot open input file
'C:\Users\psychroomnew\Desktop\matconvnet-master\matconvnet-master\matlab\mex\.build\bits\impl\im2row_gpu.obj'

Error in vl_compilenn>(parfor body) (line 404)
  mex_link(opts, objs, mex_dir, flags.link) ;

Error in vl_compilenn (line 401)
parfor i = 1:numel(mex_src)
 

Thank you

**Comment by hidiryuzuguzel** [comment]
Hi,

I have exactly the same configuration and same problem. Did you find out something?

Thanks

**Comment by aakashiisc** [comment]
Hi,

I could not find any solution till now. I am able to work on CPU version.

**Comment by pengsun** [comment]
Hi, 

According to the error message you post, I guess you had not done it in the right folder. We need reside at the root folder (`matconvnet-master` in your case) and run the m file to compile.

**Comment by hidiryuzuguzel** [comment]
Hello,

In fact, I am in the root folder. I follow the instructions given in http://www.vlfeat.org/matconvnet/install/#compiling . Before compiling gpu version, we need to compile cpu version which compiles without any problem. When I compile the gpu version, I get the same output as aakashiisc.

BR

**Comment by pengsun** [comment]
It's weird... I thought it were folder/path problem because I saw the `matconvnet-master` shows up twice. 

Anyway, the error is due to the `obj` file cannot be found, why not trace in the compilation m file and see where the `obj` is? For convenience of debugging, you could change `parfor` to plain `for` temporarily.

**Comment by aakashiisc** [comment]
Hi pengsun. I could not find im2row_gpu.obj

However, when I tried fresh installation i.e. compiling GPU before CPU I get a different error.
****************************************
Error using mex
LINK : fatal error LNK1181: cannot open input file
'C:\Users\psychroomnew\Desktop\matconvnet-1.0-beta12\matlab\mex\.build\vl_nnconv.obj'



Error in vl_compilenn>mex_link (line 452)
mex(mopts{:}) ;

Error in vl_compilenn (line 404)
  mex_link(opts, objs, mex_dir, flags.link) ;
*****************************************************

But if I now compile CPU and then run GPU I get same error as in the first post. BTW does this have anything to do with visual C++ compilers.

**Comment by slegall56** [comment]
I add the same error but by replacing parfor by for in vl_compilenn, and calling vl_compilenn('enableGpu', opts.useGpu, 'cudaMethod', 'nvcc','verbose', '2') ; it worked

**Comment by aakashiisc** [comment]
Thanks. I read about this method in one of the earlier post. It will work if we have graphic card with compute capability of 3.0. My graphic card has compute capability of 2.1 and with cudaMethod I get a new error. " Unsupported gpu architecture 'compute_21' "

**Comment by slegall56** [comment]
Then I manually change the arch_code in vl_compilenn by 2.0 and it worked

**Comment by aakashiisc** [comment]
Hi, I am using vl_compilenn('enableGpu', true, 'cudaMethod', 'nvcc','verbose', '2')  ...

This is the function in vl_complinenn  
function cudaArch = get_cuda_arch(opts)
% --------------------------------------------------------------------
opts.verbose && fprintf('%s:\tCUDA: determining GPU compute capability (use the ''CudaArch'' option to override)\n', mfilename);
try
  gpu_device = gpuDevice();
  arch_code = strrep(gpu_device.ComputeCapability, '.', '');
  cudaArch = ...
      sprintf('-gencode=arch=compute_%s,code=\\\"sm_%s,compute_%s\\\" ', ...
              arch_code, arch_code, arch_code) ;
catch
  opts.verbose && fprintf(['%s:\tCUDA: cannot determine the capabilities of the installed GPU;' ...
                      'falling back to default\n'], mfilename);
  cudaArch = opts.defCudaArch;
end


I tried changing "arch_code = strrep(gpu_device.ComputeCapability, '.', '');" to "arch_code = 2.0" ...Is this where you changed the variable

**Comment by slegall56** [comment]
I did like this : 
cudaArch = ...
      sprintf('-gencode=arch=compute_%s,code=\\\"sm_%s,compute_%s\\\" ', ...
              '20', arch_code, '20') ;

**Comment by aakashiisc** [comment]
Thanks  a lot, It finally worked ..

**Comment by jreinertnash** [comment]
Using  vl_compilenn('enableGpu', true, 'cudaMethod', 'nvcc','verbose', '2'), 

...editing vl_complinenn subfunction get_cuda_arch with 

      cudaArch = sprintf('-gencode=arch=compute_%s,code=\\"sm_%s,compute_%s\\" ', ...
      '20', arch_code, '20') ;

...and making sure C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64 was in my system path made this GPU compilation happen smoothly.

Windows 7 x64, Lenovo P900 ThinkStation NVIDIA Quadro K4200 GPU, Matlab 2015a.

Thanks for the solutions in this thread, which resolved my problems.

**Comment by chulminy** [comment]
If the above solution is not working, use the following code

vl_compilenn('enableGpu', true,'verbose',1, 'cudaRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5','cudaMethod','nvcc')

Window 7 x64 Titan X and Telsa 40c

**Comment by eladar** [comment]
In addition, to make it compile for GPU, I had to change also the middle `arch_code` at the same line pointed by **jreinertnash**

BTW, i'm using Windows7 x64, Lenovo P900 with Nvidia Titan-X and Matlab2015a.

**Comment by angy50** [comment]
hi, I tried the same to resolve the same error whatever is discussed above. But I am still getting an error. Pls help me to resolve it.

What is done: compilling GPU support
vl_compilenn('enableGpu', true,'cudaMethod', 'nvcc','verbose', '2')

Platform used: windows 8.1, matlab2015a, cuda6.5, nvidia geforce graphics with computing capability 5.0

What error is occured:
Error using mex
msvcprt.lib(newaop_s.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1800' doesn't match value '1600' in
vl_nnconv.obj
   Creating library C:\Program Files\MATLAB\MATLAB Production Server\R2015a\bin\matconvnet-1.0-beta16\matlab\mex\vl_nnconv.lib and
   object C:\Program Files\MATLAB\MATLAB Production Server\R2015a\bin\matconvnet-1.0-beta16\matlab\mex\vl_nnconv.exp
C:\Program Files\MATLAB\MATLAB Production Server\R2015a\bin\matconvnet-1.0-beta16\matlab\mex\vl_nnconv.mexw64 : fatal error
LNK1319: 1 mismatches detected



Error in vl_compilenn>mex_link (line 456)
mex(mopts{:}) ;

Error in vl_compilenn (line 408)
  mex_link(opts, objs, mex_dir, flags.link) ;


Thanks

**Comment by yushuinanrong** [comment]
@angy50 
Hi,

I have exactly same problem as yours. Did you fix it ? 

Thanks

**Comment by angy50** [comment]
@yushuinanrong 
Hi,

I removed the matconvnet toolbox and reinstalled. for compilation i did direct compilation on gpu before cpu compilation. It worked. 

thanks.

**Comment by yushuinanrong** [comment]
@angy50 

Finally.... I make it.  Thanks a lot!

**Comment by GreenKing** [comment]
@angy50 
this might be the problem that you didn't use the same version of c compiler and cpp compiler
just pre-set again both the compilers:
```
mex -setup c

mex -setup cpp
```

**Comment by Abdelpakey** [comment]
Solution provided by @jreinertnash   worked for me using vl_compilenn('enableGpu', true, 'cudaMethod', 'nvcc','verbose', '2') and I didn't modify  cudaArch

**Comment by vickykhan89** [comment]
@jreinertnash your suggested code does not work for me, I still get the error.
Please help me.
