### ISSUE TITLE
Localization with VGG 

### ISSUE THREAD

**Issue by sunilrao43** [vlfeat/matconvnet#173]
@vedaldi   how can run localization task having vgg pretained model .. and bounding box 
 thanks in advance

**Comment by bazilas** [comment]
You cannot perform directly the localization task using the pre-trained models for classification. If you would like that your network outputs a bounding box, you should train the network to perform regression (e.g. L2-loss). You can always use a pre-trained model for the initialization of your network, if even it is not clear that is going to help your optimization.

cheers,
Vasilis
