### ISSUE TITLE
Is upsampling a 1x1xD patch with deconvolutional filter possible?

### ISSUE THREAD

**Issue by dbbert** [vlfeat/matconvnet#174]
I want to build an encoder-decoder architecture with a 1x1xD intermediate representation. It doesn't seem to be possible to upsample this patch with the vl_nnconvt layer. Is this an implementation issue or is it fundamentally impossible?

**Comment by vedaldi** [comment]
Dear Bert, thanks for noting this. Yes it is a bug, fixed in the devel branch just now.
