### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by amar2015** [vlfeat/matconvnet#176]
Hi 
I used MatConNet library six months ago and It was running perfectly. But I now need to run it again and unfouthinalty  I have the following error:

Undefined function 'gather' for input arguments of type 'single'.

Error in cnn_train>updateError (line 258)
predictions = gather(res(end-1).x) ;

Error in cnn_train (line 167)
    info.train = updateError(opts, info.train, net, res, batch_time) ;

Error in cnn_mnist (line 128)
[net, info] = cnn_train(net, imdb, @getBatch, ...

I had this error before and I managed my self to fix it but now I forgot how to do that.
would you please help me to fix  that error.

I really appreciate you help.

**Comment by amar2015** [comment]
I remember how to fix the problem. 
Thanks

**Comment by pilotbear** [comment]
how did you fix it? I have the same problem.

**Comment by amar2015** [comment]
You need to add the tool box for that function gather

**Comment by pilotbear** [comment]
do I need to purchase it? is that Parallel Computing Toolbox?

**Comment by amar2015** [comment]
Yes you do.
Yse it is.
