### ISSUE TITLE
-gencode=arch=compute_21 is not a valid key

### ISSUE THREAD

**Issue by aupilot** [vlfeat/matconvnet#180]
There is  (apparently) a bug in vl_compilenn.m  

cudaArch = ...
      sprintf('-gencode=arch=compute_%s,code=\\\"sm_%s,compute_%s\\\" ', ...
              arch_code, arch_code, arch_code) ;

in my case (Mac, GeForce GTX 560 Ti) the variable arch_code gets "21". However, "compute_21" is not a valid flag, it must be "compute_20"

This workaround works for me:
cudaArch = ...
      sprintf('-gencode=arch=compute_20,code=\\\"sm_21,compute_20\\\" ') ;

**Comment by chenqifeng22** [comment]
I have a similar problem. I need to change in the same way you suggest.

**Comment by lenck** [comment]
Duplicate to #143 . Fixed in the current version.

**Comment by vickykhan89** [comment]
@aupilot  how did you change it, could you tell me the specific file. looking forward to.
