### ISSUE TITLE
Unsupervised training

### ISSUE THREAD

**Issue by swamiviv** [vlfeat/matconvnet#182]
I am new to this library and I was wondering if there is a way to perform unsupervised training using matconvnet ?

**Comment by bazilas** [comment]
if you mean something an autoencoder, you could try the code from @umuguc:

https://github.com/umuguc/matconvnet/tree/autoencoder/examples/mnistAutoencoder

**Comment by swamiviv** [comment]
@bazilas I just came across that too. Thanks! and of course, thanks @umuguc!

**Comment by xcyan** [comment]
@bazilas I was wondering if the weights (encoder & decoder) are tiled or not?

**Comment by mingtop** [comment]
@bazilas  Do you know any CNN-autoencode implements ?  Such as conv-convt , I trained ,but can't get a result, thank you very much~~!

**Comment by bazilas** [comment]
hi @mingtop 

Check out this paper: http://people.idsia.ch/~ciresan/data/icann2011.pdf

It should be helpful.

**Comment by mingtop** [comment]
@bazilas   Thank you very much, now I got a reasonable model.  I will check the pdf your shared ~ Thank you again!
