### ISSUE TITLE
Index exceeds matrix dimensions when getBatch using cnn_train

### ISSUE THREAD

**Issue by HaoyangWang** [vlfeat/matconvnet#183]
I kept getting 'Index exceeds matrix dimensions' error in training. I have printed out the batch indicies, I only have 28741 images, but at some point the batch index gives 28742. I have also tried to run the code with only a small subset of data but it runs without any error. From what I understand, the batch indicies are generated in 'process_epoch' in cnn_train. Did the error happen because of a bug in cnn_train.m or I have done something wrong?

**Comment by yalaudah** [comment]
Hi @HaoyangWang, can you comment on how you fixed this issue?
Thanks
