### ISSUE TITLE
How to create fully connected layers in MatConvNet

### ISSUE THREAD

**Issue by hidiryuzuguzel** [vlfeat/matconvnet#185]
Hi everyone,
I have been trying to design & train the CNN architecture in the recent paper: "Color Constancy using CNNs"  (http://arxiv.org/abs/1504.04548). However, I could not make it train properly. I use the following network structure:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
f=1/100 ;
net.layers = {} ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(1,1,3,240, 'single'), zeros(1, 240, 'single')}}, ...
                           'stride', 1, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'pool', ...
                           'method', 'max', ...
                           'pool', [8 8], ...
                           'stride', 8, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'reshape') ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(1,1,3840,40, 'single'),zeros(1,40,'single')}}, ...
                           'stride', 1, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', relu) ;
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(1,1,40,2, 'single'),zeros(1,2,'single')}}, ...
                           'stride', 1, ...
                           'pad', 0) ;
net.layers{end+1} = struct('type', 'euclideanloss') ;   % Loss layer
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function Y = vl_nnreshape(X,dzdY)

if nargin <= 1 || isempty(dzdY)
  [r,c,NumOfFeatMap,NumOfImages] = size(X);
  Y = reshape(X,[1 1 r*c*NumOfFeatMap NumOfImages]);
else % backward
  Y = reshape(dzdY,size(X)) ;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Do you have any idea or suggestion for why it fails? 

Best Regards,
H.

**Comment by berkaykicanaoglu** [comment]
Hi,

I have been thinking on the same issue. Is that really necessary to flatten the blob before the fully-connected layer? If there was an implicit conversion from feature maps to a flat representation as in Caffe (when using INNER_PRODUCT block), that would be so handy. 

In the description of the function vl_nnconv(), there is this note:

%    VL_NNCONV() implements a special `fully-connected' mode: when the
%    support of the filters matches exactly the support of the input
%    image, the code uses an optimized path for faster computation.

However, I am not sure yet whether it is what we want here or not.

It would be great to hear about your suggestions.

Kind regards,
Berkay

**Comment by vedaldi** [comment]
In most cases there should be no need to flatten the data. A “flat” data is just a 1 x 1 x D x N array in MatConvNet. VL_NNCONV will implicitly switch to optimised versions of the code for this special case (as ultimately in memory the data is exactly in the same format as for a  D x N array anyway).

The big advantage is that there is no need to distinguish between FC and conv layers anymore. E.g. if you run AlexNet on a very large image you automatically get classification in a “sliding window” manner.

**Comment by hidiryuzuguzel** [comment]
Hi,

![cnn_arch](https://cloud.githubusercontent.com/assets/4250775/8477390/5de2c908-20d2-11e5-9bfb-07ad4b339b17.PNG)

I am trying to create the network shown upside (from Color Constancy Using CNNs paper). In order to do that, I tried the network which I have posted at the beginning. In the network architecture, there is an explicit reshape and I tried to mimic reshape in matconvnet. Is my approach correct? Or is there any other way to design this particular network without reshape in matconvnet?

Thanks,
H.

**Comment by vedaldi** [comment]
Hi, from the looks of it, although I cannot be 100% from just the picture, all you need is to replace the first FC layer with a convolutional layer that has filters with with and height equal to the with and height of the image coming from the layer prior to that (4 x 4 x number of input dim x 40). That will work as a FC layer implicitly and give you a 1 x 1 x 40 output directly.

**Comment by wajahat57** [comment]
Hi Vedaldi
I am new to ConvNets. As you  mentioned above, that if the FC layer is a large convolution, then for any input image of size larger than the training images, the network would apply a sliding window. My question is that how the stride of this slide can be controlled? Which parameter will decide that by how many pixels will the window slide between two consecutive positions on the large input image?
Best Regards
Wajahat

**Comment by khurram-amin** [comment]
I am trying to convert a cnn written in matconvnet into caffe version by simply reading matconvnet network in matlab and copy/pasting weights to a caffe network(which is also loaded in matlab). One problem that i am facing is that the network contains a fully connected layer and these are implemented in matconvnet as convolution-layer. Now when I try to copy weights from this layer (from matconvnet) to caffe's FC layer it gives a shape error.

**input data/diff size: [ 6 6 256 6144 ] vs target blob shape: [ 9216 6144 ]

This is expected. The thing I cannot figure out is how to properly reshape this matrix. Should I just reshape it as [6x6x256, 6144] matrix? Will this be correct or do i need to apply some dimension flips before doing this?**
