### ISSUE TITLE
visualizing features

### ISSUE THREAD

**Issue by aakashiisc** [vlfeat/matconvnet#186]
Hello all,

I am trying to visualize features from different layers (similar to that reported by Zeiler (2013)) using vl_nnconvt. But, I could not find the way to do it. Any help is appreciated. 

Thanks 
Aakash

**Comment by mingtop** [comment]
I also used convt ,but I can't get a resluts works.

**Comment by aakashiisc** [comment]
Are we doing it correctly. I mean Zeiler used deconvolution along with unpooling. Are there any tutorials for determining that.

**Comment by vedaldi** [comment]
Hi, unfortunately we do not have a tutorial for that. It would be an interesting project to automatically convert (simple) networks in deconvnets.

Note however that there is one missing piece: deconvnets require a max pooling block that can store the position of the pooled features. vl_nnpool does not do that. Given that, the unpooling operator can be easily constructed.

**Comment by aakashiisc** [comment]
Yeah, it would be great if we could have one. Will you be incorporating that one in future release ?

**Comment by vedaldi** [comment]
Hi, we are working on a few other features right now, but it is definitely under our radar.

**Comment by lenck** [comment]
Hi, you may want to look at the [deep-goggle](https://github.com/aravindhm/deep-goggle). It is using MatConvNet... In fact, for the Zeiler method is easily doable with simple [backprop step of standard convolution layer](http://arxiv.org/abs/1312.6034). Deconvolution would be useful for the generative, auto-encoder like models or the FCNs where you need to upsample your representation during the forward pass.

I hope it's ok that I will close this issue...
