### ISSUE TITLE
imreadjpeg is too slow sometimes

### ISSUE THREAD

**Issue by jiangwenchao** [vlfeat/matconvnet#187]
The matconvnet is really a good toolbox for exploration of deep learning. I installed the Matconvnet based on the installation tutorial and then I tested it in imagenet 2012. But I found the following problem. Please see the following two images.

![screenshot from 2015-07-05 12 44 15](https://cloud.githubusercontent.com/assets/9612073/8513536/22cc5992-2325-11e5-8818-353eefc464f3.png)

![screenshot from 2015-07-05 12 47 13](https://cloud.githubusercontent.com/assets/9612073/8513537/28892d42-2325-11e5-95f5-024b04f77892.png)

In the first image, the speed suddenly slowed down and would not recover. In the second image, the speed was too slow from the first iteration.

I am using the GPU computing. I ran the code line by line and found it was imreadjpeg() that caused the problem. To further figure out the problem, I ran imreadjpeg() independently, which means I wrote a short script and found the function is fast, but it is very slow in the imagenet example code.

As a summary, the function imreadjpeg is too slow sometimes and I do not know what is the reason. Does anyone meet the same problem or know the solutions? Thank you.

**Comment by vedaldi** [comment]
Hi, are you testing this on a windows machine?

**Comment by jiangwenchao** [comment]
Thank you for your reply. I tested them in ubuntu

**Comment by vedaldi** [comment]
Hi, ok. The code seems a bit slow in general for a K40c I believe (it should be more in the 240 images/s,  using cuDNN). Are you storing your images in a ramkdisk after preprocessing them?

Even so, there is  no reason why the code should slow down so much. Is that MATLAB 2014a or an earlier version?

To better pinpoint the error, you could use MATLAB's building profiler. Use the command

profile clear
profile on

before starting your code. Then break (Ctrl-C) after a while and use

profile viewer

It may confirm the issue, or reveal another one.

**Comment by gucan-long** [comment]
Hi @jiangwenchao, I am suffering the same problem of loading images being very slow. Have you fixed it?

**Comment by baiyancheng20** [comment]
@jiangwenchao @gclong  have your guy sloved this problem? I meet this problem too, since the beginning.

**Comment by gclong** [comment]
Hi guys, sorry for the missing updates. 

I think the problem might lie in the hardware part rather than MatconvNet.

**Comment by baiyancheng20** [comment]
@gclong Did you slove this problem and get the a fast training speed or change to Ubuntu?

**Comment by gclong** [comment]
I am now working with Windows-Caffe which also suffered the bottleneck of loading images until I add a new SSD.
