### ISSUE TITLE
using vl_nnconv for RGB images

### ISSUE THREAD

**Issue by noorjugni** [vlfeat/matconvnet#188]
I set the filters in conv layer to 8x8x3x64 (3 for rgb image).
the input to vl_nnconv is 80x80x3 (ie 80x80 rgb image)
but the output from vl_nnconv is 73x73x64 instead of 73x73x3x64.
what I am expecting is that it should convolve each channel separately. How can we do that?

**Comment by vedaldi** [comment]
Hi, filters in convents are 3D, i.e. they operate on all channels.

Having said that, what you want can be obtained by using the "filter groups" feature of vl_nnconv. Just create a filter bank of size 8x8x1x(64*3). Now the first 64 filters will be applied to the first channel, the second 64 to the second channel etc. See the vl_nnconv documentation to understand what is going on.
