### ISSUE TITLE
Compile error @ vl_imreadjpeg.cu on Windows

### ISSUE THREAD

**Issue by ByungtaeAhn** [vlfeat/matconvnet#190]
Hi,

I did compiling with sentences below

――――――――――――――――――――――――――――――――――――――
vl_compilenn('enableGpu', true, ...
               'cudaRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v6.5', ...
               'cudaMethod', 'nvcc', ...
               'enableCudnn', 'true', ...
               'cudnnRoot', 'local/') ;
￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣

but it outputs an error at vl_imreadjpeg.cu

――――――――――――――――――――――――――――――――――――――
... (until above, no problem)
vl_imreadjpeg.cu 
'Microsoft Visual C++ 2012 (C)' ...
error: vl_compilenn>mex_link (line 452)
LINK : fatal error LNK1104: cannot open file
'D:\DeepLearning\MatConvNet\matlab\mex\vl_nnconv.mexw64'
￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣￣

so, I cannot use vl_imreadjpeg.m

My environment is Windows7 x64, Matlab 2014a, Cuda toolkit 6.5, and the latest version of Matconvnet.
@lenck @vedaldi Any insight on what might seems to be the problem?

Thanks!
Byungtae

**Comment by svarjo** [comment]
I had a similar problem but solved it. In my case linker error was thrown since the mex file was "in use". So make sure you don't have the problematic mex in use or even loaded by matlab (eg restart matlab or unload by other means...).
