### ISSUE TITLE
vl_imreadjpeg - Memory leak issue?

### ISSUE THREAD

**Issue by nicjac** [vlfeat/matconvnet#191]
Hi all,

I am experiencing strange behaviours when using "vl_imreadjpeg" to read image files into memory (Windows 64-bit). The RAM usage keeps increasing during training, eventually reaching 100% and slowing down drastically. This might be related to issue #187 . The fact that the usual memory management tricks do not work ("clear all" for example does not change the memory usage reported in task manager) might suggest that it has something to do with the max/cu implementation of imreadjpeg?

This happens when simply calling the function with the image file names.

Any help would be greatly appreciated!

Thanks.

Nicolas

**Comment by vedaldi** [comment]
Hi, I tried the following script in Windows 7 MATLAB 2014a and I cannot observe any memory leak:

```matlab
a = which('peppers.png') ;
clear b ;
for j =1:100
  b{j} = a ;
end
for i = 1:1000
  c= vl_imreadjpeg(b) ;
  disp('.') ;
end
```
Could you please check whether this reproduces the problem for you or, if not, if you can modify it to reproduce the issue?

**Comment by okvol** [comment]
I have the same issue. Not sure if the memory leaks, but the speed is low --- ~30 data/s on a K20m GPU.

**Comment by nicjac** [comment]
So the code you provided does not reproduce the problem. But it did help me identify a possible cause of the problem: my images are 256x256x1, whereas the test image has three channels. Indeed, when I create fake 256x256x3 by repeating the grayscale channel, the problem goes away!

The issue is thus related to how vl_imreadjpeg deals with single channel images. 

Other things:
* vl_imreadjpeg will always read PNG files as three channels (seemingly by repeating the grayscale channel)
* As thus, the memory leak issue does not happen when reading PNG files, even those containing a single grayscale channel (but need to remember to handle the data properly down the line!)

I am not familiar enough with the code to spot the issue right away. I will give it a go, though it is likely that @vedaldi will figure it out much quicker!

**Comment by vedaldi** [comment]
Hi, I believe I just managed to fix the problem (in the devel branch). Reading BW images in Windows is likely to be somewhat suboptimal. Please let me know if the slow speed is still an issue.

**Comment by nicjac** [comment]
@vedaldi are you referring to the commit to the devel branch that was made 11 days ago?

**Comment by nicjac** [comment]
Thanks @vedaldi ! Unfortunately I am unable to use the vl_imreadjpeg.cu from the devel branch, I get the following error (compilation completes without issues): Invalid MEX-file 'E:\Coding\matconvnet\matlab\mex\vl_imreadjpeg.mexw64': The specified module could not be found.

**Comment by vedaldi** [comment]
Hi, I am referring to this patch:

https://github.com/vlfeat/matconvnet/commit/9f03f792ba3124e9bc5eb08a2e34c9d33f99ec99 <https://github.com/vlfeat/matconvnet/commit/9f03f792ba3124e9bc5eb08a2e34c9d33f99ec99>

The error is pretty odd. Did you try deleting the matlab/mex folder and recompile from scratch? There isn’t any recent change that should create such an error.

**Comment by nicjac** [comment]
@vedaldi it seems this error only occurs when compiling with cuDNN support. When disabling it, vl_imreadjpeg reads single channel images just fine, the memory leak is gone! I will do some tests regarding the reading speed now.

Thanks!
