### ISSUE TITLE
Error # The number of elements of BIASES is not the same as the number of filters.

### ISSUE THREAD

**Issue by KevinChen1618** [vlfeat/matconvnet#194]
Hi, guys. As I implemented my network, unfortunately encountering this problem as stated in the title. Wondering how could I fix this problem. Any help? thanks in advance. The following is part of my code.

net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(7,7,3,50, 'single'), ...
                           'biases', zeros(1, 50,'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;

**Comment by vedaldi** [comment]
Hi, this seems odd. I tried this code:
```matlab
run matlab/vl_setupnn
net.layers = {} ;
f = 1 ;
net.layers{end+1} = struct('type', 'conv', ...
                           'filters', f*randn(7,7,3,50, 'single'), ...
                           'biases', zeros(1, 50,'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;
vl_simplenn(net,randn(20,30,3,1,'single'));
```

and it executes without errors.

**Comment by lanyizheng** [comment]
i have the similar error when i run fcnTrain, as you see:
Error using vl_nnconv
The number of elements of BIASES is not the same as the number of
filters.

Error in dagnn.Conv/forward (line 11)
      outputs{1} = vl_nnconv(...

Error in dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;

Error in dagnn.DagNN/eval (line 88)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;

Error in cnn_train_dag>process_epoch (line 191)
      net.eval(inputs, opts.derOutputs) ;

Error in cnn_train_dag (line 88)
    stats.train(epoch) = process_epoch(net, state, opts, 'train') ;

Error in fcnTrain (line 97)
info = cnn_train_dag(net, imdb, getBatchWrapper(bopts), opts.train, ...
 
wondering what's wrong with my code?

**Comment by anguszxd** [comment]
Hi, everybody! I don;t have idea whether you have solved the problem or not. I face the same problem with lanyizheng, when I try to run fcnTrain, I get the Error message "The number of elements of BIASES is not the same as the number of filters." I check the net struct in line 72 
net = fcnInitializeModel('sourceModelPath', opts.sourceModelPath) ;
find the size of layer 'fc8f', layer 'fc8b' is not matching. So I change the size of layer 'fc8b'  (21x1 single), make it to be the same as the the number of 'fc8f'. And it works well now.
