### ISSUE TITLE
Classes of images in the tutorials

### ISSUE THREAD

**Issue by aakashiisc** [vlfeat/matconvnet#196]
Hello everyone, 

I just downloaded the data and code from the tutorial link. The images in the data folder does not look similar to imagenet data base. Also there are no classes assigned to them. Can anyone please let me know how can I use them.

Thank you

**Comment by lenck** [comment]
Hi, if you mean the classification tutorial it does not contain the whole imagenet (which would take few GB). To get the ILSVRC12 you need to go to their [website](http://image-net.org/challenges/LSVRC/2012/signup)...
