### ISSUE TITLE
Problem in version 1.0-beta13

### ISSUE THREAD

**Issue by hrahmani6060** [vlfeat/matconvnet#197]
Hi, everyone.  In the version 1.0-beta13, the bias is not learned as it always remain zero during training. Does anyone know how to solve it? This problem is not happened in version 1.0-beta12.
Thanks

**Comment by vedaldi** [comment]
Hi, yes, just noticed the problem. I will push a fix in the next couple minutes.

**Comment by hrahmani6060** [comment]
Thanks. I think you should take out the min from "min(numel(res(l).dzdw),1)" in  accumulate_gradients function.

**Comment by vedaldi** [comment]
Hi, indeed. Should be fixed now.
