### ISSUE TITLE
Beta13 Fails vl_test_nnlayers @ line 89

### ISSUE THREAD

**Issue by rob-rowe** [vlfeat/matconvnet#198]
It looks like the normalization factor n in vl_nnloss line 56 is no longer being used. If I put it back in to the calculation of Y (line 59) similar to Beta12 then vl_test_nnlayers fails on line 67. What is the right way to correct this problem?

**Comment by zhimingluo** [comment]
It's due to the precision of 'single' in Matlab, you can fix it by change the variable 'mass'  (line 41) to 'double'.

**Comment by rob-rowe** [comment]
That corrected the problem! Thank you.

**Comment by vedaldi** [comment]
Hi, yes, that’s correct. I adjusted the precision of a parameter of the test in the repository and now it passes.

**Comment by vedaldi** [comment]
Hi, sorry for this unwanted change. Do you think it is preferable to have the normalisation factor on by default?

I am preparing a rewrite of vl_nnloss to be clearer and more flexible and I would like to fix these details in the best possible way.

**Comment by rob-rowe** [comment]
Hi -- I generally find that normalization is beneficial if it allows the magnitude of the loss to remain roughly the same regardless of the size of the data. But I don't have a strong opinion on this. It's great that you're refining the code. Much appreciated!
