### ISSUE TITLE
Issue with test #2

### ISSUE THREAD

**Issue by arjunsubway** [vlfeat/matconvnet#199]
Hi,

I was able to successfully compile MatConvNet with Xcode 6.0.1 and Matlab R2015A (the CPU version). Some mex files appeared as a result.

vl_imreadjpeg.mexmaci64
vl_nnbnorm.mexmaci64
vl_nnconv.mexmaci64
vl_nnconvt.mexmaci64
vl_nnnormalize.mexmaci64
vl_nnpool.mexmaci64

After running vl_setupnn, I ran vl_test_nnlayers. However, I ran into an issue on Test 2. Specifically, the error reads:

Error using vl_testsim (line 34)
Assertion failed.

Error in vl_testder (line 23)
vl_testsim(dzdx, dzdx_, tau);

Error in vl_test_nnlayers (line 89)
      vl_testder(@(x) vl_nnloss(x,c), x, dzdy, dzdx, range * 1e-8) ;

Do you know why this error might have arisen? Is it possible to be fixed? Just to be safe, I downloaded and recompiled the code, but I got the same result as before. All others tests except 2 seem to work fine, but I'm concerned about this error.

**Comment by vedaldi** [comment]
Hi this should now be fixed as part of #198. It is an error of the test script requiring too much precision.

**Comment by arjunsubway** [comment]
Thanks for your help! It works now, much appreciated.
