### ISSUE TITLE
Compile gpu version error

### ISSUE THREAD

**Issue by jackiechensuper** [vlfeat/matconvnet#2]
Hi guys,
I am compiling the gpu version and got following error:

/home/gg/matlab2013/bin/mex: 2: matlab/src/config/mex_CUDA_maci64.xml: Syntax error: newline unexpected
make: *** [matlab/mex/vl_nnconv.mexa64] Error 2

Anyone can help?

**Comment by johnny5550822** [comment]
I got the same error too....what can I do?

**Comment by lenck** [comment]
As @shicai noted, usually it is caused by bad architecture settings. So you should edit your Makefile.
Or, in new release there is new option to compile using the vl_compilenn script, which detects the architecture automatically...
