### ISSUE TITLE
Error message of vl_nnconv() when using GPU mode with OS X 10.9

### ISSUE THREAD

**Issue by luzhi** [vlfeat/matconvnet#20]
I got an error message of function **vl_nnconv()** when I run the **vl_test_nnlayers.m** or **cnn_mnist** (or other examples) under the GPU mode on my iMac (*OS X 10.9 + CUDA 6.5 + GeForce GTX 775M + Matlab 2014a*). The error message is:

> Error using vl_nnconv An input is not a numeric array (or GPU support not compiled).

The same code is running correctly under the CPU mode. In addition, I also installed the Matconvnet toolbox on another machine with *Ubuntu 14.04 + CUDA 6.5 + GeForce GTX 770 + Matlab 2014a*, where the same code runs well under either GPU or CPU mode.

In detail, the problem happens at **line 153** of function vl_simplenn(), which calls:

> res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;

I checked all the input data of this function, where *res(i).x*, *l.filters* and *l.biases* are all **GpuArray** type.

Then, I tracked the code of Matconvnet. The problem happens at the function *void packed_data_init_with_array(PackedData ** *map, mxArray const** *array)* of the file **nnhelper.h**, which is called by **vl_nnconv.cu**. This function regards all the input data ( *res(i).x*, *l.filters* and *l.biases*) as non-GpuArray type, which is determined by **line 120** of file **nnhelper.h**:

> if (!mxIsNumeric(array)) {
>      mexErrMsgTxt("An input is not a numeric array (or GPU support not compiled).") ;
>   }

The question here is I have no idea why **mxIsNumeric()** does not regard the input array as GpuArray?

I tried to search the solution to this problem online, but got nothing. Could anyone help me on this? Is that caused by the compatibility between OS X and the CUDA? Thanks!

**Comment by lenck** [comment]
Hi, sorry for so late response... :P
This never happenned to me, but does other GPU related stuff works in Matlab? I.e. computation with gpu arrays or the Mathworks example [here](http://uk.mathworks.com/help/distcomp/run-mex-functions-containing-cuda-code.html?refresh=true)?
Then, the issue can be also that you are resuming training which was being run on CPU and then you want to resume for GPU - in the current implementation it is not checked and not autmoatically transferred... So, maybe when the error occurs, check whether all the first three arguments in `vl_nnconv` are gpuArrays...
Sorry, it's more a list of random ideas, but that would be what I would try to do...

**Comment by luzhi** [comment]
@lenck Thanks for your reply. I think I find the solution to the problem, which is the compatibility of CUDA version and the Matlab version. If I installed CUDA 5.5 with Matlab 2014a, it works.

**Comment by drohit92** [comment]
Hi,
I have CUDA 6.4, Ubuntu 14.04 with Matlab R2014b. I also get the same error. The same function vl_nnconv works in general and for the MNIST example.

Any suggestions?

**Comment by khouloud123** [comment]
Hi,
When i run the exercice 5 from VGG Convolutional Neural Networks Practical some erreus appears
such as :
Error using load
Can't read file C:\Users\MONDE
INFO\Desktop\CNNstart\practical-cnn-2015a\practical-cnn-2015a\data\imagenet-vgg-verydeep-16.mat.

why ?

THANKS
