### ISSUE TITLE
Issues with vl_nnpdist

### ISSUE THREAD

**Issue by DPO84** [vlfeat/matconvnet#203]
Hi, 

first, thanks for all the good work to Andrea and Karel as well as all the other people involved. 

Not entirely sure if I am on the right track here but something seems off with vl_nnpdist. The function header says

```matlab
function y = vl_nnpdist(x, x0, p, varargin)
```
but `vl_simplenn` calls it like this: 
```matlab
res(i+1) = vl_nnpdist(res(i).x, l.p, 'noRoot', l.noRoot, 'epsilon', l.epsilon) ;
```
so `l.p`is actually `x0`, which causes the entire function not to work.

In addition, with the newer beta versions it seems impossible to define loss functions such as a regular squared loss, i.e. instead of having the imdb.images.data (mnist example) in their original form put them in a binary vector per example and redefine getBatch as (simple, I know)
```matlab
function [im, labels] = getBatch(imdb, batch)
im = imdb.images.data(:,:,:,batch) ;
labels = imdb.images.labels(:,batch) ;
```
If you do that a define an appropriate loss then what I get 
```
DEROUTPUT dimensions are incompatible with X and FILTERS.
```
I debugged a little but couldn't quite find the cause.

Best
Pat

**Comment by lenck** [comment]
Hi, the issue with calling the `vl_nnpdist` has been fixed. The second issue - the labels has to be of exatly the same size as is the output of the network. So in your case you probably just need to use `permute` to fix it...
