### ISSUE TITLE
A bug ? Or the bnorm not support convt layer ?And my solution

### ISSUE THREAD

**Issue by mingtop** [vlfeat/matconvnet#205]
If the bnorm after conv layer it's ok 
But the bnorm after convt layer , I got this :
           Error using reshape
           To RESHAPE the number of elements must not change.

Here is my net_init: 
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(5,5,10,20, 'single'), zeros(1, 20, 'single')}}, ...
                           'stride', 1, ...
                           'pad', 0) ;                % 249*249*20*N
net.layers{end+1} = struct('type', 'relu');
net.layers{end+1} = struct('type', 'convt', ...
                           'weights', {{f*randn(5,5,20,10, 'single'),zeros(1,10,'single')}}, ...
                           'upsample', 1, ...
                           'crop', 0) ;                % 253*253*10*N    7
I debuged the  vl_bnorm.m  (If used the new repos, it's writes in vl_bnorm.cu, I can't debug get more info )   in Line 60:
g = reshape(g, [1 x_size(3) 1]) ;
b = reshape(b, [1 x_size(3) 1]) ;
---   g is  20*1  
----- x_size(3)  is 10 
So the error comes here ~~~~  

Here is my question and may a solution:
----- because the bnormal insert is in the file  net_init.m, so  I change the  the function:  
      function net = insertBnorm(net, l)
      I want add a judgement before    ndim = size(net.layers{l}.weights{1}, 4);
      if layer is conv 
              follow original way process
     if layer is convt 
            ndim = size(net.layers{l}.weights{1}, 3); 
----------------------------------------------------------------------------------------------------
The reson is this : 
             When we config the filter bank in net_init.m
the conv  w*h*depth*num
the convt w*h*filter_num*depth

If I'm not right, please  crrect it, thank you!

**Comment by vedaldi** [comment]
Hi, this seems appropriate. Note that the network construction files in the example directory are just that, examples. In that case they are not designed to work with convt as none of the example networks use it yet, hence the error.

Your fix seems legitimate.
