### ISSUE TITLE
A bug in vl_simplenn_move.m   report and fix

### ISSUE THREAD

**Issue by mingtop** [vlfeat/matconvnet#206]
When I used layer convt training on CPU, It's ok
But when I changed it to GPU on K20 ,  it's not work .
The error is   data and filter isn't both cpu data or gpu data.

Here is my fix: 
Just add  convt in vl_simplenn_move
for l=1:numel(net.layers)
  switch net.layers{l}.type

    case {'conv','convt', 'bnorm'}         % add convt here 

      for f = {'filters', 'biases', 'filtersMomentum', 'biasesMomentum'}
        f = char(f) ;
        if isfield(net.layers{l}, f)
          net.layers{l}.(f) = moveop(net.layers{l}.(f)) ;
        end

**Comment by vedaldi** [comment]
Thans, fixed in the devel branch and closed.
