### ISSUE TITLE
How to explain the results of sample code "cnn_cifar"

### ISSUE THREAD

**Issue by KevinChen1618** [vlfeat/matconvnet#207]
While testing the sample code: "cnn_cifar", I obtained the following results, which "info.train" and "info.val" are shown as follows. So my question is that why they are 20 results for objective, error, topFiveError, and speed; Because I have counted they are only 12 layers in this network. And the other question is that if I wanted to calculate the prediction accuracy for the network, then what shall I deal with it? (Is it comparing the "info.train" and "info.val"?)

info.train = 
objective: [1.5653 1.1478 0.9879 0.8890 0.8178 0.7637 0.7225 0.6781 0.6484 0.6167 0.5849 0.5562   
                  0.4191 0.3937 0.3842 0.3764 0.3698 0.3634 0.3455 0.3432]
error: [0.5659 0.4003 0.3420 0.3060 0.2801 0.2602 0.2486 0.2317 0.2224 0.2125 0.2019 0.1917  
          0.1414 0.1321 0.1295 0.1269 0.1241 0.1214 0.1147 0.1129]
topFiveError: [0.1101 0.0439 0.0321 0.0259 0.0218 0.0183 0.0162 0.0143 0.0134 0.0111 0.0102       
                       0.0086 0.0051 0.0045 0.0043 0.0040 0.0040 0.0041 0.0036 0.0035]
speed: [1x20 double]

info.val = 
objective: [1.2612 1.0767 0.9730 0.8920 0.8451 0.8260 0.8544 0.7845 0.7781 0.7761 0.7890 0.8011  
                  0.7157 0.7196 0.7213 0.7305 0.7309 0.7319 0.7284 0.7291]
error: [0.4463 0.3787 0.3404 0.3011 0.2863 0.2796 0.2830 0.2579 0.2624 0.2533 0.2530 0.2509 
           0.2276 0.2280 0.2247 0.2251 0.2250 0.2248 0.2254 0.2241]
topFiveError: [0.0542 0.0388 0.0302 0.0261 0.0259 0.0229 0.0230 0.0184 0.0189 0.0199 0.0218 
                       0.0196 0.0150 0.0150 0.0148 0.0156 0.0144 0.0146 0.0150 0.0150]
speed: [1x20 double]

**Comment by vedaldi** [comment]
Hi, you get a value for each epoch of training, so you can have an idea of the converge. In practice, use the last values in each array as this is the accuracy of the final model.
