### ISSUE TITLE
vl_imreadjpeg takes time during training process

### ISSUE THREAD

**Issue by slegall56** [vlfeat/matconvnet#211]
Hello, 
I'm training a cnn using Matconvnet. 
Everything works well. As i have got lot of images i'm loading them at each batch using vl_imreadjpeg like this : im = vl_imreadjpeg(images,'numThreads', opts.numThreads); 
Loading 200 images with vl_imreadjpeg takes me 3 seconds. I have 4000 batch per epoch and 60 epoch so just loading the image takes me 8 days without doing anything else. Is there a way to speed up the process of loading image ?

**Comment by nicjac** [comment]
This sounds quite slow in my experience. What are the images dimensions and their format? Also, what type of drive are you loading from? Mechanical HD or SSD?

Also, can you check your memory usage? We previously discussed a memory leak that happens in some cases when using matconvnet in Windows (issue #191).

**Comment by slegall56** [comment]
Thank you for the answer. 
I have a mechanical HD. It can explain it
Image dimension are 100x100, jpg in grayscale
About the issue #191, I have already add the line bitmap.UnlockBits(&data) ; to avoid the memory leak.
Loading image takes me more time than training the cnn, what a shame !!

**Comment by nicjac** [comment]
This is very strange. Loading 200 JPEGs with such small dimensions should not take that long, even using a regular HD. Have you tried replacing vl_imreadjpeg with MATLAB's imread in a loop, if you have access to the corresponding toolbox? If the performance improves then there is an issue with vl_imreadjpeg.

**Comment by slegall56** [comment]
Doing the loop takes the same time as using vl_imreadjpeg

**Comment by slegall56** [comment]
If i do a parfor loop with imread then i get 2 times faster than vl_imreadjpeg

**Comment by vedaldi** [comment]
Hi, is this on windows? 

Also, make sure to use multiple threads to load images.

**Comment by slegall56** [comment]
Hi Vevaldi
Yes it is on windows. 
I just test 1 thread and 4 thread with  vl_imreadjpeg and I got the same time always : 2.6 seconds for 200 images of size 100x100. So it seems that changing number of thread does not change anything on my computer

**Comment by nicjac** [comment]
How long does it take to read a single image?

**Comment by slegall56** [comment]
approximately 0.03s using imread. For vl_imreadjpeg, between 0.02 and 0.2, it is not very constant.

**Comment by slegall56** [comment]
On your computer does the speed change for vl_imreadjpeg when you set different number of threads ? For me it is exactly the same. Is there something to parameters on matlab or matconvnet compilation  to correct this?

**Comment by vedaldi** [comment]
I develop mostly on Mac and Linux and test occasionally on windows. However, it seems to be working ok -- although not super-fast as I am using a VM:
```matlab
run matlab/vl_setupnn
%vl_compilenn

a{1} = which('football.jpg') ;
a{2} = which('glass.png') ;
a{3} = which('AT3_1m4_09.tif') ;
clear b ;
for j =1:100
  b{j} = a{mod(j-1,3)+1} ;
end
for t = 1:4
  tic
  for i = 1:10
    c = vl_imreadjpeg(b,'numThreads',t) ;
  end
  fprintf('nthreads: %d: speed %f im/sec\n', t, (i*numel(b))/toc) ;
end
```
gives:
```
>> test_speed
nthreads: 1: speed 267.453121 im/sec
nthreads: 2: speed 476.231205 im/sec
nthreads: 3: speed 622.945176 im/sec
nthreads: 4: speed 712.679945 im/sec
```
As you can see, with increasing threads I get a more or less linear speedup.

Note also that the key feature of vl_imreadjpeg is to allow prefetching:
```matlab
run matlab/vl_setupnn
%vl_compilenn

a{1} = which('football.jpg') ;
a{2} = which('glass.png') ;
a{3} = which('AT3_1m4_09.tif') ;
clear b ;
for j =1:100
  b{j} = a{mod(j-1,3)+1} ;
end
for t = 1:4
  vl_imreadjpeg(b,'numThreads',t,'prefetch') ;
  pause(2) ;
  tic
  c = vl_imreadjpeg(b,'numThreads',t) ;
  fprintf('nthreads: %d: speed with prefetch %f im/sec\n', t, numel(b)/toc) ;
end
````
gives:
```
>> test_prefetch
nthreads: 1: speed with prefetch 11350.093638 im/sec
nthreads: 2: speed with prefetch 10871.101351 im/sec
nthreads: 3: speed with prefetch 11369.450287 im/sec
nthreads: 4: speed with prefetch 10970.325270 im/sec
```
The reason is that reading images is entirely masked by the `pause(2)` command (during which MATLAB could carry other operations. In this case using multiple threads does not show any effect as the speed is below 2 seconds in all cases.

**Comment by slegall56** [comment]
Hi, 
Your code works also perfectly on my computer with time improvement when the number of thread increase. So I'll check why I got weired slow time on my training. Thank you very much both of you. By the way very nice toolkit with clear tutorial

**Comment by gucan-long** [comment]
Hi @slegall56, I got the same problem of vl_imreadjpeg. When tested alone, it is OK, while it became extremely slow during cnn_train running. Have you figured out the problem?

**Comment by slegall56** [comment]
Well, during the test it was fast because i tested always on the same image, and the computer seems to  keep the memory in cache, but when tested on different image each time it take 2 sec for 100 images of size 100*100. Also there was a memory leak issue #191. 
So I change my HDD by a SDD and convert all my jpeg image in raw data then loading is faster because it doesn't need to unconpress the file
