### ISSUE TITLE
Does the matconvnet need vl_complienn every time?

### ISSUE THREAD

**Issue by mingtop** [vlfeat/matconvnet#217]
I don't know why , 
        Every time I restarted the computer, or I transfer the hole project from sever . I have to re-complie the matconvnet.  If I don't complie the matlab crash.
        Is it a bug?

**Comment by vedaldi** [comment]
Hi, restarting should not affect it unless something serious changes in your configuration.

Transferring from another machine may have unpredictable effects. Binary-level compatibility is probably pretty difficult to achieve with CUDA and MATLAB together.

**Comment by mingtop** [comment]
@vedaldi  Thank you very much !   Maybe the Tesla is double and my PC is single. 
I don't change any thing on my local PC. But after I complied the vl_comple it works well. 
It's not a big problem. 
Thank you again.

**Comment by zhimingluo** [comment]
when using the version 1.3,  I also meet this matlab carsh problem when  matlab is restart.
I find that before using the toolbox , just run the command gpuDevice first and then the problem fixed.

**Comment by vedaldi** [comment]
Hi, I experienced similar issues as well. I think this happens if the MEX files are linked against a different version of CUDA than the one MATLAB is using (which is common). Indeed initialising with gpuDevice seems to do the trick.

**Comment by mingtop** [comment]
@zhimingluo   Thank you very much!!
