### ISSUE TITLE
If a changed the relu to sigmoid, need I modify the conv/convt layer's gradient?

### ISSUE THREAD

**Issue by mingtop** [vlfeat/matconvnet#219]
As we know ,  the network trained by BP .If the activation function isn't relu(such as ) sigmoid , so we have to change the method of   dJ/dz  (J is the cost function).   z = w*a(or w*x)
If the last is relu,the J is  1/.2*(a-y).^2  
    we will have a    dJ/dz = (a-y)*1;
But the activation is sigmoid we will get:
        dJ/dz = (a-y).*a.*(1-a)    or   dJ/dz = (a-y).*sigmoid(z).*(1-sigmoid(z))   

Here is my question:
       If I added a activation of softplus   f(x) = log(1+exp(x)), or powder activetion   f(x) = x.^2;
May I get a right gradient back  in the convolution lay /  deconvolution layer   ?
--------------
ps:  Maybe I will not get a right gradient BP.   Need I modify the vl_convt.cu ?   I don't know how to write the cu programme.

**Comment by CASIAHYH** [comment]
The BP process is just an instance of the chain rule. So it's easy to insert any differentiable moduls into the MatConvNet. In your case, you just give the right equations of the Sigmoid in both forward and backward(BP) passes, the program will run correctly. You absolutely do not have to modify any other files. By the way, I have implemented Sigmoid and Tanh successfully.
