### ISSUE TITLE
Error with Cuda 6.0 and Matlab2014a in Ubuntu 12.04

### ISSUE THREAD

**Issue by capara** [vlfeat/matconvnet#220]
Hi,

**Comment by capara** [comment]
I have tried to compile the matconvnet with the option of enabling GPU in matlab 2014a.
My cuda6.0 lies in the path, '/usr/local/cuda'.
Although matlab succeeded in compiling the MatConvnet Package, when I started to run my code, it couldn't make it. 
The error message is as follow:
Invalid MEX-file '/home/sct/matconvnet/matlab/mex/vl_nnconv.mexa64': libcudart.so.6.0: cannot open
shared object file: No such file or directory

I have tried several methods, such as changing the bash.bashrc file, but it didn't work. Could anyone give me a hand?

**Comment by vedaldi** [comment]
Hi, this is surprising given that libcudart.so.6.0 should ship with MATLAB. Can you check whether it is contained in the MATLAB folder bin/glnxa64/lib64 (or similar?)?

**Comment by capara** [comment]
Thanks for your advice ^~^
I found that the linking error was due to the lack of required file,libcudart.so.6.0, in the folder /user/local/lib. I tried to add cudalib to the lib path by executing the cammand,
sudo ldconfig /usr/local/cuda/lib64
and it works now :)
