### ISSUE TITLE
Suggestions to add more complex network structure

### ISSUE THREAD

**Issue by jiangwenchao** [vlfeat/matconvnet#221]
Thank the authors for providing us so cool matlab based deep learning toolbox. It is actually of great help to someone like me who is familiar with matlab.

I have a suggestion. Now the examples you provide us are only with networks of chain, which means there is only one input and one output layer and there are no branches. Could the authors provide the function that can support the networks as long they are directed acyclic graph(DAG) (multiple inputs, multiple outputs, multiple branches)?  For example, one layer may have multiple bottom and multiple top.

I am not sure it is feasible for you. But if it is realized, I think people can do much more things with your toolbox. Although users can revise your toolbox all by themselves, it is time-consuming and there is no need for everybody to do so.

**Comment by AruniRC** [comment]
Hi, they seem to have a separate `devel-dag` branch where all the DAG related stuff is there. I have not seen in detail, but there is example code of using DAG in there (training or evaluating existing networks that are DAGs). However what may be missing is an example of how to define a DAG network from scratch. This would be really helpful.

**Comment by vedaldi** [comment]
Hi, note, we have a new branch called simply `dag` which is going to be part of the upcoming beta14. Please use that one instead of the old branch as they differ substantially.

**Comment by AruniRC** [comment]
awesome!

**Comment by jiangwenchao** [comment]
Hi, @vedaldi , How cool it is you have had the dag version！ When will the official version be released?

**Comment by vedaldi** [comment]
Hi, we are testing at the moment, and trying to add a few examples using the DAG. GoogLeNet works already and we should get a FCN-style segmentation network to work as well in the next few days. Training AlexNet and such seem to work fine too, and we are using it internally for a few experiments, so it may be ready to use.

Mostly, however, I want to avoid people the pain of a slightly changing interface and small bugs.

**Comment by jiangwenchao** [comment]
@vedaldi  Thank you for your reply. I found the branch of dev_dag and dag. They all have the dag implementation. What is the difference between them? I should use dag instead of dev_dag?

**Comment by vedaldi** [comment]
Hi, see below in this thread. Use `dag`; `dev_dag` is an early version that differs in a few substantial ways from the new

**Comment by jiangwenchao** [comment]
@vedaldi  Thank you. I will investigate the branch of dag. Hope to see the newest dag version fast.

**Comment by mingtop** [comment]
cool!

**Comment by jiangwenchao** [comment]
@vedaldi Hi, I am new to use the toolbox, thus I am not sure whether it is a bug. This bug is in the function vl_nnloss in the branch of "dag".

When caculating ci, I think n /numPixelsPerImage is wrong, because n and numpixelsPerImage are uint64, thus the result is integer and is based on rounding.

In fact, it needs to be uint64(floor(double(n) / double(numPixelsPerImage))). we need the result rounding toward negtive infinity.

Waiting for your reply. Thank you.

**Comment by jiangwenchao** [comment]
@vedaldi Hi, another possible bug is also in the brach of 'dag'.

In concat.m

function [derInputs, derParams] = backward(obj, inputs, params, derOutpus)
outputs{1} = vl_nnconcat(inputs, derOutputs{1}, 'inputSizes', obj.inputSizes) ;
end

This function is imcomplete, which should be

function [derInputs, derParams] = backward(obj, inputs, params, derOutputs)
        derInputs = vl_nnconcat(inputs, obj.dim, derOutputs{1}, 'inputSizes', obj.inputSizes) ;
        derParams={};
 end

waiting for your verification. Thank you very much.

**Comment by vedaldi** [comment]
Hi, yes, I think you are correct.

**Comment by vedaldi** [comment]
Hi, thanks, there was a bug indeed. Unfortunately MATLAB has an extremely weird implementation of integer classes with all sorts of unusual rounding. For now I switched to using double/floats  everywhere. It should work.

In the future we may just CUDAify the whole function.

**Comment by jiangwenchao** [comment]
@vedaldi  Thank you for youre reply. Hope to see the offical dag version soon.

**Comment by vedaldi** [comment]
Hi, I think that we will keep it brewing for one or two weeks to make sure we get most of the bugs, but you are more than welcome to check it out. We can definitely use the feedback!

**Comment by dbbert** [comment]
Is it possible to make the imagenet-googlenet-dag.mat file already available for download? It is referenced in examples/cnn_imagenet_googlenet.m

**Comment by dbbert** [comment]
I found a typo that causes a bug in matlab/+dagnn/ConvTranspose.m. On lines 34 and 35, it says obj.upsalmple instead of obj.upsample.

For future bugs, do you prefer that we submit a pull request or create a new issue instead of commenting here?

**Comment by vedaldi** [comment]
Hi, thanks!

Either methods would work. For such a small bug (one letter), I think a message here is sufficient.

**Comment by feichtenhofer** [comment]
Hi, a similar typo can be found in https://github.com/vlfeat/matconvnet/blob/dag/matlab/%2Bdagnn/Concat.m#L17
where derOutpus is passed instead of derOutputs.

**Comment by kjw0612** [comment]
Is 'imagenet-googlenet-dag.mat' available somewhere?

**Comment by vedaldi** [comment]
Hi, yes, there is a preview copy here:

http://www.vlfeat.org/sandbox-matconvnet/models/imagenet-googlenet-dag.mat <http://www.vlfeat.org/sandbox-matconvnet/models/>

Note that the structure might slightly change as we finalise the DAG implementation.

**Comment by kjw0612** [comment]
@vedaldi It works. Great! Thank you.
