### ISSUE TITLE
Recompile every time?

### ISSUE THREAD

**Issue by kobefeng123** [vlfeat/matconvnet#226]
Hi,

Thanks for the useful tool, but there is one thing bothering me. Every time I open Matlab, I need to recompile Matconvnet so that those functions can be used. I am wondering is there any way to not recompile Matconvnet when I open Matlab? I compile it using GPU and CUDNN.

Thanks.

**Comment by eric-phu** [comment]
There is no need to re-compile every time. Remove the line that does compilation and you will be fine.
