### ISSUE TITLE
What's the intuition behind the "final touches" of Xavier Improved initialization? 

### ISSUE THREAD

**Issue by peiyunh** [vlfeat/matconvnet#227]
I'm curious about the intuition behind 
``` net.layers{end}.weights{1} = net.layers{end}.weights{1} / 10 ; ```
in ```cnn_imagenet_init.m```

Can anyone shed some light? Thanks!

**Comment by vedaldi** [comment]
Hi, one of those hand-tuning that are needed to make things work. Xavier initialisation seem to be tuned to high for the softmax layer and causes it to diverge. I believe that some similar adjustments were noted also in the reference we used to implement this.

**Comment by eric-phu** [comment]
This makes sense to me, and yes I found they also talked about this in the paper. Thanks!
