### ISSUE TITLE
How to initialize the weights of a deconvolution layer to bilinear interpolation?

### ISSUE THREAD

**Issue by atique81** [vlfeat/matconvnet#231]
Hi all,
I would like to implement [1] using matconvnet. This paper uses a layer called "Deconvolution" which can be readily added by using a layer with type 'convt' in matconvnet. But, they have initialized their deconvolution layer weights to bilinear interpolation and I am not sure how to do that in matconvnet.

Any help/pointer would be highly appreciated.

1.  Fully Convolutional Networks for Semantic Segmentation, Jon Long*, Evan Shelhamer*, Trevor Darrell (CVPR 2015)

**Comment by eric-phu** [comment]
I actually have the same question.

**Comment by atique81** [comment]
Got it. Thanks a lot @eric-phu
