### ISSUE TITLE
# Error using  vl_nnsoftmaxloss: assertion failure

### ISSUE THREAD

**Issue by KevinChen1618** [vlfeat/matconvnet#232]
Hi, guys. As I implemented my CNN, I got this error:

Error using vl_nnsoftmaxloss (line 42)
Assertion failed.

Error in vl_simplenn (line 167)
      res(i+1).x = vl_nnsoftmaxloss(res(i).x, l.class) ;

Error in cnn_train (line 198)
    res = vl_simplenn(net, im, [], res, ...

Error in cnn_LIVEII (line 98)
[net,info] = cnn_train(net, imdb, @getBatch, ... % "net" with above-defined layers

Moreover, I thought the problem has something to do with this:

 % one label per spatial location
  sz_ = size(c) ;
  assert(isequal(sz_, [sz(1) sz(2) 1 sz(4)])) ;

So my question is that is this error associated with the number of classes? And how could I fix this problem? Thanks.

**Comment by KevinChen1618** [comment]
p.s. There is a weird observation:

As I printed out  the size of "l.classes" in matlab's command window, this values maintained at 100 as I intended to split into 100 classes.

size(l.classes) = 1 100

However, as the error message shows up, the size of "l.classes" is altered:

size(l.classes) = 1 1

**Comment by lenck** [comment]
Hi, in simplenn, the l.classes is being set in `cnn_train:306` as a ground truth label. See e.g. the `cnn_mnist` example how to create and pass the labels in the `getBatch` function... Also make sure that your classes are 1-indexed. Just how Matlab likes it :)

**Comment by samo313** [comment]
i have the same error with binary classification and my labels are 1 and 0.  the size of l.classes  is 10 for me. i would be appreciate for any help.
thanks
