### ISSUE TITLE
vl_simplenn does not process P-dist layer

### ISSUE THREAD

**Issue by aupilot** [vlfeat/matconvnet#233]
Hi Andrea,

I hope you are still reading this :)

There are 2 calls of vl_nnpdist() in the vl_simplenn.m, both use incorrect arguments:
res(i).dzdx = vl_nnpdist(res(i).x, l.p, res(i+1).dzdx, 'noRoot', l.noRoot, 'epsilon', l.epsilon)

Should not we pass the target values as well? Something like:
res(i).dzdx = vl_nnpdist(res(i).x, targets,  l.p, res(i+1).dzdx, 'noRoot', l.noRoot, 'epsilon', l.epsilon)

Cheers
Kir

**Comment by rosenfeldamir** [comment]
I've noticed this as well, this is solved by adding l.class after the first argument, i.e,
res(i).dzdx = vl_nnpdist(res(i).x, l.class, l.p,...)

**Comment by lenck** [comment]
Hi, this has been already fixed. Sorry for responding so late. Thanks for reporting!
