### ISSUE TITLE
Does matconvnet support processing a batch of varying sized images?

### ISSUE THREAD

**Issue by atique81** [vlfeat/matconvnet#234]
Hi all,
I was just wondering if it is possible to process a batch of images with varying dimensions in matconvnet?

Any response is highly appreciated.

Thanks

**Comment by vedaldi** [comment]
Hi, no this is currently not possible. It would be possible to implement SGD to do that, but it would not be very efficient.

**Comment by atique81** [comment]
Hi @vedaldi ,

thanks a lot for your response.
