### ISSUE TITLE
error in vl_simplenn_move.m

### ISSUE THREAD

**Issue by atique81** [vlfeat/matconvnet#240]
Hi @vedaldi ,

I guess the new deconvolution layer having the type 'convt' has not yet been added to the vl_simplenn_move.m file, as shown below.
.......................
line:20   for l=1:numel(net.layers)
line:21      switch net.layers{l}.type
line:22          case {'conv', 'bnorm'}
................
case should contain {'conv', 'bnorm', 'convt'}, since otherwise, the weights of the deconvolution layer will not be converted to gpuArray.

Please correct me if I am wrong.

**Comment by vedaldi** [comment]
Hi, yes, that’s correct. This is already in the dag branch, that should become master soonish.
