### ISSUE TITLE
error when Compiling the cuDNN support

### ISSUE THREAD

**Issue by fengyunxiaozi** [vlfeat/matconvnet#241]
hi guys, i was using MatConvNet with the environment "win8+vs2012+matlab 2015a+cuda 6.5+cudnn v2", there were some errors when compiling the cuDNN support. The following was used to compile, vl_compilenn('enableCudnn', true), but errors occurred. 

The error are:

Error using vl_compilenn>mex_compile (line 438)
vl_nnpool.cpp
h:\ufldl\matconvnet\matlab\src\vl_nnpool.cu(169) : error C2027: undefined type “vl::CudaHelper”
 h:\ufldl\matconvnet\matlab\src\bits\data.hpp(44) : refer to the definition of “vl::CudaHelper”

 any guys meet this problem?  Thanks!

**Comment by vedaldi** [comment]
Hi, can you try again with all the flags as specified in the website? E.g., explicitly enable CUDA support as well?

**Comment by fengyunxiaozi** [comment]
thanks, i have solved this problem according to your advice! cuda and cudnn support are compiled at the same time!
