### ISSUE TITLE
training one epoch getting slower and slower

### ISSUE THREAD

**Issue by arakotom** [vlfeat/matconvnet#243]
does any of few have experienced that the training time for one epoch is getting slower and slower, as the iterations go? if yes, do you know any reason for this behaviour?

thanks a lot

Alain

**Comment by jianqingzhu** [comment]
i also meet this problem. Do you solved it ?

**Comment by kevjshih** [comment]
I found the problem for me to be the OS caching too many file reads. Periodically running:
 `echo 1 > /proc/sys/vm/drop_caches`
as root fixed it. The slowdown tends to happen right when the buff/cache size equals the amount of free memory.
