### ISSUE TITLE
How to use the pre-trained  model  for fine-tuning on new data?

### ISSUE THREAD

**Issue by tzczsq** [vlfeat/matconvnet#244]
Hi, I want to  use the pre-trained ImageNet  model  for fine-tuning on new data.
For exampe, I have some image datasets are visually very similar to the ImageNet dataset, on which the imagenet-vgg-f was trained. The difference is that we are predicting 20 classes instead of a 1,000 on the ImageNet dataset. 
Please tell me how to fine-tune this  pre-trained imagenet-vgg-f model for our data with 20 classes?

**Comment by raphaeli** [comment]
Look at closed issue #218 on transfer learning

**Comment by mahfuj1093** [comment]
If you want to use pre-trained network, you have to change the class number 1000 to 20 (due to having 20 classes) in the FC layer.
