### ISSUE TITLE
GPU support for DagNN?

### ISSUE THREAD

**Issue by chuanli** [vlfeat/matconvnet#245]
Hi, 

It seems by default DagNN is set to work with cpu. I would like to load a pre-trained model and continuing with its 'net.device' being set to 'gpu'. I wonder if this is possible

So far I have been trying (without success) these two steps 
1) setting 'net.device' to 'gpu' (have to remove 'SetAccess = private' in DagNN.m)
2) applying 'gpuArray' on 'net.vars.value' and 'net.params.value'

And the error message I received from a forward propagation (net.eval) is 
Error using vl_nnconv
nnconv_forward_cudnn: : getWorkspace:  [out of memory error]

Many thanks.

**Comment by vedaldi** [comment]
Hi, The error is a bit unexpected, but to do what you want try using the DagNN.move method (it’s there for that purpose!)

**Comment by chuanli** [comment]
Hi, Andrea. Thanks a lot for mentioning the move function. 

The "out of memory error" seems to be related to graphics card memory. The situation gets better when I switched to a more powerful machine. However, it still happens when I forward prop a single image (300x600) with the very-deep-19 net. 

I noticed the dag branch had a recent update for cuda and cudnn -- I will try it and see if that helps my problem.

**Comment by ppdg123** [comment]
I got the same error when I  run with some particular images (the same size as others).

the error is : nnconv_forward_cudnn: : getWorkspace: [out of memory error] 

Then , I check the gpuDevice and I found a lot of free Memory there.

**Comment by vedaldi** [comment]
Hi, this *might* be possible as VGG is a very heavy model, although unlikely. How much memory does you graphic card have?

As a rule of thumb, we can train VGG VD with batches of about 20 images on cards with 6GB of ram.

**Comment by ppdg123** [comment]
The memory of my graphic card is 4G. 

Oh.. that's it. Thanks a lot!

**Comment by vedaldi** [comment]
Hi, you should still be able to use it with smaller batches. In particular a single image should really work.

Definitely try CuDNN as it uses less memory.
