### ISSUE TITLE
Error in running vl_test_nnlayers

### ISSUE THREAD

**Issue by zcn17** [vlfeat/matconvnet#246]
Hi, I encountered an error while I was running the script vl_test_nnlayers. It happened for test number 2: testing vl_nnloss multiple images convolutional.

Error using vl_testsim (line_34)
Assertion failed.

Error in vl_testder (line_23)
vl_testsim(dzdz, dzdx_, tau);

Error in vl_test_nnlayers (line_89)
vl_testder(@(x), vl_nnloss(x,c), x, dzdy, dzdx, range * 1e-8);

I ran other tests independently (1 and 3-14) and they are ok. I am running on Windows 64 bit and my matlab version is R2015a. 

Thanks,
Zhi

**Comment by netagy** [comment]
I have the same issue, with Windows 64 bit and matlab R2012b.

**Comment by Sleepingkoala** [comment]
Thanks for presenting this error. I`ve got the same issue on Ubuntu 12.04 64bit and matlab R2014a.

**Comment by zcn17** [comment]
ok found the fix here: https://github.com/vlfeat/matconvnet/commit/dc9b5755a0d9335f8814e9a878bc3ab0f8fe09ee

There is a commit in 16 Jul that deals with this.

**Comment by Sleepingkoala** [comment]
Thanks so much for the solution. It works.
