### ISSUE TITLE
Error using vl_nnconv An input is not a numeric array (or GPU support not compiled).

### ISSUE THREAD

**Issue by Mahesh-MR** [vlfeat/matconvnet#247]
Hi,
   After compilation of MATCONVNET with no errors. But while running the program (exercise 4 in Getting started) i am getting this error. 

>> learning rate changed (0.000000 --> 0.001000): resetting momentum
training: epoch 01: processing batch   1 of 152 ...Error using vl_nnconv
An input is not a numeric array (or GPU support not compiled).

Error in vl_simplenn (line 153)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;

Error in cnn_train (line 140)
    res = vl_simplenn(net, im, one, res, ...

Error in exercise4 (line 54)
[net,info] = cnn_train(net, imdb, @getBatch, trainOpts) ;
x------------------------------------------------------------------------x
Matlab2015a gpuDevice config is 
Name: 'Quadro K2200'
                     Index: 1
         ComputeCapability: '5.0'
            SupportsDouble: 1
             DriverVersion: 7
            ToolkitVersion: 6.5000
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 4.2946e+09
           AvailableMemory: 3.8061e+09
       MultiprocessorCount: 5
              ClockRateKHz: 1124000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1
---------------- (But actually i have toolkit version 7, but MATLAB is showing 6.5).----------

Please help.
Thank you in advance.

**Comment by orshij** [comment]
Try compiling using CudaMethod =  nvcc:
vl_compilenn('enableGpu', true, 'cudamethod','nvcc')

**Comment by Gzzgz** [comment]
May be the format of input data is unsuitable.

**Comment by nightrome** [comment]
For me simply recompiling with the same settings worked (enable GPU). Might be related to a system update or something...
