### ISSUE TITLE
Error while executing Transfer learning in matconvnet

### ISSUE THREAD

**Issue by aparnamhnty** [vlfeat/matconvnet#250]

**Comment by aparnamhnty** [comment]
![trans_error](https://cloud.githubusercontent.com/assets/9334941/9440676/96d802f6-4a8e-11e5-819e-8f323919eadc.PNG)

While trying to use a trained model to test my model i am getting this error. Please help.
My testx3 is of size (224,224,3)

**Comment by fengyunxiaozi** [comment]
@aparnamhnty  hi, according to the error information, the problem may be the filter size is larger than your image size. you had better check this! good luck!

**Comment by vedaldi** [comment]
Hi, a perhaps obvious trick is to use `dbstop if error` and then examine the size of the variable.s
