### ISSUE TITLE
vl_imreadjpeg seems to be only "semi" asynchronous on Linux

### ISSUE THREAD

**Issue by zoharby** [vlfeat/matconvnet#254]
I'm using matconvnet on an Ubuntu 14.04 machine. Currently data is on an HDD, which makes prefetching critical (will probably switch to SSD soon).

I've added prefetching with vl_imreadjpeg, but it doesn't seem to be working as expected. 

Here's a snippet out of my batch preparation function:
```
if nargout == 0
    % prefetch    
    files = prefetchFiles;
    tic
    vl_imreadjpeg(files,'Prefetch','NumThreads',6,'Verbose') ;
    fprintf('Prefetch: %.3f sec\n',toc)
    ims = [] ;
    labels = [];
    return ;
end

files = prefetchFiles;
tic
ims = vl_imreadjpeg(files,'NumThreads',6,'Verbose') ;
fprintf('Read: %.3f sec\n',toc)
```

The following debug prints illustrate the problem:
```
...
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  20 of 304 ... 0.71 s (140.3 images/s) PD 67.6% FA 32.6%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  21 of 304 ... 0.71 s (141.5 images/s) PD 67.4% FA 32.9%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  22 of 304 ... 0.71 s (141.6 images/s) PD 68.7% FA 32.4%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  23 of 304 ... 0.71 s (141.5 images/s) PD 68.4% FA 31.9%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  24 of 304 ... 0.71 s (141.5 images/s) PD 68.2% FA 31.6%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  25 of 304 ... 0.71 s (141.5 images/s) PD 66.2% FA 30.6%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  26 of 304 ... 0.71 s (141.7 images/s) PD 66.8% FA 30.9%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.002 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  27 of 304 ... 0.74 s (135.8 images/s) PD 67.3% FA 30.6%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  28 of 304 ... 0.71 s (140.3 images/s) PD 67.7% FA 30.6%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.001 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  29 of 304 ... 0.71 s (141.4 images/s) PD 67.4% FA 30.1%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.490 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  30 of 304 ... 1.21 s (82.8 images/s) PD 68.0% FA 30.6%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.390 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  31 of 304 ... 1.11 s (90.3 images/s) PD 68.4% FA 30.3%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.655 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  32 of 304 ... 1.38 s (72.6 images/s) PD 69.0% FA 30.4%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.533 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  33 of 304 ... 1.26 s (79.6 images/s) PD 69.1% FA 29.7%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.563 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  34 of 304 ... 1.29 s (77.7 images/s) PD 68.9% FA 29.1%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.579 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  35 of 304 ... 1.31 s (76.6 images/s) PD 69.5% FA 28.8%
vl_imreadjpeg: numThreads = 6, prefetch = 0, preallocate = 1
Read: 0.000 sec
vl_imreadjpeg: numThreads = 6, prefetch = 1, preallocate = 1
Prefetch: 0.445 sec
CNNfst_w_lr0.01_reg0.0001 | training: epoch 02: done batch  36 of 304 ... 1.18 s (84.9 images/s) PD 69.6% FA 28.3%
...
```

You can notice that the "Read" time is always 0, indicating prefetching works. But, the "Prefetch" time is not always 0. It starts at 0 at the first batches, since another run I made just before caused the OS to cache those files to memory.

But, starting from batch 31 (the point where I stopped the previous run) the "Prefetch" times suddenly jump to high values.

My conclusion here is that only the JPEG decoding part is asynchronous, but reading the files from disk seems to be synchronous even in prefetch mode. 

This was reproduced both on beta13 and on the devel branch.

**Comment by vedaldi** [comment]
Hi, thank you for your insightful comment.

This may very well be the case. The function needs to access the file synchronously when called in order to obtain the image size and pre-allocate the buffers to hold the image data.

The reason is that, as far as I know, it is not possible to allocate a MATLAB memory buffer (using mxMalloc) in a concurrent thread without crashing MATLAB. Therefore, these buffers are pre-allocated when vl_imreadjpeg is first called.

An alternative is to allocate “standard” memory asynchronously (using malloc) and then copy back to MATLAB memory upon the second invocation to the function. However, in my experiments the memory copy operation was expensive enough that this strategy was worse than peeking the files and pre-allocate some MATLAB memory directly.

It may be possible to solve the problem by passing to imreadjpeg the image size as part of the options (as in this case peeking the files would not be needed), but this would complicate the interface.

If anyone has any idea how this could be done better I would be very interested to know.

**Comment by zoharby** [comment]
I think in this case indeed passing the image size as an argument would be the easiest solution. You can raise an error on the 2nd call if an image was encountered with a size different than what was passed in the input.
Agree that this complicates the interface, but it would really speed things up in cases where pre-fetching is really critical (such as reading from an HDD).

**Comment by zoharby** [comment]
A simple solution which doesn't complicate the interface is to add a FixedDims flag. If set to true, code will check the dimensions of the 1st image and assume all the rest have the same dimensions. If it later encounters an image with different dimensions it can raise an error. Though this would require saving the dimensions in the task array so they can be validated when doing the actual read operation.

**Comment by lenck** [comment]
Hi, I think the fixed size together with many other improvements is implemented in the new `vl_imreadjpeg`...
