### ISSUE TITLE
initialize the weights from pre trained model 

### ISSUE THREAD

**Issue by amar2015** [vlfeat/matconvnet#261]
I am working on classification problem and I am using matconnet, but I want to initialize the weights for my CNN using pre trained model.
Can I do that?

**Comment by bazilas** [comment]
Yes, it's possible. You can download a pre-trained model (http://www.vlfeat.org/matconvnet/pretrained/) and use it for initialization. Have also a look at the issue #218. It's related to your question.

**Comment by amar2015** [comment]
Thanks a lot for your help. 
But my question is little bit different. I do not use the same architecture  for VGG network or AlexNet because they have large number of parameters and a such network is out of my machine's capabilities to do the retraining. I want to transfer some from their weights to my CNN which is smaller than these implementation(VGG network or AlexNet).       

I really appreciate your help and thanks in advanced.

**Comment by bazilas** [comment]
Hi Amar,

You have to load your trained network ('net' structure) and keep the layers that you need. Then, you can add more layers (net.layers{end+1} = struct(....) ) after the last layer of the pre-trained network. We describe something similar in the issue #218.

cheers,
Vasilis

**Comment by amar2015** [comment]
Hi Vasilis
Thanks a lot for your quick reply. 
I will try that.
Thanks again for your help.

**Comment by amar2015** [comment]
Hi  Vasilis
I tried that , I load the pre-trained model (imagenet-caffe-alex.mat) but when I call cnn_train function I have the following error:

Reference to non-existent field 'filters'.

Error in cnn_train (line 36)
  net.layers{i}.filtersMomentum = zeros(size(net.layers{i}.filters), ...

I really appreciated if you help me to implement the retraining part again.

Thanks

**Comment by bazilas** [comment]
Hi Amar,

The format of the network has been recently updated. It can be that the pre-trained models are in the old format with filters and bias.

After loading a model and convert it to the new format (e.g. with weights - cell array).
V

**Comment by bappadityamandal** [comment]
Hi bazilas,
After loading a model and convert it to the new format (e.g. with weights - cell array).
How to convert? can you please provide some examples?
