### ISSUE TITLE
vl_test_nnlayers for CPU code cannot work

### ISSUE THREAD

**Issue by heibaoradi** [vlfeat/matconvnet#262]
Hi, everyone. I'm using the latest version matconvnet-1.0-beta13. When I tested my compilation using vl_test_nnlayers, I got the following output.

-------------------------------------------------------------------------------------------------------
     vl_test_nnlayers
     testing the CPU code
     test number 1
     testing vl_nnsoftamxloss multiple images convolutional
     test number 2
     testing vl_nnloss multiple images convolutional
     Error using vl_testsim (line 35)
     Assertion failed.

     Error in vl_testder (line 23)
     vl_testsim(dzdx, dzdx_, tau);

     Error in vl_test_nnlayers (line 89)
     vl_testder(@(x) vl_nnloss(x,c), x, dzdy, dzdx, range * 1e-8) ;
-----------------------------------------------------------------------------------------------------------------   
   
 I went vl_test_nnlayers.m and modified line 30 "tests = 1:14 ; " as "tests = 3:14 ; ". It seems all other tests go well except test number 2, i.e., vl_nnloss. Did  anyone meet the same problem? Thanks.

**Comment by vedaldi** [comment]
Hi, these test scripts will be made obsolete soon, so perhaps the problem has been fixed in the current development branch (dag).

**Comment by heibaoradi** [comment]
Hi, Vedaldi. Thanks for your explanation. I downloaded the development branch (dag) code and compiled it. How can I confirm MatConvNet has been installed successfully as the tutorial said (http://www.vlfeat.org/matconvnet/install/). Thanks.
