### ISSUE TITLE
Error in Quick Start

### ISSUE THREAD

**Issue by hyojinie** [vlfeat/matconvnet#267]
When I execute "Using DAG models" code in the Quick Start page, I get following error which is caused by v value being NaN. 

Subscript indices must either be real positive
integers or logicals.

Error in dagnn.DagNN/eval (line 74)
[obj.vars(v).value] = deal(inputs{2:2:end}) ;

**Comment by vedaldi** [comment]
Thanks, indeed there was a typo in the example code. Could you try the version I just uploaded?

**Comment by hyojinie** [comment]
I see. It works now. :)
