### ISSUE TITLE
Is there any easy way to debug into the C++ source code, e.g. vl_nnconv.

### ISSUE THREAD

**Issue by HuiZeng** [vlfeat/matconvnet#268]
Hi,

I am trying to extract CNN feature from VGG-VD model in an only C/C++ environment. So I want to know is there any easy way to debug into the C++ source code, e.g. vl_nnconv, or  directly call the c++ source code (instead of the compiled mex file) in MatConvNet.

Thanks.

**Comment by vedaldi** [comment]
Hi, yes, this is possible for all the blocks that are coded as C/CUDA files (mainly conv, convt, pool, normalisation, and batch normalisation). Look in the matlab/src subdirectory. You can use the MEX files as a guide on how to call these functions, but is should be pretty easy: just wrap your CPU or GPU memory in vl::Tensor classes and then call the functions (e.g. vl::nnconv).

**Comment by HuiZeng** [comment]
Finally, I solve this problem in caffe which is easier for me.
Thank you anyway!
