### ISSUE TITLE
launch failure after back propagation of my self-defined convolution layer

### ISSUE THREAD

**Issue by peiyun** [vlfeat/matconvnet#27]
Does anybody have an experience of error when executing the: 
```
wait(gpuDevice)
```

When the code is waiting after finish the back propagation of my self-defined convolution layer, it gives the error: 
```
The CUDA Error: unspecified launch failure

Error in parallel.gpu.CUDADevice/wait

Error in back_prop: 
    wait(gpuDevice);
```

I feel this should not be a memory problem. Besides, when I define only one filter (HxWxDx1) in the self-defined convolution layer, it's fine. But when I define two, which makes the filters HxWxDx2. 

Does anyone have a clue about this? 

Thanks!

**Comment by xcyan** [comment]
Yes, I find the same problem when sharing GPU with other people (even if the memory is quite enough).

**Comment by vedaldi** [comment]
Is this problem still occurring?

In general, there is only limited control on what we can do when interacting with MATLAB's memory handler, but we can raise the issue to Mathworks if this is the problem.
