### ISSUE TITLE
vl_imreadjpeg seems not working

### ISSUE THREAD

**Issue by metalbubble** [vlfeat/matconvnet#270]
After I compiled the matconvnet, I wanted to benchmark the speed of vl_imreadjpeg, so I ran vl_bench_imreadjpeg.m, after some time, I only got the results as follows,
** test results preallcoate 0
	single tread: 0.0 pm 0.0
	4 threads: 0.0 pm 0.0
	issue prefetch: 0.0 pm 0.0
	retrieve prefetched: 0.0 pm 0.0

Also when I ran the script from some previous closed issue as follows

run matlab/vl_setupnn
%vl_compilenn

a{1} = which('football.jpg') ;
a{2} = which('glass.png') ;
a{3} = which('AT3_1m4_09.tif') ;
clear b ;
for j =1:100
  b{j} = a{mod(j-1,3)+1} ;
end
for t = 1:4
  vl_imreadjpeg(b,'numThreads',t,'prefetch') ;
  pause(2) ;
  tic
  c = vl_imreadjpeg(b,'numThreads',t) ;
  fprintf('nthreads: %d: speed with prefetch %f im/sec\n', t, numel(b)/toc) ;
end

It just poped a lot of warning like 
Warning: could not read image '/usr/local/MATLAB/R2015a/toolbox/images/imdata/glass.png' 
Warning: could not read image '/usr/local/MATLAB/R2015a/toolbox/images/imdata/AT3_1m4_09.tif' 
Warning: could not read image '/usr/local/MATLAB/R2015a/toolbox/images/imdata/glass.png' 
Warning: could not read image '/usr/local/MATLAB/R2015a/toolbox/images/imdata/AT3_1m4_09.tif' 
Then I got some unreasonable speed as
nthreads: 4: speed with prefetch 26888.948642 im/sec

Do you know what happened here? How to fix it? Also I tried the imagenet training example, it rougly takes 20s to load one batch with 256 images, does it make sense? Thanks a lot.

**Comment by prophecies** [comment]
I have the same Issue. I have double checked for any issues regarding filenames. I can read the exact same image by copy pasting from the warning using imread().

**Comment by tinalegre** [comment]
Hi guys, do you find a way to solve the issue? I'm having the same problems now after I upgraded the CUDA version. Could it be related to compatilitiy issues? I'm using CUDA 7.5 with Matlab 2014a. From the webpage, it seems to be that CUDA 7.5 has not been yet tested => http://www.vlfeat.org/matconvnet/install/#compiling

**Comment by tinalegre** [comment]
Do you guys solved the issue?  If yes, how? I'm not able to read PNG/TIF images using vl_imreadjpeg on linux. Since I want to avoid any compression, JPEG is a no-go. I did also a test on a mac and it worked without any problems.

**Comment by Firenze11** [comment]
I had the same issue. In windows png was working fine, but not on ubuntu

**Comment by vedaldi** [comment]
Hi, on Windows and Mac we use the OS to read images, which means that the function works with pretty much any format. On Linux we would need to explicitly link to each library for each format, so for now we use libjpeg.

**Comment by lenck** [comment]
Ok, I'm going to close this issue as there is not much point to adding support for reading png images in `vl_imreadjpeg`... :P Maybe it would be an useful feature addition, but at this point it is not needed.

**Comment by jmontoyaz** [comment]
@lenk I think reading `png` is important. In my case, I padded my images with some specific values that should be retained even after having stored them on disk. I therefore stored those images 
using  a lossless compression format such as `png`. Now, I would like to read a batch of those when training my CNN. From what I understood the benefit of using `vl_imreadjpeg` is its capacity of reading efficiently from disk, right? I was therefore hoping for a `vl_imreadpng` if you want to rename it that way. I think, a function that read images from disk shall not be limited to a specific format, but should be rather a more general one. I'm using BTW linux and hope this functionality will be available soon?

**Comment by lenck** [comment]
Hi, @jmontoyaz, sorry if it sounded like it wouldn't be useful. It's just that it is not our priority now, so we cannot promise when it would be supported. And yeah, then it can probably be renamed.
But, if you would like to contribute and play with the libpng library to read png files as well, it would be really appreciated :)

**Comment by vedaldi** [comment]
Hi, also, if anyone knows of a good general purpose image reading library in linux, we may link to that and be done with all formats at once.
