### ISSUE TITLE
Mailing list / forums?

### ISSUE THREAD

**Issue by nicjac** [vlfeat/matconvnet#271]
Dear all,

sorry for this post which is not an issue per-se; I was wondering whether the authors of matconvnet would consider setting up a mailing list or discussion forums? I feel like posts that are not actual issues but rather questions or comments (like this one) detract from the original function of this section of the repository. 

Nicolas

**Comment by vedaldi** [comment]
Hi, yes, this is an excellent idea. Any suggestion for a suitable platform?

**Comment by nicjac** [comment]
If you can host it, I had very good experience with Discourse (http://www.discourse.org/). Otherwise, Google Groups?

**Comment by jreinertnash** [comment]
Google Groups is where I go for Caffe and DIGITS discussion. I would welcome a MatConvNet group.

**Comment by arunmallya** [comment]
@vedaldi: Creating a chatroom on https://gitter.im might be useful.
Caffe (https://gitter.im/BVLC/caffe) and Torch (https://gitter.im/torch/torch7) use it.

**Comment by nicjac** [comment]
I agree, gitter.im seems like a pretty good first step to take!
