### ISSUE TITLE
cnn_train on CPU

### ISSUE THREAD

**Issue by NiclasWad** [vlfeat/matconvnet#276]
Hi,

I have donwloaded matconvnet and trying to run the example cnn_mnist I get error in cnn_train because numberlabs and labnumber are undefined in my matlab. I do not have parallel toolbox. The example runs if I define the variables numberlabs = 1; and labnumber = 1;. What do I need to do to be able to run the example on a single CPU?

/Niclas

**Comment by vedaldi** [comment]
Hi, ok, this is slightly unexpected. I believed that MATLAB would be able to do the right thing if the parallel toolbox is not installed, but obviously this does not seem to be the case.

Your solution seems to be correct. Does it work in practice?

**Comment by NiclasWad** [comment]
Hi Andrea,

Thanks for prompt reply. Yes, the example code cnn_mnist runs as it should. I consider my solution a temporary solution since I defined the variables in every place where numlabs and labnumber is used. It should be possible to do this once early in the code but I am not sure how to do it. How do you check if the toolbox is installed and how do you define a global variable that is seen by all other functions? 

/Niclas

**Comment by vedaldi** [comment]
Hi, one possibility would be to create two functions labindex and numblabs that take no arguments and return 1. If you make them visible in MATLAB’s path, that should take care of the problem.
