### ISSUE TITLE
DAG model build and train example

### ISSUE THREAD

**Issue by korkinof** [vlfeat/matconvnet#277]
Hi guys,
That's a really great toolbox, but I've noticed it lacks an example for building and training a DAG network, such as a googlenet for imagenet for instance. This would be really really helpful for me if you have it and can share it.
Best,
Dimitrios

**Comment by vedaldi** [comment]
Hi, the AlexNet example can switch to a “dag” mode, although it starts by converting a SimpleNN model first. Except for that, it should be a complete example.

**Comment by korkinof** [comment]
ok, I can work with that as well. Thanx

**Comment by korkinof** [comment]
Although technically, alexnet is not a complete example, as it is really a simplenn and some of the dagnn-specific functions are unused untested.
For instance dagnn.Concat's backward pass breaks for me and needs debugging.
So it would help if you provide googlenet or NIN equivalent example if you have one.

**Comment by korkinof** [comment]
Which backward pass looks in fact incorrectly implemented.

**Comment by korkinof** [comment]
I think it may have been just a small bug in line 18: Concat.m should look like this:
derInputs = vl_nnconcat(inputs, 3, derOutputs{1}, 'inputSizes', obj.inputSizes);
instead of this:
outputs{1} = vl_nnconcat(inputs, derOutputs{1}, 'inputSizes', obj.inputSizes);

Still struggling to make the whole thing work though.

**Comment by vedaldi** [comment]
Hi, this is correct, but this bug should have been fixed in beta15. Do you still have problems with this version?

**Comment by korkinof** [comment]
No, it's fine now! I managed to fix my problems and run a reinitialised version of the googlenet you provide. Many thanks!

**Comment by vedaldi** [comment]
Great, I'm glad that it is working for you now.
