### ISSUE TITLE
Bug in BatchNorm

### ISSUE THREAD

**Issue by korkinof** [vlfeat/matconvnet#280]
BatchNorm has a problem, as the wrapper is not implemented to take into consideration multipliers and biases.
I hacked it a bit by adding this:
params{1} = ones(size(inputs{1},3),1,class(inputs{1}));
params{2} = zeros(size(inputs{1},3),1,class(inputs{1}));
if(isfloat(inputs{1}))
     params{1} = single(params{1});
     params{2} = single(params{2});
end

**Comment by korkinof** [comment]
Also BN is doing the same thing in testing and training modes, which it shouldn't. During testing it should be normalising the input with a global mean and std accumulated during training.

**Comment by vedaldi** [comment]
Hi, thank you for pointing this out. It is indeed a limitation of the current wrapper. 

We are working on a solution to that, but we are not yet satisfied with the interface. The capability is now exposed in the underlying `vl_nnbnorm` function, but we are still deciding which would be the cleanest way of integrating this in the wrapper.

**Comment by lenck** [comment]
This was implemented in Beta-17...
