### ISSUE TITLE
Local weight sharing for convolution

### ISSUE THREAD

**Issue by jiangwenchao** [vlfeat/matconvnet#284]
Hi, I want to use the local or limited weight sharing for convolution, which means in different positions of the input image, the kernels are different. I am not sure whether this toolbox support it?

The local weight sharing method is proposed in "Applying convolutional neural networks concepts to hybrid nn-hmm model for speech recognition"

**Comment by vedaldi** [comment]
Hi, we do not have such a layer yet unfortunately.
