### ISSUE TITLE
Problem with the "vl_testnn'

### ISSUE THREAD

**Issue by DavidQiuChao** [vlfeat/matconvnet#287]
Hello, I have met this problem when I run the vl_testnn? Can you help me ?

![20151009194011](https://cloud.githubusercontent.com/assets/15049009/10392870/9c1967ca-6ebd-11e5-9c7c-60ce715c0fdd.jpg)

**Comment by vedaldi** [comment]
Hi, probably you have an “old” matlab version. The rest of the library should work on anything after Matlab 2014a (and with a bit of patience it should compile on some older version too)
