### ISSUE TITLE
Line 32 at Crop.m: inputSizes instead of inputSize

### ISSUE THREAD

**Issue by eric-phu** [vlfeat/matconvnet#288]
Hi,

This may already be fixed. Just post in case people wonder. Shouldn't it be 
```
derInputs{1} = vl_nncrop(inputs{1}, adjCrop, derOutputs{1}, obj.inputSizes{1}) ;
```
at line 32 of matlab/+dagnn/Crop.m
instead of 
```
derInputs{1} = vl_nncrop(inputs{1}, adjCrop, derOutputs{1}, obj.inputSize{1}) ;
```

Eric

**Comment by vedaldi** [comment]
Hi, yes, you are correct. Sorry for the blunder. I pushed a patch to the devel branch in github. Could you please let me know if it now works?

**Comment by eric-phu** [comment]
For my case, changing inputSize to inputSizes works for me. Thanks!
