### ISSUE TITLE
Problem while Running setup.m in practical-cnn-2015a

### ISSUE THREAD

**Issue by minhtannguyen** [vlfeat/matconvnet#289]
Hi all,

I encounter the following error while running the setup.m file in practical-cnn-2015a using CPU. Does anyone know how to fix this error? I am using MATLAB 2015b.

Thank you so much!!!

Error using mex
In file included from /Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/vl_nnconv.cpp:5:
In file included from /Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/vl_nnconv.cu:15:
/Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/bits/nnhelper.h:161:28: error:
non-constant-expression cannot be narrowed from type 'ptrdiff_t' (aka 'long') to 'mwSize' (aka 'unsigned long') in
initializer list [-Wc++11-narrowing]
  mwSize dimensions [4] = {geom.height, geom.width, geom.depth, geom.size} ;
                           ^~~~~~~~~~~
/Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/bits/nnhelper.h:161:28: note: override this message
by inserting an explicit cast
  mwSize dimensions [4] = {geom.height, geom.width, geom.depth, geom.size} ;
                           ^~~~~~~~~~~
                           static_cast<mwSize>( )
/Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/bits/nnhelper.h:161:41: error:
non-constant-expression cannot be narrowed from type 'ptrdiff_t' (aka 'long') to 'mwSize' (aka 'unsigned long') in
initializer list [-Wc++11-narrowing]
  mwSize dimensions [4] = {geom.height, geom.width, geom.depth, geom.size} ;
                                        ^~~~~~~~~~
/Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/bits/nnhelper.h:161:41: note: override this message
by inserting an explicit cast
  mwSize dimensions [4] = {geom.height, geom.width, geom.depth, geom.size} ;
                                        ^~~~~~~~~~
                                        static_cast<mwSize>( )
/Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/bits/nnhelper.h:161:53: error:
non-constant-expression cannot be narrowed from type 'ptrdiff_t' (aka 'long') to 'mwSize' (aka 'unsigned long') in
initializer list [-Wc++11-narrowing]
  mwSize dimensions [4] = {geom.height, geom.width, geom.depth, geom.size} ;
                                                    ^~~~~~~~~~
/Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/bits/nnhelper.h:161:53: note: override this message
by inserting an explicit cast
  mwSize dimensions [4] = {geom.height, geom.width, geom.depth, geom.size} ;
                                                    ^~~~~~~~~~
                                                    static_cast<mwSize>( )
/Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/bits/nnhelper.h:161:65: error:
non-constant-expression cannot be narrowed from type 'ptrdiff_t' (aka 'long') to 'mwSize' (aka 'unsigned long') in
initializer list [-Wc++11-narrowing]
  mwSize dimensions [4] = {geom.height, geom.width, geom.depth, geom.size} ;
                                                                ^~~~~~~~~
/Users/dsp/Documents/MATLAB/practical-cnn-2015a/matconvnet/matlab/src/bits/nnhelper.h:161:65: note: override this message
by inserting an explicit cast
  mwSize dimensions [4] = {geom.height, geom.width, geom.depth, geom.size} ;
                                                                ^~~~~~~~~
                                                                static_cast<mwSize>( )
4 errors generated.

Error in vl_compilenn>mex_link (line 323)
  mex(mopts{:}) ;

Error in vl_compilenn (line 274)
  mex_link(opts, mex_src, obj_files, mex_libs, mex_dir, mex_opts);

Error in setup (line 15)
  vl_compilenn('enableGpu', opts.useGpu, 'verbose', opts.verbose) ;

**Comment by vedaldi** [comment]
Hi, I cannot reproduce in MATLAB 2015b on Mac and Linux. Which version are you using?

At any rate, it seems a small quirk with c++11. See here for a solution: http://stackoverflow.com/questions/4434140/narrowing-conversions-in-c0x-is-it-just-me-or-does-this-sound-like-a-breakin

**Comment by aurotripathy** [comment]
I've run into the same issue (as minhtannguyen) with Mac OS X 10.11 (El Capitan) and Matlab R2015b

**Comment by aurotripathy** [comment]
OK., changing line 161 in nnhelper.h (to the line below) completed the build.

  mwSize dimensions [4] = {static_cast<unsigned long>(geom.height), static_cast<unsigned long>(geom.width), static_cast<unsigned long>(geom.depth), static_cast<unsigned long>(geom.size)} ;

**Comment by prasannavk** [comment]
Thanks that works for me.

**Comment by vedaldi** [comment]
Hi, you could also try replacing matconvnet with one of the later versions. I vaguely remember that this bug was fixed at some point. Of course, we should be updating the practicals with the new versions. Hopefully we will get down to it soon.

**Comment by Maswor** [comment]
Thank Aurotripathy. That also works for me!

**Comment by bkasap** [comment]
Thanks aurotripathy. changing line worked for me too on el capitan with matlab r2015a.

**Comment by pencilzhang** [comment]
Thank you Aurotripathy. Also works for me on Mac OS X 10.11 (El Capitan) and Matlab R2015a!

**Comment by DC1991** [comment]
Aurotripathy's solution also works for me, but need more information. I changed the line 161 into:
mwSize dimensions[4] = {static_cast<mwSize>(geom.height),static_cast<mwSize>(geom.width),static_cast<mwSize>(geom.depth),static_cast<mwSize>(geom.size)};

My platform are Mac OS X 10.12.3 and MATLAB R2016a.

**Comment by himahuja** [comment]
Just adding on to the soultion by @aurotripathy. The cast is performed as below,

`mwSize dimensions [4] = {static_cast<mwSize>(geom.height), static_cast<mwSize>(geom.width), static_cast<mwSize>(geom.depth), static_cast<mwSize>(geom.size)} ;`
