### ISSUE TITLE
I wonder that can matconvnet concatenates two parallel layer outputs?

### ISSUE THREAD

**Issue by dongb5** [vlfeat/matconvnet#29]
Can matconvnet concatenates two parallel layer outputs like CONCAT layer in CAFFE? Suppose I have two images as input and to be convoluted at same time followed by a full connect layer to compare these two images. Can I build such a network with matconvnet? Thanks.

**Comment by swamiviv** [comment]
Has there been any update regarding concatenation ?

**Comment by Tgaaly** [comment]
I would also like to know if there has been any update regarding this??

**Comment by vedaldi** [comment]
Hi, I think the answer is yes. The new DAG module supports GoogLeNet and you can now download a pre-trained implementation of it. Several new layers have been added as well, although I am sure we are still missing a few useful ones.

**Comment by jmontoyaz** [comment]
@vedaldi thanks for releasing the new DAG module! I was wondering whether you could provide a working example (such as cnn_imagenet.m) on how you defined the network architecture of GoogLeNet (as in cnn_imagenet_init.m) and how did you trained it (as in cnn_imagenet.m)? Would be great :+1:

**Comment by vedaldi** [comment]
Hi, for the moment we did not try to learn GoogLeNet from scratch, but imported the model from Caffe ModelZoo. You should be able to use MatConvNet for fine-tuning without too many problems. Training from scratch should also work, but I think that it may take a bit of effort to figure out all the parameters.

**Comment by yuanyc06** [comment]
@vedaldi Hi Andrea, I'm new for MatConvNet. As you mentioned above, it is possible to use the pre-trained GoogLenet model for fine-tuning. However, as far as I know, there's no support for the inception module in vl_simplenn. So I wonder how should the fine-tuning with the pre-trained GoogLenet be done? Thank you very much!

**Comment by vedaldi** [comment]
The `inception module` is just a small network pattern. See e.g. here for a discussion: 

https://github.com/BVLC/caffe/issues/1106

Hence, using DagNN, which can run such networks, you also get the ability to run inception.

**Comment by mosbate** [comment]
I want to implement  parallel  layer in my network.
In my network two images entered to two separated  parallel conv layers and after convolving  two results connect  to fully connected  network.
Both input images have size 200*200 and one conv layer size is 3*3*50 and another is 5*5*50.
I study image-net example but this is different structure.
How can I design this network?
Thanks

**Comment by lenck** [comment]
Hmm, I think this issue can be closed as the [concatenation layer](https://github.com/vlfeat/matconvnet/blob/master/matlab/%2Bdagnn/Concat.m) is in DagNN for ages...
