### ISSUE TITLE
Fully connected layer toy example

### ISSUE THREAD

**Issue by Monicar77** [vlfeat/matconvnet#293]
Hello,

I am quite new to matconvnet, in order to learn I would like to write some toy examples for each of the steps of a conv net architecture. I started with a two layer fully connected network example without success... I thought it would be the simplest case and I found it very hard :(

What I was trying to do is to define the following layer configuration 

X ~ 5 x 4

W1 ~ 4 x 10
b1 ~ 1 x 10

W2 ~ 10 x 3
b2 ~ 1 x 3

I wrote this code: 

net.layers = {} ;
% First layer
net.layers{end+1} = struct('type', 'conv', 'weights', {{W1, b1}}, 'learningRate', lr, 'stride', 1,          'pad', 0) ;
% Second layer
net.layers{end+1} = struct('type', 'conv', 'weights', {{W2, b2}}, 'learningRate', lr, 'stride', 1, 'pad', 0) ;
                     
% Forward pass: compute scores
cudnn = {'NoCuDNN'} ;
layer1_output = vl_nnconv( X, net.layers{1}.weights{1}, net.layers{1}.weights{2}, 'pad', 0, 'stride', 1, cudnn{:} );

layer2_output = vl_nnconv( layer1_output, net.layers{2}.weights{1}, net.layers{2}.weights{2}, 'pad', 0, 'stride', 1, cudnn{:} );

I am not quite sure if the code is going to provide the expected output, but I could not even make work any of the vl_nnconv lines... I suspect that the problem is that MatConvNet is expecting image like data, am I right? 

Help please!
Thank you!!

**Comment by arunmallya** [comment]
It is a bit tricky to begin with, always. I think this should help you out.

conv (or fc) in matconvnet expects 4-D inputs as it was aimed for making CNNs. The inputs look like this:  height x width x channels x batchsize. 
Thus your input can be considered as a 5 x 4 x 1 x B sized input, B = batchsize.

``` matlab

net.layers = {} ;

% conv layer that has filter height = 5, width = 4, channel = 1, output = 10
% as input is of same height and width, only one output of size 10 will be produced
% input: 5 x 4 x 1 x B -> output: 1 x 1 x 10 x B
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(5,4,1,10, 'single'), zeros(1, 10, 'single')}}, ...
                           'stride', 1, ...
                           'pad', 0) ;

% conv layer that has filter height = 1, width = 1, channel = 10, output = 3
% input: 1 x 1 x 10 x B -> output: 1 x 1 x 3 x B
net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(1,1,10,3, 'single'), zeros(1, 3, 'single')}}, ...
                           'stride', 1, ...
                           'pad', 0) ;

% attach some loss layer here, e.g. softmax cross-entropy loss
net.layers{end+1} = struct('type', 'softmaxloss') ;
```

Have a look at the examples/ folder, esp. on how to write a get_batch() function. 
Once that is done, pass your network and batch function handle to cnn_train()
Simplest point would be https://github.com/vlfeat/matconvnet/blob/master/examples/cnn_mnist.m
