### ISSUE TITLE
question about install the matconvnet

### ISSUE THREAD

**Issue by swangb** [vlfeat/matconvnet#295]
I was trying to install the Matconvnet 16. Now there's some problems.
I originally used cuda 6.5 and it works perfectly with all the previous version of matconvnet. But I made the mistake to upgrade the cuda to 7.5.... 
My first question is whether cuda 7.5 be well supported?
Since cuda 6.5 works well, so I re-installed the cuda 6.5 besides the cuda 7.5. 
But when I compile the maxconvnet using following configuration:

opts.enableGpu        = true;
opts.enableImreadJpeg = true;
opts.enableCudnn      = false;
opts.imageLibrary = [] ;
opts.imageLibraryCompileFlags = {} ;
opts.imageLibraryLinkFlags = [] ;
opts.verbose          = 0;
opts.debug            = false;
opts.cudaMethod       = 'mex' ;
opts.cudaRoot         = '/usr/local/cuda-6.5' ;
opts.cudaArch         = [] ;
opts.defCudaArch      = [...
  '-gencode=arch=compute_20,code=\"sm_20,compute_20\" '...
  '-gencode=arch=compute_30,code=\"sm_30,compute_30\"'];
opts.cudnnRoot        = 'local' ;

it report the following error:

Warning: Setting the 'MW_NVCC_PATH' environment variable to '/usr/local/cuda-6.5/bin/nvcc' 
> In vl_compilenn>activate_nvcc at 600
  In vl_compilenn at 253 
vl_compilenn:	CUDA: MEX config file: '~/matconvnet-1.0-beta16-copy/matlab/src/config/mex_CUDA_glnxa64.xml'
Building with 'nvcc'.
Error using mex
nvcc fatal   : Unsupported gpu architecture 'compute_52'

Error in vl_compilenn>mex_compile (line 438)
mex(mopts{:}) ;

Error in vl_compilenn (line 397)
      mex_compile(opts, srcs{i}, toobj(bld_dir,srcs{i}), flags.mexcu) ;

When I changed this setting:   opts.cudaRoot         = '/usr/local/cuda-7.5' ;

The compiling works well, except the following warning: 

/matconvnet-1.0-beta16-copy/matlab/src/bits/impl/tinythread.h(654): warning: extra ";" ignored
/matconvnet-1.0-beta16-copy/matlab/src/bits/impl/tinythread.h(654): warning: extra ";" ignored

But when I test using vl_testnn('gpu',true) nothing is working.

Then I change this setting back to: opts.cudaRoot         = '/usr/local/cuda-6.5' ;
When I do re-compiling, it skips the compiling error:
Building with 'nvcc'.
nvcc fatal   : Unsupported gpu architecture 'compute_52'

After re-compiling, vl_testnn('gpu',true) works well.

However, at this point,  if I run any demo in the example folder without using GPU, the matlab always crashed. (using GPU works fine)

How should I solve this problem? Reinstall the whole system?

By the way, I use GTX960 graphic card.

**Comment by swangb** [comment]
I just found that the problem also happened to my server, with cuda 6.5 and titan x graphic card.
It also report the following error

Building with 'nvcc'.
nvcc fatal   : Unsupported gpu architecture 'compute_52'

**Comment by cheer37** [comment]
I got the same error.
You solved the problem?

**Comment by swangb** [comment]
Which error do you have? 
I used to have two problems: 
1. my cuda version is too low: the latest matcovnet require at least cuda 7.0 for compute_52 gpu
2. when I installed cuda 7.5, I did not set up the environment correctly

**Comment by cheer37** [comment]
I have run vl_compilenn for cpu, but i couldn't run the vl_compilenn('enableGpu', true) for gpu.
It complains below.


Error using mex
C:\Program Files\MATLAB\MATLAB Production Server\R2015a\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.xml is not a valid XML file.

Error in vl_compilenn>mex_compile (line 438)
mex(mopts{:}) ;
Error in vl_compilenn (line 397)
      mex_compile(opts, srcs{i}, toobj(bld_dir,srcs{i}), flags.mexcu) ;
My environment is cuda7.0 sdk, comput capibility = 5.0, matlab r2015a and windows.
Would you help me?
Thanks in advance.
