### ISSUE TITLE
The speed comparation

### ISSUE THREAD

**Issue by llyydd007** [vlfeat/matconvnet#30]
Has any body madea speed comparation with cuda convnet2 or caffe？I try to reimplement a paper. Using matconvnet is really wonderful.However,I have run 5000 epoch using GPU GTX 550  and 1 million backpropagation which costs me roughly 2 days.The author of the paper have run 8*10^8 backpropagation  which costs roughly 3 days using GTX 770 GPU and cuda convnet2. Is there anything wrong? I think maybe there is something wrong with my code.But I still want to wonder the speed comparation with cuda convnet2 or caffe.Thanks!

**Comment by vedaldi** [comment]
Glad to hear that! We recently observed nice speedups using cuDNN in beta9.
