### ISSUE TITLE
About memory leakage in CPU mode

### ISSUE THREAD

**Issue by saturosfz** [vlfeat/matconvnet#308]
On Windows with the latest matconvnet, I use vl_nnconv to make a forward convolution with the filter of 6X6X96X64 on the image of 300X300X96 in CPU mode. The verbose info shows that the data occupy less than 100MB. But when I finish vl_nnconv, the WIndows task manager shows that Matlab occupies 3G+ memory. When I type clear all in Matlab, the memory usage goes down to 500Mb.

So I think there may be memory leakage in vl_nnconv. Anyone else who met the problem?

PS: I use Matlab 2014b

**Comment by vedaldi** [comment]
Hi,

convolutions use a large intermediate buffer than is recycled through calls. Try to use `clear mex` instead and see if the memory goes back to normal.

Note that MATLAB does tend to keep around his ow share of allocated memory (for internal buffers, DLLs) and sometimes it is difficult to understand why memory is not fully released when you expect that it should be.

There are no known leak in vl_nnconv. There could be one I suppose, but I would be somewhat surprised as we have been using it (along with the rest of the library) to train CNN models for weeks without issues.
