### ISSUE TITLE
Reset CNN.

### ISSUE THREAD

**Issue by as3nsi0** [vlfeat/matconvnet#316]
Hi everybody,
My question is CNN, for example pre-trained "imagenet-caffe-alex", as is possible initialize with weights zero that is to say as if it had never been trained?
I want have for example imagenet-caffe-alex and train from scratch.

Thanks for advance!

**Comment by bazilas** [comment]
You may want to check the function cnn_imagenet_init(). It's for AlexNet.

**Comment by as3nsi0** [comment]
Thanks a lot @bazilas!
