### ISSUE TITLE
vgg_face_matconvnet

### ISSUE THREAD

**Issue by cheer37** [vlfeat/matconvnet#326]
Anyone tried to execute the vgg_face_matconvnet provided by vgg?(http://www.robots.ox.ac.uk/~vgg/software/vgg_face/)

It causes following error.

Error using lib.face_detector.dpmCascadeDetector/resize
Method 'resize' is not defined for class 'lib.face_detector.dpmCascadeDetector' or is removed from MATLAB's search path.

Error in lib.face_detector.dpmCascadeDetector/featpyramid (line 42)
  scaled = obj.resize(im, 1/sc^(i-1));

Error in lib.face_detector.dpmCascadeDetector/detect (line 7)
pyra = obj.featpyramid(double(im));

Error in demo (line 13)
det = faceDet.detect(img);

Can you help me?
Thanks.

**Comment by vedaldi** [comment]
Hi, could you direct this request to Omkar Parkhi (the first author on the VGG Face paper)? I am not maintaining that package directly (jut a copy of the network) and he will be able to respond better to these questions — which are in this case independent of matconvnet.

From the looks of it, however, it seems that some mex files needs to be compiled.

**Comment by cheer37** [comment]
I emailed him twice by their saying if having a question, contact him.
But he has not been responding, So i posted here.
By the way, Mex files exists in the sub folder.

**Comment by cheer37** [comment]
@vedaldi 
I found the reason.
The project has only mex files for linux and mac, I am running on windows.
Do you have no the project on windows?
If you dont have, i think you are close relation with Omkar Parkhi and would you transfer my asking.
I need urgently.
Thanks in advance.

**Comment by MargaretaKusan** [comment]
I am experiencing the same problem. Any news?

**Comment by cheer37** [comment]
I used my own library based on windows for face detection.

**Comment by sidriaz** [comment]
I am struggling with the same problem as cheer37. I am running this code on windows 7. I have some questions:
Cheer37, what kind of library you have used for face detection? 
Also, does the demo program (given below) of Omkar Parkhi runs after you perform your own face detection? 

Demo Code:
img = imread('ak.jpg');
det = faceDet.detect(img);  %use any detector
crop = lib.face_proc.faceCrop.crop(img,det(1:4,1));
[score,class] = max((convNet.simpleNN(crop));

Moreover, if you used your own face detection, then what should be given as input in the "det" variable for further processing of the code? 
I can use ASM for face detection. But I am not sure what is the value of "det" variable (bounding box or points). 

Thanks,

**Comment by cheer37** [comment]
I used standard matlab face detection library.
Det is bounding box.

**Comment by sidriaz** [comment]
@cheer37 Thank you~
