### ISSUE TITLE
vl_nnnormalize interprets the alpha parameter differently from cuDNN's LRN

### ISSUE THREAD

**Issue by vadimkantorov** [vlfeat/matconvnet#339]
Hi,

I was converting some MatConvNet model to Torch and had to reset the alpha parameter in order to get identical results from CuDNN.

The code to generate the input and compute MCN's output:
```
run('matconvnet-1.0-beta16/matlab/vl_setupnn.m');

rng(1);
matlab_input = 41 + 90 * randn(74, 98, 96, 32, 'single');

net.layers{1} = struct('name', 'norm', 'type', 'normalize', 'param', [5.0000e+00  1.0000e+00  2.0000e-05  7.5000e-01]);
res = vl_simplenn(net, matlab_input);
matlab_param = net.layers{1}.param;
matlab_output = res(2).x;

save('test_norm.mat', 'matlab_input', 'matlab_output', 'matlab_param');
```

The equivalent Torch code:
```
require 'cudnn'
matio = require 'matio'

test_norm = matio.load('test_norm.mat')

N, KAPPA, ALPHA, BETA = test_norm.matlab_param[1][1], test_norm.matlab_param[1][2], test_norm.matlab_param[1][3], test_norm.matlab_param[1][4]

lrn = cudnn.SpatialCrossMapLRN(N, ALPHA, BETA, KAPPA)
cudnn_output = lrn:cuda():forward(test_norm.matlab_input:permute(4, 3, 2, 1):cuda()):float()

print((cudnn_output - test_norm.matlab_output:permute(4, 3, 2, 1)):abs():mean())
```

The output would be ```21.169983159962```. If instead of ALPHA I use the CuDNN's default 1e-4, mean absolute difference becomes more reasonable ```5.2012681605239e-06```.

I've checked the MCN's GPU and CPU code and both look reasonable, so I don't know where the discrepancy comes from. Any ideas?

I am using MatConvNet 1.0-beta16 and CuDNNv3.

**Comment by vadimkantorov** [comment]
Heck, just realized it's probably for the same reason there's a ```1/local_size``` factor in Caffe -> MCN conversion. https://github.com/vlfeat/matconvnet/blob/master/utils/import-caffe.py#L349

I agree, the different parameter interpretation may be Caffe's or CuDNN's problem, but maybe MCN could mention this difference in its documentation too.

**Comment by vedaldi** [comment]
Thanks! This is an excellent point. We will add a clearer message to the documentation.
