### ISSUE TITLE
vl_imreadjpeg.mexw64 The specified module could not be found

### ISSUE THREAD

**Issue by dynamicsong** [vlfeat/matconvnet#341]
I use matconvnet under win7, matlab R2014b, and visual studio 2010. I have installed the vlfeat according to http://www.vlfeat.org/install-matlab.html. Also I have compiled successfully using vl_compilenn and vl_compilenn('enableGpu', true, 'cudaRoot', '/Developer/NVIDIA/CUDA-6.0', 'cudaMethod', 'nvcc', 'enableCudnn', 'true', 'cudnnRoot', 'local/'). However, when I try to call vl_imreadjpeg function. It reports 
Invalid MEX-file '\matconvnet-fcn-master\matconvnet\matlab\mex\vl_imreadjpeg.mexw64': The
specified module could not be found.

Anyone has idea why it happens?

**Comment by talenz** [comment]
same problem

**Comment by talenz** [comment]
How to solve this problem?
