### ISSUE TITLE
beta-17 no way to specify GPU

### ISSUE THREAD

**Issue by AruniRC** [vlfeat/matconvnet#342]
The new beta-17 version does not provide an easy way to specify which GPUs (in case of multiple GPUs) to use, and the entire `opts.train` set of options is not easily modifiable any more.

**Comment by lenck** [comment]
Thanks for spotting this!

**Comment by AruniRC** [comment]
@lenck Hi, I meant to add that it's in the `cnn_imagenet.m` file, but I guess you already got that :)
