### ISSUE TITLE
beta17 vl_simplenn_tidy fails for custom layers

### ISSUE THREAD

**Issue by Relja** [vlfeat/matconvnet#347]
Hi,

The ``vl_simplenn_tidy` function doesn't take into account that some layers might be implemented as classes (`custom`) and fails with:

    No public property PP exists for class LL.
    
    Error in vl_simplenn_tidy (line 95)
      layer.(defaults{i}) = defaults{i+1} ;

Where PP and LL are the property and layer class, respectively.
The problem is that the `switch layer.type` doesn't do anything for `custom` so `defaults` stores the same value as it had for the previous layer, and then it tries to set the potentially non-existing properties in the custom layer using wrong defaults. I think this is easily fixable (seems to work for me) by adding this to the switch statement:

    otherwise:
        defaults= {};

**Comment by lenck** [comment]
Hi, does the fix work for you?

**Comment by Relja** [comment]
Yup, thanks!
