### ISSUE TITLE
About DAG CNN

### ISSUE THREAD

**Issue by xingchao92** [vlfeat/matconvnet#349]
Hello, 
       I am using matconvnet-1.0-beta17. 

       I found that if there is more than one input of the convolution layer, I need add a concatenation layer to concatenate the inputs. Is it right?
       What is more, If the two inputs of the loss layer all come from the network (one of them is not labels), do I need to implement a loss layer or function to calculate the dz/input1 and dz/input2 ? Is it similar to concatenation layer ?

      If the examples of several structures of DAG CNN can be provided, I will have a better understand of the MatConvNet. It would be nice to hear how MatConvNet has been used for several structures.

Thanks!

**Comment by lenck** [comment]
Hi, most of the operations which are available in `vl_simplenn` support only a single input. Therefore, if you want to perform convolution on multiple features, you have to use concatenation as the operations would have to do some wild guess what sort of operation they should do (concatenation along which dimension? Or should it have more outputs?).
Similarly, the second input of the loss layer is only for labels.

**Comment by xingchao92** [comment]
I see, Thank you very much!
