### ISSUE TITLE
error in compiling GPU version with windows 7 + matlab 2013b

### ISSUE THREAD

**Issue by dongb5** [vlfeat/matconvnet#35]
nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2010, 2012, and 2013 are supported .

But I have vs2010 and vs2012 in my computer.

**Comment by guanggz** [comment]
in Matlab 2014a, win 7 and compile as  

```
>> vl_compilenn('enableGpu', true)
```
 I got 
```
Undefined function 'patsh' for input arguments of type 'double'.

Error in vl_compilenn>which_nvcc (line 436)
    paths = patsh(strfind(paths, '.exe'));

Error in vl_compilenn>search_cuda_devkit (line 452)
paths = [paths, which_nvcc(opts)] ;

Error in vl_compilenn (line 195)
  if isempty(opts.cudaRoot), opts.cudaRoot = search_cuda_devkit(opts); end
```
Is there any missing function??

**Comment by dongb5** [comment]
I know that one! you should to modify 'patsh' to 'paths'. I thought that this is just a mistake.

**Comment by dongb5** [comment]
And......I have passed that visual studio thing. But I got a new problem...
 -----------------------------------------------------------------------------------------
vl_nnnormalize.cu 
    Usage: 
        MEX [option1 ... optionN] sourcefile1 [... sourcefileN] 
            [objectfile1 ... objectfileN] [libraryfile1 ... libraryfileN] 
 
    Use the -help option for more information, or consult the MATLAB API Guide. 
 
 
  D:\TOOLS\MATLAB\R2013A\BIN\MEX.PL: Error: Unrecognized switch: -cxx. 
 
Error using mex (line 206)
Unable to complete successfully.

Error in vl_compilenn>mex_link (line 323)
  mex(mopts{:}) ;

Error in vl_compilenn (line 287)
  mex_link(opts, ...

------------------------------------------------------------------------------
What happened?

**Comment by guanggz** [comment]
right, that was a typo. thanks!

**Comment by dongb5** [comment]
@vedaldi Why I got this error message? The processing was well-off when compiling vl_nnconv.cu, vl_nnpool.cu and so on. But stoped at 'vl_nnnormalization.cu'....

**Comment by dongb5** [comment]
ok...it seems that this was caused by MATLAB 2013. It worked with MATLAB 2014b.

**Comment by lenck** [comment]
Hey, thanks for pointing out these errors! 
It seems that the '-cxx' argument was introduces in mex in Matlab R2014, so that's why it ended up with error... Should be partially fixed in commit 9122b97b4bd53fc8e33ef2c0baa62addf3db5cb3 .

**Comment by guanggz** [comment]
@lenck sorry that I need to come back to this problem again. 
When I did ``` vl_compilenn()``` all compiles are ok, but if I do
``` vl_compilenn('enableGpu', true)``` I will have a fatal error saying

```
 nvcc : fatal error : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2008, 2010, and 2012 are supported 
Error using vl_compilenn>nvcc_compile (line 371)
Command "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc" -c
"C:\Users\Administrator\Documents\MATLAB\matconvnet-v1b8\matlab\src\bits\im2col_gpu.cu"
-gencode=arch=compute_35,code=\"sm_35,compute_35\"  -DENABLE_GPU -I"C:\Program Files\MATLAB\R2014a\extern\include" -I"C:\Program
Files\MATLAB\R2014a\toolbox\distcomp\gpu\extern\include" -O3 -DNDEBUG  -Xcompiler  /MD -o
"C:\Users\Administrator\Documents\MATLAB\matconvnet-v1b8\matlab\mex\.build\im2col_gpu.obj" failed.

Error in vl_compilenn (line 285)
      cuobj_files = nvcc_compile(opts, cu_src, bld_dir, nvcc_opts);  
```
But obviously I have vs installed. could you suggest some solutions? Thanks.

**Comment by dteney** [comment]
First make sure that your Visual Studio directory is in the path, e.g. by running:
setenv('PATH', [getenv('PATH') ';C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin']);

If it didn't help, passing a few extra flags to NVCC did the trick for me, indicating which version of Visual Studio to use, and where it is located (you may have to change the directories).

Around line 263 in vl_compilenn.n:
    nvcc_opts = nvcc_get_opts(opts) ;
    nvcc_opts = [ '--cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64" '  nvcc_opts ] ;
    opts.verbose && fprintf('%s:\tCUDA: NVCC compiler options: %s\n', ...
                            mfilename, nvcc_opts) ;

**Comment by guanggz** [comment]
@dteney did you get the fatal error right after you run ``` vl_compilenn('enableGpu', true) ``` or after several good compiles?

**Comment by dteney** [comment]
Oh it failed from the first time for me. I missed the fact that it worked a few times for you first.

**Comment by guanggz** [comment]
@dteney my bad. forgot to mention that in the beginning. thanks any way.

**Comment by lenck** [comment]
Hi @guanggz , from the error it really seems that it might have succeeded to compile the first few files (as they do not need nvcc) and failed for the .cu modules.
And the error you get seems exactly like nvcc does not have `cl.exe` from visual studio in the path so it's not able to find the necessary files. Have you tried some of the tips @dteney suggested? They seem quite reasonable (and in fact, I didn't know about those nvcc arguments, so thanks btw :)).

**Comment by YitzhakSp** [comment]
I try to install the beta10 version under win8 and Matlab2013. when I execute vl_compilenn I get the following error:

  C:\PROGRA~1\MATLAB\R2013A\BIN\MEX.PL: Error: 'C:\Dima\Projects_C\Libraries\matconvnet\matlab\src\bits\im2col.cpp' not found.

**Comment by YitzhakSp** [comment]
I Found the im2col.cpp file and added it to the directory. Wonder why it has not been there. Now I still have the  -cxx problem (see comment of dongb5 on Jan5). From [lenck, Jan10] it seems that the error was fixed in the current version the prog should compile on Matlab2013 or did I missunderstand the post?

**Comment by lenck** [comment]
Hi, are you sure you have the beta10? In the [latest vl_compilenn](https://github.com/vlfeat/matconvnet/blob/v1.0-beta10/matlab/vl_compilenn.m) there is no reference to the `im2col.cpp` from the old version of matconvnet...

**Comment by YitzhakSp** [comment]
Thanks for the advice, I'll take a closer look. In any case the critical issue right now for me is the -cxx thing. any ideas about that?

**Comment by lenck** [comment]
Hmm, that's probably because Matlab 2013 does not support this option. And if you just comment line 314 in [vl_compilenn.m](https://github.com/vlfeat/matconvnet/blob/master/matlab/vl_compilenn.m) does it work? :)
The thing is that putting there a condition for Matlab 2013 we do not have a way how to test it on Mac OS where the compilation fails without the `-cxx` option (as clang struggles to recognise if it should use c++ or c compiler). And conditioning it on the OS as well would be just another offering to the spaghetti monster :P

**Comment by suhaslohit** [comment]
Just commenting line 314 in [vl_compilenn.m](https://github.com/vlfeat/matconvnet/blob/master/matlab/vl_compilenn.m) seems to work for compiling in Matlab 2013b. All the tests ran fine.

**Comment by lenck** [comment]
Great :) Seems that it is really an issue of older Matlabs...
