### ISSUE TITLE
bug: undefined variables in cnn_imagenet()->getImageStats

### ISSUE THREAD

**Issue by AruniRC** [vlfeat/matconvnet#350]
When calculating the image stats in `cnn_imagenet` (ln 167), the variables `avg`, `rgbm1`, `rgbm2` need to be defined before the for-loop begins (line 175), like so:
`avg = {};
rgbm1 = {};
rgbm2 = {};
`

Otherwise in line 188, after the loop ends, Matlab throws an error saying these variables cannot be accessed when the code tries to calculate the expectations.

**Comment by lenck** [comment]
Thanks again for the bug report! :)
