### ISSUE TITLE
vl_imreadjpeg fails to load image

### ISSUE THREAD

**Issue by dynamicsong** [vlfeat/matconvnet#351]
I have complied the matconvnet successfully under Ubuntu 14.04 + Matlab R2014 b + CUDA 7.0. I have changed the gcc version to 4.7 which is supported by Matlab R2014b.

However whenever I call the function vl_imreadjpeg function, it reports:
warning: could not read image 'xxx/xxx/000.png'. 
The image url is correct. The problem still occurs without compiling with GPU. 

When compiling I notice there is a warning:
In file included from matconvnet/matlab/src/bits/implimread_libjpeg.cpp:14:0
/matconvnet/matlab/src/bits/impl/imread_helper.hpp:35:2. warning: "SSSE3 instruction set not enabled. Using slower image conversion routines." [-Wcpp]

I am not sure if this is the problem which causes the failure of reading images. Can anyone give some suggestions?

**Comment by lenck** [comment]
Hi, I'm afraid the `vl_imreadjpeg` supports only jpeg files, not png files...
However, even though this fails, it should successfully use the (slower) `imread` function, no?

**Comment by dynamicsong** [comment]
Indeed I have successfully load png images using vl_imreadjpeg under Windows 7 + Matlab R 2014b. I am sure whether it is the incompatible problem in Ubuntu. Anyway thanks for your advice, I have switched to imread and my program is able to begin training.

**Comment by lenck** [comment]
Ah, good point... I haven't realised this. It is probably because GDI+ used in windows version supports many formats, whereas in Linux we link against the libjpeg only. Probably on Max OS X there would be also more formats possible to read...
Do you know by any chance if there is some stable library in Linux with multiple format support?

**Comment by iTomxy** [comment]
I got this error, too. See my comment in [is vl_imreadjpeg() get the right image ? #286](https://github.com/vlfeat/matconvnet/issues/286#issuecomment-826480563).
