### ISSUE TITLE
VGG Convolutional Neural Networks Practical

### ISSUE THREAD

**Issue by zockder** [vlfeat/matconvnet#358]
I try to run the CNN example 1, but the system show me the VL_NNCONV() does not seem to be compiled. Trying to compile it now.  What should I do? Thanks.

**Comment by lenck** [comment]
Hi, sorry for this. In case of the VGG practicals, the MatConvNet was pre-compiled for the students.
However it is really simple to compile it, as is described in the 'Getting Started' section, by simply calling `run matlab/vl_compilenn`.

**Comment by PeterHuang2015** [comment]
Really appreciate this post as I have problem running vgg example too and run vl_compilenn to get the vl_nnconv~Is the .m file with the same exist for DIY the vl_nnconv?Thanks

**Comment by lenck** [comment]
@PeterHuang2015  I'm not sure if I understand you correctly, but the `vl_nnconv.m` is there only for the help string, the file which should be called is a compiled mex file in `matlab/mex`...

**Comment by PeterHuang2015** [comment]
@lenck Well, I was running vgg_face demo and had some problem as vl_nnconv hasn't been compiled yet cause the system took vl_nnconv.m for execution but it's empty except help string. I found this post and ran vl_compilenn and successfully execute the demo~ 
    I asked if vl_nnconv.m exists because it's left for implementing a vl_nnconv of my own version, a .m file without any script or function confused me. Now I know it's for help string, thanks lenck

**Comment by lenck** [comment]
Yeah, that's a bit weird thing how Matlab solves documentation for mex files :) Great that it works for you now!

**Comment by khouloud123** [comment]
Hi ,
in VGG i can't execute the exemple 4 

setup ;

%% Part 3.1: Prepare the data

% Load a database of blurred images to train from

load('data\text_imdb.mat') ;

the erreur appeach is
Error using load
Can't read file C:\Program Files\MATLAB\CODE2\practical-cnn-reg-2016a\data\text_imdb.mat

Why?

**Comment by PeterHuang2015** [comment]
## Did you try starting your matlab and read in the mat file manually? Or start your matlab with the administrator's authority?

## Or does the file exist in that folder?
