### ISSUE TITLE
Boundary check in vl_nnpool.cu

### ISSUE THREAD

**Issue by eric-phu** [vlfeat/matconvnet#36]
Hi there, 

Just want to make sure if it should be 
```
if (data.geom.height + (padTop+padBottom) < poolHeight || data.geom.width + (padLeft+padRight) < poolWidth) { 
    ... 
}
```

instead of 
```
if (data.geom.height < poolHeight || data.geom.width < poolWidth) { 
    ... 
}
```

at Line 243 in matconvnet/matlab/src/vl_nnpool.cu .

Let me know if I'm correct.

**Comment by vedaldi** [comment]
Hi, thanks for reporting. I believe the first version is correct as padding effectively extends the size of the image, and pooling is allowed to pool in the padded region.
