### ISSUE TITLE
Data augmentation for training imagenet model from scratch

### ISSUE THREAD

**Issue by okvol** [vlfeat/matconvnet#361]
I'm using version beta17.  I have several questions as follows. I'd really appreciate your suggestions/comments!
1. Is the default data augmentation setting in the demo code the best for training an ImageNet model from scratch? If not, how could I choose the best one?
2. Is scale augmentation implemented? Is it enabled by default?
3. Could someone provide a list of data augmentations one could do, sorted by empirical importance?

Since training a model takes a long time, it would be useful to know these beforehand instead of doing control experiments on them.

Thank you very much.

**Comment by bazilas** [comment]
Hi,

1. It includes crop and flip data augmentation.
2. Scale augmentation is not included.
3. Crop and flip are very useful and inexpensive augmentations. On top of it, one can include scale changes and small amount of noise in the ground-truth values (in regression problems).

V

**Comment by okvol** [comment]
Thanks!
