### ISSUE TITLE
cudnn compliation error!

### ISSUE THREAD

**Issue by zwx8981** [vlfeat/matconvnet#362]
I want to compile the cudnn-r4 on Windows 10, GTX 770M sli, Matlab2015b, matconvnet-1.0-beta17 and CUDA-7.5， the compilation of only CUDA-7.5 is just fine, but errors occur when I try to compile the cudnn also. Here is the error info. Anyone know how to fix it? Or I just need to use an older version of cuda or cudnn?

Thank you very much.

G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(217): error: "#" not expected here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(217): error: "#" not expected here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(466): error: "#" not expected here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(466): error: "#" not expected here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(466): error: "#" not expected here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(499): error: "#" not expected here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(499): error: "#" not expected here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(499): error: "#" not expected here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(217): error: expected an expression 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(217): error: expected an expression 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(217): error: argument of type "float *" is incompatible with parameter of type "cudnnTensorDescriptor_t" 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(217): error: too many arguments in function call 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(215): warning: variable "alpha" was declared but never referenced 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::forward(vl::Context &, vl::Tensor, double, vl::Tensor, double, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(466): error: expected an expression 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(463): warning: variable "alpha" was declared but never referenced 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(464): warning: variable "beta" was declared but never referenced 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(499): error: expected an expression 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(495): warning: variable "alpha" was declared but never referenced 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(496): warning: variable "beta" was declared but never referenced 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
G:/Matlab2015b/matconvnet-1.0-beta17/matlab/src/bits/impl/nnconv_cudnn.cu(446): warning: variable "filtersGrpOffset" was declared but never referenced 
          detected during instantiation of "vl::Error vl::impl::nnconv_cudnn<type>::backward(vl::Context &, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, vl::Tensor, int, int, int, int, int, int) [with type=float]"  
(538): here 
 
14 errors detected in the compilation of "C:/Users/Weixia/AppData/Local/Temp/tmpxft_00002c94_00000000-8_nnconv_cudnn.cpp1.ii". 
nnconv_cudnn.cu 
Error using vl_compilenn>nvcc_compile (line 468)
Command "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc" -c "G:\Matlab2015b\matconvnet-1.0-beta17\matlab\src\bits\impl\nnconv_cudnn.cu"
-DNDEBUG -DENABLE_GPU -DENABLE_CUDNN -IG:\Matlab2015b\matconvnet-1.0-beta17\examples\local\cudnn-rc4\include -D__SSSE3__ -I"G:\Matlab2015b\extern\include"
-I"G:\Matlab2015b\toolbox\distcomp\gpu\extern\include" -Xcompiler /MD -gencode=arch=compute_30,code=\"sm_30,compute_30\"  -o
"G:\Matlab2015b\matconvnet-1.0-beta17\matlab\mex\.build\bits\impl\nnconv_cudnn.obj" failed.

Error in vl_compilenn (line 414)
      nvcc_compile(opts, srcs{i}, toobj(bld_dir,srcs{i}), flags.nvcc) ;

**Comment by zwx8981** [comment]
I changed CUDA7.5 to CUDA7.0, but it doesn't work.

**Comment by amirjamaludin** [comment]
I think this might be a Windows-specific bug which can be solved by expanding some of the #if statements in nnconv_cudnn.cu & nnbias_cuddn.cu as discussed here: https://groups.google.com/forum/#!topic/matconvnet/xnH57LNF6ag.

I've attached a .zip file which contains the aforementioned files with expanded #if statements that should work for windows.
[conv_bias_cudnn_windows.zip](https://github.com/vlfeat/matconvnet/files/73628/conv_bias_cudnn_windows.zip)

**Comment by zwx8981** [comment]
@amirjamaludin Thank you very much! I'll try it and close this issue if that works.

**Comment by lenck** [comment]
Hi, thanks for reporting this and thanks @amirjamaludin for the proposed solution!
I've created a new branch `win-cudnn-fix` with those fixes and few others. Do you think you can check whether this version works? Unfortunately I do not have access to a windows machine with a GPU.
Thanks!

**Comment by amirjamaludin** [comment]
@lenck, you might need to add #include <algorithm> in nnconv_cudnn.cu. The new branch works only if I include said header. @zwx8981 I noticed some mistakes in my fixes which were fixed in the new branch, you should probably try the new branch just to be sure.

**Comment by lenck** [comment]
@amirjamaludin What version of the MSVC are you using? I'm trying to install the 2015 to test it with it as well, but it takes ages :)

**Comment by amirjamaludin** [comment]
@lenck I'm currently using the 2013 version.

**Comment by yhqlower** [comment]
hi, @lenck , I've also come across similar problems. I've recorded the way these problems are addressed in my blog http://www.colinyan.com/?p=161 . Hope can help people having similar problems if possible.

**Comment by lenck** [comment]
@amirjamaludin yes, you were right, for MSVC2013 it needs this include... Now it should be hopefully fixed :)

**Comment by lenck** [comment]
The fixes seems to work fine on a Linux machine as well so I've merged it to master, so other people do not end up with the same issues... Please let me know if you would have any problems and thanks again to all for reporting it!

**Comment by panovr** [comment]
I can confirm this fix works fine with cudnn-r4 on Windows 10, Visual Studio 2013, GTX 750, Matlab2015b and CUDA v7.5.
