### ISSUE TITLE
switching between CPU and GPU when resuming

### ISSUE THREAD

**Issue by guanggz** [vlfeat/matconvnet#37]
When i interrupt the example code, say `cnn_mnist` with `opts.train.useGpu = false`, and change it to GPU mode by doing `opts.train.useGpu = true`, it gives errors like
```
resuming by loading epoch 59
training: epoch 60: processing batch   1 of 600 ...Error using vl_nnconv
DATA and FILTERS are not both CPU or GPU arrays.
```
Also, if I complete run `can_mnist` in GPU mode, it will skip to run again in CPU mode.
Any idea that I can switch btw CPU and GPU freely and start from the beginning as I wish?

Thanks in advance.

**Comment by vedaldi** [comment]
Hi, the problem is that the intermediate models are saved either in GPU or CPU format, depending on the initial setting. The solution would be to use vl_simplenn_move() right after loading the intermediate model. We should add this to a future version.

**Comment by guanggz** [comment]
Hi Andrea, thanks for quick reply. 
It is a great function for notebooks to carry on with unfinished jobs. But as for now, could you suggest some quick fix/hints for this problem? thx.

**Comment by vedaldi** [comment]
Hi, yes of course. Simply use vl_simplenn_move() to convert the model to GPU or CPU as needed right after the load instruction in cnn_Train.m

**Comment by guanggz** [comment]
Thanks! good to go again :D
