### ISSUE TITLE
old net format in vl_simplenn_diagnose function

### ISSUE THREAD

**Issue by tinalegre** [vlfeat/matconvnet#372]
Just to report a small bug in [vl_simplenn_diagnose](https://github.com/vlfeat/matconvnet/blob/cf1d8e343eaf8c37e72174e6dc9d2538623e63d4/matlab/simplenn/vl_simplenn_diagnose.m) due to the new network format (looks like this function has not been updated yet). Basically, the variable `ly.filters` in lines [40](https://github.com/vlfeat/matconvnet/blob/cf1d8e343eaf8c37e72174e6dc9d2538623e63d4/matlab/simplenn/vl_simplenn_diagnose.m#L40) and [41](https://github.com/vlfeat/matconvnet/blob/cf1d8e343eaf8c37e72174e6dc9d2538623e63d4/matlab/simplenn/vl_simplenn_diagnose.m#L41) should be replaced with `ly.weights{1}`. In addition, variable `ly.biases` in lines [46](https://github.com/vlfeat/matconvnet/blob/cf1d8e343eaf8c37e72174e6dc9d2538623e63d4/matlab/simplenn/vl_simplenn_diagnose.m#L46) and [47](https://github.com/vlfeat/matconvnet/blob/cf1d8e343eaf8c37e72174e6dc9d2538623e63d4/matlab/simplenn/vl_simplenn_diagnose.m#L47) must be replaced with `ly.weights{2}`.

**Comment by lenck** [comment]
Hey, thanks for the report! :)
