### ISSUE TITLE
Uknown parameter 'useGpu' Mnist dataset

### ISSUE THREAD

**Issue by myouness** [vlfeat/matconvnet#373]
Hello,

I have an issue when using the function vl_argparse and opts.train.useGpu = false ;
>>Error using vl_argparse (line 100)
Uknown parameter 'useGpu'

Can somebody please help me find where is the problem.

Thank you very much.

Youness

**Comment by tinalegre** [comment]
@myouness I think, you are using an old version of the library ;-) The `opts.train.useGpu = false;` is not used any more. It's now: `opts.train.gpus = [];` as on [line 16](https://github.com/vlfeat/matconvnet/blob/master/examples/mnist/cnn_mnist.m#L16) in the cnn_mnist.m example. If you want to use gpu, then you need to set the variable to 1, e.g.: `opts.train.gpus = [1];`

**Comment by myouness** [comment]
Thank you very much for your answer. I solved the problem by using a corrected version of the code.

**Comment by lenck** [comment]
Hi, sorry, this bugfix is just in master, not in the distribution packages on the website... I'm glad it works for you...
