### ISSUE TITLE
how to perform forward and backward passes separately

### ISSUE THREAD

**Issue by fariba-abbasi** [vlfeat/matconvnet#375]
Hello everyone,

I want to perform forward and backward passes separately. In other words first I want to perform forward pass and get output of the network, then I perform backward pass using output of the network as input for backward pass. please tell me how to do it?

Thanks very much
Fariba

**Comment by lenck** [comment]
Hi, we have added this functionality in to the `vl_simplenn` interface in the devel branch just now (as we had this feature request on our todo list for some time).
It should be the easy to use as:
```
res = vl_simplenn(net, x); % forward pass
res = vl_simplenn(net, x, dzdy, res, 'skipForward', true); % backward pass only
```

**Comment by vedaldi** [comment]
Hi, another solution (which I used previously) was to define a custom layer to trigger the required code at the end (in between forward and backward pass). With closures it should be pretty flexible.
