### ISSUE TITLE
how to get the imdb.mat file using my own labeled images?

### ISSUE THREAD

**Issue by ShuenLyu** [vlfeat/matconvnet#383]
I have hundreds of images in several categories with labeled. my question is  how to get the imdb.mat file using the original labeled images because i want to train my own model.

**Comment by fengyunxiaozi** [comment]
this is very simple, just see the examples provided in matconvnet

**Comment by tinalegre** [comment]
@ShuenLyu have a look at the [cnn_imagenet_setup_data.m](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m) example. Basically, the function will return a structure named `imdb` with two main fields: `imdb.images` & `imdb.classes`. The IDs, names, training set labels, and class labels of your database images are set in the following fields respectively: [imdb.images.id](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m#L114), [imdb.images.name](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m#L115), [imdb.images.set](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m#L116), [imdb.images.label](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m#L117). The training set labels have 3 different values: `{1,2,3}`. The value `1` is associated with the training images, value `2` with validation images, and value `3` with testing Images.
A description and name of the class labels in your dataset are set up in: [imdb.classes.name](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m#L83) and [imdb.classes.description](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m#L84) accordingly. You'll also need to specify your image directory: [imdb.imageDir](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m#L85)

**Comment by ShuenLyu** [comment]
thanks very much.

**Comment by lenck** [comment]
@tinalegre Thanks for the perfect response! :)

**Comment by ShuenLyu** [comment]
@fengyunxiaozi  Hi,i think this cnn_imagenet_setup_data.m example cannot solve my problem because the label information is in an excel file not like the that of the example.
here is my problem that i have several hundreds original images in several catogries with labeled information in an excel file, I dont know how to use it  and how to convert it to mat file.
could you give me some advise.thanks very much.

**Comment by ShuenLyu** [comment]
@tinalegre   Hi,i think this cnn_imagenet_setup_data.m example cannot solve my problem because the label information is in an excel file not like the that of the example.
here is my problem that i have several hundreds original images in several catogries with labeled information in an excel file, I dont know how to use it and how to convert it to mat file.
could you give me some advise.thanks very much.

**Comment by prashant905** [comment]
@ShuenLyu  Did you sort out this issue. i am having the same problem and wondering can i create my own imdb dataset with my set of images.?Can you please guide through the solution?

**Comment by JavierCoronel** [comment]
Hi, is there a way to include the images in the .mat file? my database are image patches and not jpeg files in a folder
If someone could help me would be great

**Comment by Karakule** [comment]
Is there any one who can make a tutorial for making  imdb.mat file with using his/her own labeled images? It is very imporant for me.

**Comment by JavierCoronel** [comment]
@Karakule I could help you if you give me more information about your data.

**Comment by Karakule** [comment]
Thank you very much. I have 7 type of classes . In each class I have 144 images(jpg format). Now I want to make imdb file then classify with some network. Actually I dont know how creating new  netwolrk also.

**Comment by JavierCoronel** [comment]
@Karakule You have to do various task with your data before trying the network. You can write to me at jd.coronel30@uniandes.edu.co to give you specific information and solve your answers

**Comment by arash111** [comment]
Hi, can any body help me please, I have my own data (10 classes, and each contain around 300 jpg images), as I'm trying the method described above see the error: Error using cnn_imagenet_setup_data (line 51)
Make sure that ILSVRC data is correctly installed in data\imagenet12!! no idea please?

**Comment by samo313** [comment]
hello
I am trying to run ImageNet but the following error occurred. how should I resolve this error? any help would be appreciated.

Error using cnn_imagenet_setup_data (line 49)
Make sure that ILSVRC data is correctly installed in

thanks in advance

**Comment by hdm29** [comment]
hey friends,
i'm new to this topic. can anyone help me in creating imdb of my own dataset please? @lenck , i think you can provide some basic tutorial on this issue.  i tried to find but couldn't.
