### ISSUE TITLE
vl_nnconv speed bug?

### ISSUE THREAD

**Issue by okvol** [vlfeat/matconvnet#385]
If one runs vl_nnconv repeatedly, its speed drops by about 100 times.

Code to reproduce the bug:

x2 = gpuArray(single(randn(56, 56, 64, 32)));
f2 = gpuArray(single(randn(3, 3, 64, 128)));
b2 = gpuArray(single(randn(128,1)));
dzdy2 = gpuArray(single(randn(56, 56, 128, 32)));
other_opts = {'cuDNN'};
iter = 100;
record = zeros(1,iter);
for i = 1:100
    timer = tic; vl_nnconv(x2, f2, b2, dzdy2, 'Pad', 1, 'Stride', 1, other_opts{:}); record(i)=toc(timer);
end
plot(record);

![vl_nnconv_speed_drop](https://cloud.githubusercontent.com/assets/13367977/12373475/4b163622-bc48-11e5-88f7-d22f3c7a51ae.png)

If you cannot reproduce it, try making the filter dimension/size and the "iter" variable larger.

One way to eliminate it is to pause artificially.
record = zeros(1,iter);
for i = 1:100
    timer = tic; vl_nnconv(x2, f2, b2, dzdy2, 'Pad', 1, 'Stride', 1, other_opts{:}); record(i)=toc(timer);
    pause(0.01);
end
plot(record);

![vl_nnconv_speed_drop_pause](https://cloud.githubusercontent.com/assets/13367977/12373519/78290f62-bc49-11e5-8fc2-7431788dfdf1.png)

The version is beta17. It's compiled with GPU and cuDNN enabled.

I tried disabling cuDNN by
setting other_opts = {'NoCuDNN'};
The slow down seems to happen even earlier.
![vl_nnconv_speed_drop_nocudnn](https://cloud.githubusercontent.com/assets/13367977/12373545/9158aef6-bc4a-11e5-9dde-e38c14be4af9.png)

**I don't think this problem is artificial. It happens in practice when training many models. However, pausing artificially in training does not resolve this issue.** Only resetting the GPU can resolve it.

It would be best to figure out exactly why it happens.

**Comment by okvol** [comment]
@vedaldi 
@lenck

**Comment by lenck** [comment]
Hi, yes, I can confirm this issue. Though I have no idea why is it happening only for back-propagation :( We will try to investigate it more...

**Comment by lenck** [comment]
Hmm, I'm not sure if it is a bug. If you put `wait(gpuDevice);` the processing time starts to be more reasonable. So it may be a side effect of the way how Matlab is launching the GPU kernels (e.g. that it launches the first 50 asynchronously and then it waits for the rest)...

**Comment by okvol** [comment]
@lenck 
I believe you are right. They are asynchronously calls by default. So I guess it's not a bug.
