### ISSUE TITLE
CUDA kernel error (unspecified launch failure)

### ISSUE THREAD

**Issue by guanggz** [vlfeat/matconvnet#40]
Hi, I hit an error when I want to pass my image  through `net`  on GPU (Tesla k20c / Ubuntu 1204/Matlab 2014a). 
here's the error
```
im2col: CUDA kernel error (unspecified launch failure)
Error using gpuArray/max
An unexpected error occurred during CUDA execution. The CUDA error was:
unspecified launch failure

Error in vl_nnrelu (line 17)
  y = max(x, single(0)) ;

Error in vl_simplenn (line 165)
      res(i+1).x = vl_nnrelu(res(i).x) ;
...
```
Both `net` and input image were moved to gpu. Thanks for help!

**Comment by eric-phu** [comment]
You may want to try attaching cuda-gdb to Matlab and see where the problem really is.

**Comment by lenck** [comment]
Hi @guanggz, can you check if this solves the issue for you?
I've got similar errors, but only when I've swtiched the GPUs. So this commit should fix that, but I'm not sure if it is your case....

**Comment by guanggz** [comment]
@lenck I would guess so. I will try to reconstruction the problem and come back to it once I have access to that machine.

**Comment by vedaldi** [comment]
beta9 should be much more resilient to switching GPUs. I think this problem is likely fixed.
