### ISSUE TITLE
Batch Normalization in Testing

### ISSUE THREAD

**Issue by arjunsubway** [vlfeat/matconvnet#409]
Hi,

I recently downloaded beta18 after working with beta13 for an extended period of time. I had tried batch normalization in 13, but I ran into problems while testing. I did read in beta17 that BN had been updated so that it is easy to bypass at test time, so I tried it again. I used the mnist example 'insertBnorm' method to insert batch normalization after each convolutional and fully-connected layer.

Although the network trained without issue, as before, I ran these lines to evaluate the network:

pred = vl_simplenn(net, newImg);
probs = pred(14).x;

When I test the network on different cases, I always get the exact same probabilities. If I train the network without BN, I don't get this issue. Is there still something I need to do at test-time after I have trained the network so that BN can work properly? Sorry if this is a bad question, but I'm still new to matconvnet :) I did see low error rates while training, so I hope I can get it working. Thanks!

Best,
Arjun

**Comment by bazilas** [comment]
Hi, 

do you set the network in test mode (a.k.a. net.mode='test')?
