### ISSUE TITLE
vl_compilenn error win 10.

### ISSUE THREAD

**Issue by HEIMDAL13** [vlfeat/matconvnet#413]
Hi, I tried to follow the quickstar guide in order to install matconvnet on my windows 10 x64 using MATLAB 2015b. The problem is that I can not compile it by using the command run vl_compilenn, I get lots of errors.

Does anyboody know what can be the problem?
I installed TDM-GCC-64 as a compiler.

Thanks!

`>> vl_compilenn
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Building with 'MinGW64 Compiler (C++)'.
Error using mex
In file included from
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_helpers.hpp:18:0,
                 from
                 C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp:14:
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_hadd_epi16(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:42:70: error: '__builtin_ia32_phaddw128' was not
declared in this scope
   return (__m128i) __builtin_ia32_phaddw128 ((__v8hi)__X, (__v8hi)__Y);
                                                                      ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_hadd_epi32(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:48:70: error: '__builtin_ia32_phaddd128' was not
declared in this scope
   return (__m128i) __builtin_ia32_phaddd128 ((__v4si)__X, (__v4si)__Y);
                                                                      ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_hadds_epi16(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:54:71: error: '__builtin_ia32_phaddsw128' was not
declared in this scope
   return (__m128i) __builtin_ia32_phaddsw128 ((__v8hi)__X, (__v8hi)__Y);
                                                                       ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_hadd_pi16(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:60:65: error: '__builtin_ia32_phaddw' was not declared
in this scope
   return (__m64) __builtin_ia32_phaddw ((__v4hi)__X, (__v4hi)__Y);
                                                                 ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_hadd_pi32(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:66:65: error: '__builtin_ia32_phaddd' was not declared
in this scope
   return (__m64) __builtin_ia32_phaddd ((__v2si)__X, (__v2si)__Y);
                                                                 ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_hadds_pi16(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:72:66: error: '__builtin_ia32_phaddsw' was not
declared in this scope
   return (__m64) __builtin_ia32_phaddsw ((__v4hi)__X, (__v4hi)__Y);
                                                                  ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_hsub_epi16(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:78:70: error: '__builtin_ia32_phsubw128' was not
declared in this scope
   return (__m128i) __builtin_ia32_phsubw128 ((__v8hi)__X, (__v8hi)__Y);
                                                                      ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_hsub_epi32(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:84:70: error: '__builtin_ia32_phsubd128' was not
declared in this scope
   return (__m128i) __builtin_ia32_phsubd128 ((__v4si)__X, (__v4si)__Y);
                                                                      ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_hsubs_epi16(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:90:71: error: '__builtin_ia32_phsubsw128' was not
declared in this scope
   return (__m128i) __builtin_ia32_phsubsw128 ((__v8hi)__X, (__v8hi)__Y);
                                                                       ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_hsub_pi16(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:96:65: error: '__builtin_ia32_phsubw' was not declared
in this scope
   return (__m64) __builtin_ia32_phsubw ((__v4hi)__X, (__v4hi)__Y);
                                                                 ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_hsub_pi32(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:102:65: error: '__builtin_ia32_phsubd' was not
declared in this scope
   return (__m64) __builtin_ia32_phsubd ((__v2si)__X, (__v2si)__Y);
                                                                 ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_hsubs_pi16(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:108:66: error: '__builtin_ia32_phsubsw' was not
declared in this scope
   return (__m64) __builtin_ia32_phsubsw ((__v4hi)__X, (__v4hi)__Y);
                                                                  ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_maddubs_epi16(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:114:75: error: '__builtin_ia32_pmaddubsw128' was not
declared in this scope
   return (__m128i) __builtin_ia32_pmaddubsw128 ((__v16qi)__X, (__v16qi)__Y);
                                                                           ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_maddubs_pi16(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:120:68: error: '__builtin_ia32_pmaddubsw' was not
declared in this scope
   return (__m64) __builtin_ia32_pmaddubsw ((__v8qi)__X, (__v8qi)__Y);
                                                                    ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_mulhrs_epi16(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:126:72: error: '__builtin_ia32_pmulhrsw128' was not
declared in this scope
   return (__m128i) __builtin_ia32_pmulhrsw128 ((__v8hi)__X, (__v8hi)__Y);
                                                                        ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_mulhrs_pi16(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:132:67: error: '__builtin_ia32_pmulhrsw' was not
declared in this scope
   return (__m64) __builtin_ia32_pmulhrsw ((__v4hi)__X, (__v4hi)__Y);
                                                                   ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_shuffle_epi8(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:138:72: error: '__builtin_ia32_pshufb128' was not
declared in this scope
   return (__m128i) __builtin_ia32_pshufb128 ((__v16qi)__X, (__v16qi)__Y);
                                                                        ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_shuffle_pi8(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:144:65: error: '__builtin_ia32_pshufb' was not
declared in this scope
   return (__m64) __builtin_ia32_pshufb ((__v8qi)__X, (__v8qi)__Y);
                                                                 ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_sign_epi8(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:150:72: error: '__builtin_ia32_psignb128' was not
declared in this scope
   return (__m128i) __builtin_ia32_psignb128 ((__v16qi)__X, (__v16qi)__Y);
                                                                        ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_sign_epi16(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:156:70: error: '__builtin_ia32_psignw128' was not
declared in this scope
   return (__m128i) __builtin_ia32_psignw128 ((__v8hi)__X, (__v8hi)__Y);
                                                                      ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_sign_epi32(__m128i,
__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:162:70: error: '__builtin_ia32_psignd128' was not
declared in this scope
   return (__m128i) __builtin_ia32_psignd128 ((__v4si)__X, (__v4si)__Y);
                                                                      ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_sign_pi8(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:168:65: error: '__builtin_ia32_psignb' was not
declared in this scope
   return (__m64) __builtin_ia32_psignb ((__v8qi)__X, (__v8qi)__Y);
                                                                 ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_sign_pi16(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:174:65: error: '__builtin_ia32_psignw' was not
declared in this scope
   return (__m64) __builtin_ia32_psignw ((__v4hi)__X, (__v4hi)__Y);
                                                                 ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_sign_pi32(__m64, __m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:180:65: error: '__builtin_ia32_psignd' was not
declared in this scope
   return (__m64) __builtin_ia32_psignd ((__v2si)__X, (__v2si)__Y);
                                                                 ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_alignr_epi8(__m128i,
__m128i, int)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:188:32: error: '__builtin_ia32_palignr128' was not
declared in this scope
            (__v2di)__Y, __N * 8);
                                ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_alignr_pi8(__m64, __m64,
int)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:195:27: error: '__builtin_ia32_palignr' was not
declared in this scope
       (__v1di)__Y, __N * 8);
                           ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_abs_epi8(__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:211:57: error: '__builtin_ia32_pabsb128' was not
declared in this scope
   return (__m128i) __builtin_ia32_pabsb128 ((__v16qi)__X);
                                                         ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_abs_epi16(__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:217:56: error: '__builtin_ia32_pabsw128' was not
declared in this scope
   return (__m128i) __builtin_ia32_pabsw128 ((__v8hi)__X);
                                                        ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m128i _mm_abs_epi32(__m128i)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:223:56: error: '__builtin_ia32_pabsd128' was not
declared in this scope
   return (__m128i) __builtin_ia32_pabsd128 ((__v4si)__X);
                                                        ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_abs_pi8(__m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:229:51: error: '__builtin_ia32_pabsb' was not declared
in this scope
   return (__m64) __builtin_ia32_pabsb ((__v8qi)__X);
                                                   ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_abs_pi16(__m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:235:51: error: '__builtin_ia32_pabsw' was not declared
in this scope
   return (__m64) __builtin_ia32_pabsw ((__v4hi)__X);
                                                   ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h: In function '__m64 _mm_abs_pi32(__m64)':
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/tmmintrin.h:241:51: error: '__builtin_ia32_pabsd' was not declared
in this scope
   return (__m64) __builtin_ia32_pabsd ((__v2si)__X);
                                                   ^
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp: In member function
'vl::Error vl::ImageReader::Impl::readPixels(float*, const char*)':
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp:77:83: error:
'mbstowcs_s' was not declared in this scope
   mbstowcs_s(&n, filenamew, sizeof(filenamew)/sizeof(wchar_t), filename, _TRUNCATE);
                                                                                   ^
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp:144:1: error: jump to
label 'done' [-fpermissive]
 done:
 ^
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp:83:10: error:   from
here [-fpermissive]
     goto done ;
          ^
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp:92:24: error:   crosses
initialization of 'Gdiplus::PixelFormat targetPixelFormat'
   Gdiplus::PixelFormat targetPixelFormat = PixelFormat32bppRGB ;
                        ^
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp:90:9: error:   crosses
initialization of 'vl::Image image'
   Image image(shape, memory);
         ^
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp: In member function
'vl::Error vl::ImageReader::Impl::readShape(vl::ImageShape&, const char*)':
C:\Users\HEIMDAL13\Documents\MATLAB\matconvnet-1.0-beta18\matlab\src\bits\impl\imread_gdiplus.cpp:157:83: error:
'mbstowcs_s' was not declared in this scope
   mbstowcs_s(&n, filenamew, sizeof(filenamew)/sizeof(wchar_t), filename, _TRUNCATE);
                                                                                   ^

Error in vl_compilenn>mex_compile (line 478)
mex(mopts{:}) ;

Error in vl_compilenn (line 439)
    mex_compile(opts, srcs{i}, objfile, flags.mexcc) ;`

**Comment by Cotangent-1** [comment]
What was your solution to this error?

**Comment by HEIMDAL13** [comment]
The problem was that I used MinGW as compiler (it's not suppoerted by matconvnet). So I compiled the files from another computer with win7 and Visual C++ 2013 and it worked fine.

**Comment by santiago-vas** [comment]
@HEIMDAL13 , hey man i see your problem is little old, but i have the same one, i dont understand, how did you change the compiler?, using the` mex -setup ` function?
 i thought MinGW needed microsoft visual studio to work, i also installed SDK 10, but still hetting just the same error, do you have any suggestion for this?
