### ISSUE TITLE
Error in vl_compilenn>mex_compile

### ISSUE THREAD

**Issue by HEIMDAL13** [vlfeat/matconvnet#414]
Hi, I installed visual C++ SDK 2015 to use as a compiler for matlab 2015b.

The problem is that when I try to run vl_compilenn I get the following error:

`Error using mex
data.cpp
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE\crtdefs.h(10): fatal error C1083: Cannot open include file:
'corecrt.h': No such file or directory

Error in vl_compilenn>mex_compile (line 478)
mex(mopts{:}) ;

Error in vl_compilenn (line 439)
    mex_compile(opts, srcs{i}, objfile, flags.mexcc) ;

Error in run (line 96)
evalin('caller', [script ';']);`

Does somebody know why it isn't working?

Thanks.

**Comment by HEIMDAL13** [comment]
Problem solved, I compiled the program from another windows machine with visual c++ sdk 2013 and it works fine.

I supose it's something related with windows 10 or maybe visual studio 2013 IDK.

**Comment by RastgooBio** [comment]
I try to compile matconvnet in Windows 10 x64 and MATLAB 2017a. I had following error too:
    'corecrt.h': No such file or directory
I searched the file corecrt.h in my computer and find it in the following path:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
so my ucrt version is 10.0.10240.0
I add environment variable UCRTVersion and set it to 10.0.10240.0 , problem solved.

**Comment by Anguliachao** [comment]
@RastgooBio  Hi, I faced the same problem on matlab2015b, but problem didnot solve after I set the environment variable, would you mind give some details?
