### ISSUE TITLE
out of memory on device error at vl_nnrelu

### ISSUE THREAD

**Issue by imsosleepyy** [vlfeat/matconvnet#415]
```
net = load('data/imagenet-vgg-verydeep-16.mat');
trainOpts.batchSize = 100 ;
trainOpts.numEpochs = 50 ;
trainOpts.continue = true ;
trainOpts.useGpu = true ;
trainOpts.learningRate = 0.001 ;
trainOpts.expDir = 'data/images-experiment2' ;
trainOpts = vl_argparse(trainOpts, varargin);

imdb = load('data/imagedb.mat') ;
imageMean = mean(imdb.images.data(:)) ;
imdb.images.data = imdb.images.data - imageMean ;

% Convert to a GPU array if needed
if trainOpts.useGpu
  imdb.images.data = gpuArray(imdb.images.data) ;
end

% Call training function in MatConvNet
[net,info] = cnn_train(net, imdb, @getBatch, trainOpts) ;
```

I want to train pre-trained model, 'imagenet-vgg-verydeep-16.mat'

but at layers{1,9} : relu2_2 occured out of memory error.

error massage is 
**gpuArray/max
Out of memory on device. To view more detail about available memory on the GPU, use
'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)' .
**

My configuration Window 7 64 bit, Matlab 2015a, cuda7.5, gpu GeForce GTX TITAN X.

I don't know why make this error. My imagedb is not large and set 224 x 224 x 3 input size. 

Did not enough GeForce GTX TITAN X's memory?

Thanks in advance.

**Comment by fengyunxiaozi** [comment]
which version  did you use, MatConvNet-16 or the after? I have encountered this problem before. The same training data and network work well using the 16 version, but warn "out of memory" when using the latter version.
If you use the latter versions (17,18), you can first compute the necessary memory for your data and network parameter ; you can also try "cudnnWorkspaceLimit", as shown in the function cnn_imagenet_init to limit the memory used by cudnn.

**Comment by imsosleepyy** [comment]
This problem occured so many image on workspace, and needed too large computation because imagenet-vgg-verydeep-16's all convolution layer stride sets 1. I can solve this problem just changed pre-trained model and used Image's path. thanks.

**Comment by RMano82** [comment]
Hi @imsosleepyy . How did you solve this problem? I am having the same issue with the MatConvNet-20 version!
Thank you
