### ISSUE TITLE
mnist code example question

### ISSUE THREAD

**Issue by johnny5550822** [vlfeat/matconvnet#42]
What does this mean?

imdb.images.set = [ones(1,numel(y1)) 3*ones(1,numel(y2))] ;
imdb.meta.sets = {'train', 'val', 'test'} ;

**Comment by luzhi** [comment]
Hi @johnny5550822 ,

The first line means assign the "set ID (e.g., 1 for train, 2 for validate, and 3 for test)" for each instance, where the "set" here means "train" set, "validate" set or "test" set, as that shown in the second line.

**Comment by johnny5550822** [comment]
Thanks for the reply. So, what exactly the different between val and test?

When I do machine learning, I usually do cross validation, e.g., like leave one out. What about the val here? To me, it's seem like I only use train data to train the model, and then use val data to validate, and essentially and I also have test data to validate. What're the difference between test and train?

**Comment by lenck** [comment]
Hi, there is a loads of material regarding this question on the [internets](http://stats.stackexchange.com/questions/19048/what-is-the-difference-between-test-set-and-validation-set).
Just cleaning up old issues, so I hope you don't mind that I will close this one :)
