### ISSUE TITLE
HoledConv Layer

### ISSUE THREAD

**Issue by liavassif** [vlfeat/matconvnet#423]
Hi,
I've created a crude implementation in MatConvNet of the 'hole' algorithm described in [Semantic Image Segmentation with Deep Convolutional Nets and Fully Connected CRFs] (http://arxiv.org/abs/1412.7062) at https://github.com/liavassif/holedConv. The only implemented part is the 'hole' algorithm, without any CRF afterwards. 
A new layer named HoledConv was created. If useful, it could be later merged here.

**Comment by bazilas** [comment]
If you would like to have more feedback from your implementation, you can start a discussion in our forum: https://groups.google.com/forum/#!forum/matconvnet
