### ISSUE TITLE
Matconvnet is using my CPU instead of GPU

### ISSUE THREAD

**Issue by kbenahmed89** [vlfeat/matconvnet#425]
Hi,

I compiled matconvnet to use GPU with the command vl_compilenn('enableGpu',true,'cudaMethod','nvcc') it compiled with no errors.
I tested the cnn_imagenet code, and as soon as I run the CPU utilization jumped up while GPU utilization did not change.
does this mean that the code is not using my GPU? why ?

**Comment by fengyunxiaozi** [comment]
have you set "opts.train.gpus = []" in cnn_imagenet function

**Comment by kbenahmed89** [comment]
No, I made it equal to 1.

**Comment by kbenahmed89** [comment]
is there a function that tests if GPU is being actually used?

**Comment by fengyunxiaozi** [comment]
yes, vl_testnn('gpu', true) works.

**Comment by kbenahmed89** [comment]
thanks it worked.
