### ISSUE TITLE
Why there is a validation in cnn_train?

### ISSUE THREAD

**Issue by kbenahmed89** [vlfeat/matconvnet#433]
Hi,
cnn_train is upposed to only train networks, why do you make validation inside this code?

**Comment by fengyunxiaozi** [comment]
if there is no validation, we cannot know when to stop the training process

**Comment by kbenahmed89** [comment]
can you explain in more details please?

**Comment by fengyunxiaozi** [comment]
suppose the function of training, validation and testing data in a classification task.
