### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by itaykez** [vlfeat/matconvnet#434]
Hi all,

I recently encountered two issues:
1) Compilation is needed every time I open a new matlab (in my linux matlab2015a and windows matlab2015b machines, both have cuda 7.5).
2) I cant compile with enableCudnn option on, i.e., vl_compilenn('enableGpu', true, 'cudaMethod', 'nvcc', 'enableCudnn', 'true'). 
First I get an error with the driver compiler (see attached) 
![a](https://cloud.githubusercontent.com/assets/11193230/13312201/58dcfe0c-db9d-11e5-8ed9-25bf1a5fd0ca.JPG)
After I close it, the error is that: "fatal error C1083: Cannot open include file: 'cudnn.h': No such file or directory data.cu ".

Thanks in advance!

**Comment by fengyunxiaozi** [comment]
hi, just follow the compilation instruction in the homepage. according to " Cannot open include file: 'cudnn.h", it seems you have not indicated the path of cudnn .
