### ISSUE TITLE
Extract features from RES using DAGNN

### ISSUE THREAD

**Issue by lyltencent** [vlfeat/matconvnet#435]
When using a pretrained model, how to extract features for a new image. 

I know if the model is trained using simpleNN, we can use 

res = vl_simplenn(net,im_) to achieve that. 

Is there a similar function for a pre-trained model if it is trained using DagNN.

Thanks,

**Comment by fengyunxiaozi** [comment]
see this "http://www.vlfeat.org/matconvnet/wrappers/"

**Comment by lyltencent** [comment]
@fengyunxiaozi , 

Thanks for your reply. I have seen this page before. I think what I need is the same output variable of "res" that exists when using simplenn function. The res contains output for each layer of the neural network. Is there a fast way we can get these variables when the model is trained using the dagnn?

I think in that webpage you mentioned. it seems that we can do that, but we have to do it one layer by one layer and propagate back. Am I correct?

Thanks!

**Comment by hamidfarhid** [comment]
@lyltencent : Did you get your answer? I have a same question.
Thanks

**Comment by lyltencent** [comment]
Hi, @hamidfarhid , 
I think as point out by @fengyunxiaozi , the output of the layers using dagnn can be extracted using code like: 
 
i = net.getVarIndex('x3') ;
output = net.vars(i).value ;

**Comment by karthikknidhi** [comment]
what is x3 here ?

**Comment by KhwildiRaoua** [comment]
I have the same problem. Please how extract features from the under layers like res5c ? I used net.vars(.net.getVarIndex('res5c')).value ; but it returns  empty descriptor.
