### ISSUE TITLE
Erreur with Load?

### ISSUE THREAD

**Issue by khouloud123** [vlfeat/matconvnet#436]
Hi,
when i run the  code 

setup ;

%% Part 3.1: Prepare the data

% Load a database of blurred images to train from

load('data\text_imdb.mat') ;

the following  erreur appears why?

Error using load
Can't read file C:\Program Files\MATLAB\CODE2\practical-cnn-reg-2016a\data\text_imdb.mat.

Thanks

**Comment by bazilas** [comment]
You might want to try again. I have just downloaded the code/data and it works fine.
