### ISSUE TITLE
Can I abort top-5 error

### ISSUE THREAD

**Issue by johnny5550822** [vlfeat/matconvnet#44]
If my number of possible label is only 2 (binary classification, matconvnet will give me error. I believe this is because I don't have at least 5 possible labels. How can I solve this?

Index exceeds matrix dimensions.

Error in cnn_train>updateError (line 271)
    info.topFiveError(end) = info.topFiveError(end) + ...

Error in cnn_train (line 167)
    info.train = updateError(opts, info.train, net, res, batch_time) ;

Error in stroke_nn_medicalData_011415 (line 76)
[net, info] = cnn_train(net, medical_record_imdb, @getBatch, ...

**Comment by johnny5550822** [comment]
I think I know it. Basically, just set additionally 3 more labels but none of my training data has that output.

**Comment by titubeta** [comment]
A better way is to set labels as +1 and -1, and set opts.errorFunction = 'binary' ; in the cnn_train file.

**Comment by KumudTripathi** [comment]
In my problem, classes are 3 and error is same as above. then how to set labels:

Index exceeds matrix dimensions.

Error in cnn_train>updateError (line 271)
info.topFiveError(end) = info.topFiveError(end) + ...

Error in cnn_train (line 167)
info.train = updateError(opts, info.train, net, res, batch_time) ;

Error in stroke_nn_medicalData_011415 (line 76)
[net, info] = cnn_train(net, medical_record_imdb, @getBatch, ...
