### ISSUE TITLE
Temporal max-pooling

### ISSUE THREAD

**Issue by pxnguyen** [vlfeat/matconvnet#443]
I am working with videos, each frame is processed forward with vgg-16 independently. The relu7 outputs are temporally max-pooled. I would like to fine-tune this network. How would I start on implementing the temporal max-pool layer?

**Comment by omair-kg** [comment]
Hi @pxnguyen , you could try incorporating the 3d maxpooling function from here or at least get an idea where to begin with temporal pooling.
https://github.com/pengsun/MexConv3D
