### ISSUE TITLE
ROC to evaluate the trained network ? 

### ISSUE THREAD

**Issue by eunjoa** [vlfeat/matconvnet#448]
Could anybody give me an intuition on how to draw a ROC curve to evaluate my network trained with matconvnet to do binary classification. In my knowledge, to generate ROC we plot false positive rate and true positive rate variating the confidence threshold. in my binary classification the threshold is fixed to 0.5. How ROC curves are plot in deep learning papers treating similar problems ?

**Comment by AruniRC** [comment]
Hi @eunjoa 

1) The VLFeat library has a function, [vl_roc](http://www.vlfeat.org/matlab/vl_roc.html), that can plot ROC curves.
2) You need to give it two arrays, `labels` and `scores`.
    Labels would be -1 or +1 for your binary classes.
    The scores could be the outputs at the final layer of your deep network, positive for class +1 and negative for class -1.

Afaik, ROC is a general evaluation metric which would be the same regardless of whether you use deep learning to obtain the final scores, or maybe take SVM outputs to be the scores.

**Comment by eunjoa** [comment]
Thank you @AruniRC that was useful !!
