### ISSUE TITLE
Error while fine-adjusting cifar to different number of classes

### ISSUE THREAD

**Issue by Daifchen** [vlfeat/matconvnet#459]
I have 5 classes, but when I try to adapt the last layer to this output, I get an error index exceeds matrix dimension in the 5th batch.

--
output Matlab:
> train: epoch 01:   5/383: Index exceeds matrix dimensions.
> Error in vl_nnsoftmaxloss (line 73)
>  t = Xmax + log(sum(ex,3)) - reshape(X(c_), [sz(1:2) 1 sz(4)]) ;

--
My last 2 layers are:
> net.layers{end+1} = struct('type', 'conv', ...
>                           'weights', {{0.05*randn(1,1,64,5, 'single'), zeros(5,1,'single')}}, ...
>                           'learningRate', .1*lr, ...
>                           'stride', 1, ...
>                           'pad', 0) ;
> % Loss layer
> net.layers{end+1} = struct('type', 'softmaxloss');

I don't quite understand where these wrong sized matrixes come from, even more so as the first batches do not get that error.

Regards
Patricia

**Comment by Daifchen** [comment]
Found my Error myself

**Comment by asaydin** [comment]
What is your error? I am having the same issue.

**Comment by Daifchen** [comment]
My error was "index exceeds matrix size" in the function maxsoftloss. 
Cifar has to be adapted at two places for a different number of classes:
- in the init the last conv-layer has to contain in the filter the correct number of classes (5 in my case)
- the classes have to be numbered from 1 to n for n classes, here in the function cnn-cifar, the loading of data could cause trouble if not verified.
Hope I could help

**Comment by asaydin** [comment]
That was helpful. Thanks!
