### ISSUE TITLE
vl_compilenn issue

### ISSUE THREAD

**Issue by kalov** [vlfeat/matconvnet#460]
I recommend this change [vl_compilenn:315]:

flags.cc{end+1} = ['-I' opts.cudnnIncludeDir] ;
=> 
flags.cc{end+1} = ['-I"' opts.cudnnIncludeDir '"'] ;

Otherwise if the include directory looks like this "C:\Program Files\..." i.e., there are spaces, it won't compile. This should work in linux, too.

**Comment by lenck** [comment]
Thanks for reporting it and @DefineFc for creating a pull request...
