### ISSUE TITLE
DATA and FILTERS do not have compatible formats in vl_nnconv

### ISSUE THREAD

**Issue by Lawrence444** [vlfeat/matconvnet#463]
Hi, I run into the following issue when I use the gpu version on the pretrained 16-layer ImageNet network, the CPU version runs without any problem. The array is already single. CUDA version is 7.5, MATLAB version is R2015b. Operating System is CentOS 6.4. Any clue what that error is?

vl_simplenn(net,gpuArray(x), [],[],opt)
Error using vl_nnconv
DATA and FILTERS do not have compatible formats.

Error in vl_simplenn (line 288)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

> > vl_simplenn(net,x, [],[],opt)

ans =

1x38 struct array with fields:

```
x
dzdx
dzdw
aux
stats
time
backwardTime
```

**Comment by ZhangWen0301** [comment]
Hello , Did you have solved it ? I have the same problem. Thanks.

**Comment by aliceCohenHadria** [comment]
Hello

I've had the same problem and it turned out that my inputs were double arrays while my filters were declared as single arrays.
By converting my inputs in single arrays, it finally worked.

**Comment by Lawrence444** [comment]
For me, it is already single. As you can see that it works when x is not a gpuArray. If x is double, it wouldn't work regardless whether I use GPU or not.

**Comment by amirmazaheri1990** [comment]
Same problem here. After I move the network to GPU, it happens. 

net = vl_simplenn_move(net,'gpu');
res = vl_simplenn(net, im_) ;
Error using vl_nnconv
DATA and FILTERS do not have compatible formats.

Error in vl_simplenn (line 296)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...

**Comment by syagev** [comment]
I imagine, like me, you forgot to transfer the network itself (i.e the filters) to the GPU. You can verify this easily by testing the type of one of your filters, something like:

    isa(net.layers{1}.filters, 'gpuArray')

It should evaluate to 1

**Comment by Jinwoo-Jeon** [comment]
res(i).x, l.weights{1} and l.weights{2} should be all gpuArray.

**Comment by thehh1974** [comment]
vl_simplenn_move will do it for you.
net = vl_simplenn_move(net,'gpu');

**Comment by purity77** [comment]
I meet the same problem，and i found this is because the vl_nnconv need the format of filters H*W*C*N,but my input matric's formats are H*W.It channels aer nonn and can't divided by filters channel.
when i change my input format to H*W*1,it solved
