### ISSUE TITLE
How to visulize the learned filter of each layer?

### ISSUE THREAD

**Issue by tzczsq** [vlfeat/matconvnet#464]
Hi, could you please tell me how to visulize the learned filter of each CNN layer?
The following answers  tell me how to  only visualize the learned filters of the first CNN layer, but could not visulize the other CNN layers.  It seems that if the filter response is not 3 channel, we could not visulize it. However, Caffe can show the filter response of each CNN layer.

https://github.com/vlfeat/matconvnet/issues/94
You can just recover the filters and use Matlab's functions to display them as images. For example after loading a pretrained net from http://www.vlfeat.org/matconvnet/pretrained/ :
imshow( net.layers{1}.filters(:, :, 3, 1), [] ) ;

You may find the VLFeat function vl_imarraysc useful to display several filters.
http://www.vlfeat.org/matlab/vl_imarraysc.html

See also the tutorial:
http://www.robots.ox.ac.uk/~vgg/practicals/cnn/index.html

**Comment by lenck** [comment]
Hi, nobody really knows :) You can either take the maximum of the filter values to see the spatial distribution of its values but it impossible to tell anything more that 'Hmm, nice 3x3 filters'.
But one thing you can do is to play with the inverse of the whole network. E.g. using [Aravindh's work](https://github.com/aravindhm/deep-goggle) which allows you to project single image activations into the image domain.
