### ISSUE TITLE
How to accumulate the loss through several batches

### ISSUE THREAD

**Issue by cheer37** [vlfeat/matconvnet#465]
There is a this function in caffe by iter_size
what about MatConvnet?
There is not this function?

**Comment by vedaldi** [comment]
Hi, sue numSubBatches > 1

**Comment by cheer37** [comment]
numSubBatch is equal to iter_size?
so assume my batch size is M, numSubBatch is N, loss will be calculated through MxN images?
And also, there is no need to shuffle train dataset explicitly?
I am wondering why my net is diverging, this proved to converge in caffe.
Thanks.

**Comment by vedaldi** [comment]
Hi, numSubBatches breaks a batch into that number. I am not sure how Caffe interprets iter_size.

Convergence problems are usually due to some difference in the parameters, often something subtle as preprocessing the data in the same manner (e.g. removing the mean).

**Comment by cheer37** [comment]
When batch size is small, loss fluctuate largely, losing generalization.
If we have a small sized memory in gpu, we can increase the batch size.
To avoid this situation, caffe implemented the function to accumulate the loss through batch size x iter_size.
But using numSubBatches does not seem the same as caffe.
And also, I configured the parameters as the same in caffe.
What about shuffle?
shuffling is done in cnn_train in default?
Thanks.

**Comment by bazilas** [comment]
Yes, shuffling is inside the cnn_train.
