### ISSUE TITLE
How to deal big data which cannot be read into memory  in one time

### ISSUE THREAD

**Issue by jesszgc** [vlfeat/matconvnet#466]
I cannot get a variable in the workspace which contains all the data i need to train the net. 
How can I deal this problem?

**Comment by svarjo** [comment]
I see two options: A) Buy more memory. B) write a suitable getBatch function that read data from files (might get bit slow but...). Study for the B) example cnn_imagenet_get_batch.m...

**Comment by bazilas** [comment]
If you cannot fit the data in your RAM, you have to read it from the hard-drive for every mini-batch.
