### ISSUE TITLE
Running a trained net from the CIFAR example (will e-transfer 20USD)

### ISSUE THREAD

**Issue by afuller187** [vlfeat/matconvnet#474]
Hi everyone,

I followed the CIFAR example to a tee in order to train on my own data set. It successfully trained and I have the saved net as a .mat file in the data folder. 

However, when I attempt to run the CNN using the vl_simplenn (just like the example using the imagenet VGG and the bell peppers) I get errors. I realized that my net .mat file was formatted differently from the example net .mat file (imagenet−vgg−f.mat). So I edited the vl_simplenn code setting these:

net.layers = net.net.layers;
net.meta = net.net.meta;

This fixed the first errors I was receiving but now I am getting other errors. For example, the assertion is failing in the vl_nnsoftmaxloss file for this case: assert(isequal(sz_, [sz(1) sz(2) sz_(3) sz(4)])) ;

If anyone can help me properly run this CIFAR net I will happily e-transfer them 20USD.

Thanks a ton!

**Comment by afuller187** [comment]
Problem solved. After looking through the message board I found the Professors recommend this in the v1_simplenn file:

net.layers(end) = []

It worked.

**Comment by anewlearner** [comment]
@afuller187  I also used the  cifar10 to do classification. But during the test process,the score for the same image is different every time. Do you know why?
A example for test would be appreciated. Thanks!
