### ISSUE TITLE
Why does the binary classification give a large training error number?

### ISSUE THREAD

**Issue by luzhi** [vlfeat/matconvnet#48]
I did a binary classification task that I changed the opt.errorType from "multiclass" to "binary" in cnn_train.m . Accordingly, when the training process **update the error** by the function:

> info = updateError(opts, info, net, res, speed)

The code get into the section:

>case 'binary'
>    error = bsxfun(@times, predictions, labels) < 0 ;
>   info.error(end) = info.error(end) + sum(error(:))/n ;

Rather than evaluate the error in **multiclass** section, the **binary** error computation is to count the number of **predictions** that are different from the ground truth **labels**. Then, I got a large error number (10,000) in each epoch (even it may decreases a little). I am not sure if this is a bug or this is the error values for binary classification?

**Comment by lenck** [comment]
Hi, based on the way how the error is computed:
```
error = bsxfun(@times, predictions, labels) < 0 ;
```
I would assume that it expects labels to be +-1, so that when you have correct classification, the result of this multiplication is positive (I guess this should have been more documented in the `cnn_train.m` example).

**Comment by luzhi** [comment]
@lenck Thanks for your suggestion! Yes, that works. :)
