### ISSUE TITLE
  net = insertBnorm(net, 1) ;

### ISSUE THREAD

**Issue by aysegulucar2016** [vlfeat/matconvnet#481]
On mnist example, I did not understand batch nomalization .

Why did we use 1,4,7? 
 net = insertBnorm(net, 1) ;
 net = insertBnorm(net, 4 );
 net = insertBnorm(net, 7) ;

**Comment by albanie** [comment]
The second argument to the insertBnorm function specifies the index of the convolutional layer that you want to insert a Bnorm layer *after*.  In the mnist example, the Bnorm layers are inserted directly after the first three convolution layers, which have layer indices 1, 3 and 5.  

Once the first function call `net = insertBnorm(net, 1) ;`  has completed, you have inserted a Bnorm layer at index 2 in the network so the convolution layer indices change from 1,3,5 to 1,4,6 as the layers after the Bnorm are shifted along by one.

Next you call `net = insertBnorm(net, 4 );`  which adds a second Bnorm layer at index 5.  After this, the convolution layer indices change from 1,4,6 to 1,4,7  so the final Bnorm layer is inserted after layer 7.

**Comment by aysegulucar2016** [comment]
Many thanks for your explanation.
