### ISSUE TITLE
k-fold cross validation in matconvnet

### ISSUE THREAD

**Issue by lyltencent** [vlfeat/matconvnet#482]
Hi, 

I am just wondering if anyone has done k-fold cross validation using maconvnet. I know in cnn_train, we can create one set of training and testing for the dataset, and then apply the function for calculating the training and testing error. How to do it using k-fold, do I need to run cnn_train k times and feed in different data at different time ? Has any one done this before? Any suggestions would be helpful. 

Thanks,

**Comment by bazilas** [comment]
Performing K-fold cross validation implies that you will have to train several times. There is no reason to have inside the cnn_train. You could create another script in which are set the training / validation data (i.e. imdb database) and iteratively are executed different trainings.
