### ISSUE TITLE
Reference to non-existent field 'opts'

### ISSUE THREAD

**Issue by colin700** [vlfeat/matconvnet#487]
Hi, I have already pass the test of matconvnet through the command
**`vl_testnn('gpu', true)`**
and the result is :  **2784 Passed, 0 Failed, 0 Incomplete.**

However , when I run a simple program 
I receive the following Error message:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Reference to non-existent field 'opts'.
Error in vl_simplenn (line 291)
        l.opts{:}, ...
Error in test_net (line 14)
  	res = vl_simplenn(net, data);

Error in run (line 96)
evalin('caller', [script ';']);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
any advice would be greatly appreciated !!
※My configurations are:
1. Cuda 7.5
2. Matlab 2016a
3. Visual studio 2010

**Comment by colin700** [comment]
I have tried to add
`net = vl_simplenn_tidy(net);`
into my project , but it didn't fix the error

**Comment by iqbalnaved** [comment]
I have the same problem, seems like net.Layers{i}.opts has been deprecated, I have to drop back to an earlier version to get my code work. Any ideas which older version might work?

**Comment by vedaldi** [comment]
Hi, sorry for this. Can you let us know which layer is affecteD?

**Comment by iqbalnaved** [comment]
Sorry, can't exactly say which layer, I was trying to run a pre-trained network and stumbled into this problem. You can check the code here: http://6.869.csail.mit.edu/fa15/challenge/miniplacesCNN.zip

**Comment by iqbalnaved** [comment]
Just want to add that I get to make vl_simplenn working for refNet1-epoch-60.mat by performing the following:
- Commenting all params starting from "l.opts"s
- Delete all condition with "l.leak"s
- Delete all "lp.precious"s

**Comment by Saberm** [comment]
The problem is that, 'opts' is a independent variable, not a field of 'l' object. so this error says that there is no field 'opts' in 'l'.
I think if we write 'opts' instead of 'l.opts', so the problem will be solved.
But I don't know what is the main and true answer!

**Comment by shahabty** [comment]
I have the same problem 
I trained a network and tried to train it again.
my network is trained by matconvnet beta20 but when I tired to retrain it i faced this error  
Reference to non-existent field 'layers'

**Comment by wzm2256** [comment]
I still have this problem.

How do you solve this? roll back to beta16?
