### ISSUE TITLE
how error is compute

### ISSUE THREAD

**Issue by alevillard** [vlfeat/matconvnet#488]
Hi, during a training, or finetuning process I have the info about error and loss. First, I was  thinking that error was a number between 0 and 1, but finetuning more layers,  I have an error starting from more than one, so.. someone could explain this? thank you @vedaldi 

![image](https://cloud.githubusercontent.com/assets/18304893/14312738/e67e4142-fbed-11e5-8ebd-4e9d53bc16a6.png)

[net-train.pdf](https://github.com/vlfeat/matconvnet/files/206146/net-train.pdf)

**Comment by bazilas** [comment]
You can see the implementation of different error functions (which do not necessarily have range [0,1]), in   [https://github.com/vlfeat/matconvnet/blob/master/matlab/vl_nnloss.m](url).
