### ISSUE TITLE
imagenet_example cnn_train error

### ISSUE THREAD

**Issue by haruky** [vlfeat/matconvnet#494]
I have some errors about cnn_train.m line 159 when evaluate the imagenet-vgg-f.mat use the cnn_imagenet_evaluate.m.
The error code of Matlab as follows, 
"Index exceeds matrix dimensions."
error: cnn_train (line 159)
    info.(f).speed(epoch) = n / stats.(f)(1) * max(1, numGpus)

error: cnn_imagenet_evaluate (line 99)
[net, info] = trainfn(net, imdb, getBatchFn(opts, net.meta), ...

But, I don't know how correct it.

**Comment by lenck** [comment]
Hi, which version are you using?

**Comment by haruky** [comment]
Thank you, i tried master version and the master-scripts worked smoothly.
