### ISSUE TITLE
Question on how to integrate new ideas/methods/contributions into MatConvNet?

### ISSUE THREAD

**Issue by travesty82** [vlfeat/matconvnet#495]
Hello,
I am doing research on various parts of Convolutional Neural Networks. I wanted to implement stochastic pooling, as well as other types of pooling, into my CNN. Currently, MatConvNet only offers max and avg pooling. I wanted to know the best way to integrate other methods? 

I have previously written a script to deal with stochastic pooling, but I realize that this doesn't fit into the current structure of vl_simplenn. I wanted to take full advantage of the other aspects that are preset, and get the best performance. Do you have any examples of a CNN where a method is performed that still gives the user all of the functionality of cnn_train? 

I know I can call the layers individually via vl_nnconv, vl_nnrelu, etc, but I am unclear on how to integrate the rest of the functionality without creating a mess. Thank you for your help!

**Comment by lenck** [comment]
Hi, you can try to use the `custom` layers in simplenn. From the help string for the `vl_simplenn`:
```
%   Custom layer::
%     This can be used to specify custom layers.
%
%     - `layer.type` contains the string `'custom'`.
%     - `layer.forward` is  a function handle computing the block.
%     - `layer.backward` is a function handle computing the block derivative.
```
And here is [one example](https://github.com/vedaldi/practical-cnn-reg/blob/master/addCustomLossLayer.m) how to use it...

For DagNN you can always implement your own layer...

**Comment by travesty82** [comment]
This helps somewhat. I will look at using the custom layer, and follow the example given. However...

I was looking for an example that corresponds with a simple, real method from a paper perhaps, or just something that you all didn't offer. That way I can see how this functionality (custom layer) is modified for new ideas. That way I have a model of how to implement the algorithm, forward pass and back pass in an acceptable format for MatConvNet. I did figure some things out based on looking at the existing code. I just wanted a verifiable, existing example so that my progress is faster.

If anyone has an example from their own experience that they're willing to share, it would be much appreciated. Thank you!

**Comment by lenck** [comment]
I'm not sure if I fully understand your point. The tutorial from which the example is given is actually about designing a new layer and how to numerically verify it. The tutorial is designed in a way that helps to understand the process step by step.

If you are looking for some more dedicated project, you can look e.g. on [this one](https://github.com/Relja/netvlad). It is a nice example of several, more complicated custom layers for simplenn.

**Comment by travesty82** [comment]
Okay I see it now. The link you provided helps immensely. I also didn't initially see the exercise connected to the custom layer, so pardon my disconnect. Thank you!
