### ISSUE TITLE
Practical issue Gpu matconvnet

### ISSUE THREAD

**Issue by alevillard** [vlfeat/matconvnet#502]
Hi, and thank you for the attention. I'm writing a thesis using Matconvnet, and I would like to know better how Matconvnet uses GPUs, how it take images, if there's a partecipation of cpu in a training process using gpu and how, when,  how works a multiple gpus, so it is how the computation of a neural network works in practice in software and hardware..  I know, it can be a little annoying to reply. if you have some documentation to suggest please let me know. Thank you

**Comment by lenck** [comment]
Hi, this question would surely feel much better on the discussion forum than here, as it is not really an issue :)
Some answers to your questions you can find in the [manual](http://www.vlfeat.org/matconvnet/matconvnet-manual.pdf) but for the rest you would have to study the source code. However the organization of the source code should not be that hard as the `simplenn` wrapper is quite straightforward. And, from my experience, you learn the most when trying to understand the source code...
Good luck with your thesis!
