### ISSUE TITLE
varying error rates by the number of testing images

### ISSUE THREAD

**Issue by cwr8401** [vlfeat/matconvnet#506]
Hi, 

I have found useful information from here and I think I finally succeeded to train a binary classifier recorded 0.059 in validation. But, I have a problem in testing.

I simply switched the last layer to the same as the last layer of  "vgg-face", and I fed images into the trained CNN. 

The problem is the trained CNN recorded about 0.5 error rates when I fed single images at a time, but when I fed many images at a time (about 50 images), it seems fine.

Could you please tell me why error rates are affected by the number of testing images?

Thank you so much.

**Comment by lenck** [comment]
Are you using batchNormalization layer in your network? If so, then you have to disable it when passing a single image as the mean and variance computed from a single image is usually quite wrong...

**Comment by cwr8401** [comment]
WOW. It works.
You are the BEST. Thank you so much for your instant comment!!!!!!!!!!

**Comment by lenck** [comment]
I hope it's OK that I will close this issue...
