### ISSUE TITLE
Try to use gpu for matconv but... my matlab version is 2015a

### ISSUE THREAD

**Issue by menglin0320** [vlfeat/matconvnet#507]
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
Building with 'Microsoft Visual C++ 2013 Professional'.
MEX completed successfully.
nvcc fatal   : nvcc cannot find a supported version of Microsoft Visual Studio. Only the versions 2010, 2012, and 2013 are supported 
Error using vl_compilenn>nvcc_compile (line 371)
Command "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc" -c
"C:\Users\menglin\Desktop\sp2016_courses\543\mp4\computer_vision_MP\matconvnet\matlab\src\bits\im2col_gpu.cu"
-gencode=arch=compute_20,code=\"sm_20,compute_20\" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -DENABLE_GPU
-I"C:\Program Files\MATLAB\R2015a\extern\include" -I"C:\Program
Files\MATLAB\R2015a\toolbox\distcomp\gpu\extern\include" -O3 -DNDEBUG  -Xcompiler  /MD -o
"C:\Users\menglin\Desktop\sp2016_courses\543\mp4\computer_vision_MP\matconvnet\matlab\mex\.build\im2col_gpu.obj"
failed.

Error in vl_compilenn (line 284)
      cuobj_files = nvcc_compile(opts, cu_src, bld_dir, nvcc_opts);

Error in setup (line 22)
    vl_compilenn('enableGpu', opts.useGpu, 'verbose', opts.verbose,'cudaRoot', 'C:\Program Files\NVIDIA GPU
    Computing Toolkit\CUDA\v7.5') ;

**Comment by menglin0320** [comment]
@alevillard

**Comment by alevillard** [comment]
?? why you have cited me? :) I use matlab2015b for the gpu, and matlab 2015a works only cpu in the server I used.

**Comment by lenck** [comment]
Hi, maybe you have multiple versions of Visual Studio installed and the nvcc finds only the newer one? You can try [this SO question](http://stackoverflow.com/questions/2760374/why-cant-nvcc-find-my-visual-c-installation) to force nvcc to use the correct one... But it's more a Matlab or `nvcc` problem, not MatConvNet, unfortunately :P
Another thing you may try is to try to compile with arguments `'CudaMethod', 'mex'` and see if Mathworks configuration would work...

**Comment by anewlearner** [comment]
Make sure vc\bin\amd64 is in you path.

**Comment by menglin0320** [comment]
Thanks very much guys. But I found out that matconv with gpu would not work on my laptop because my gpu doesn't support cuda.
