### ISSUE TITLE
different scores and testing errors for the same images

### ISSUE THREAD

**Issue by alevillard** [vlfeat/matconvnet#512]
Hi, it's some time that I notice that the accuracy in a prediction is not the same making more test for the same database and same network. This is an example in which my network first evaluate correctly 2 of three images,
 and making again the test, it will evaluate 3/3 in a correct way, someone could explain this? I know maybe it can be a problem of numeric truncation during calculus in matlab, but I think that 32 bit it's enought as precision. someone knows what happen?

![eval1](https://cloud.githubusercontent.com/assets/18304893/14680402/7ceeeb88-071d-11e6-8b39-e9d8bee0b1c0.jpg)

![eval2](https://cloud.githubusercontent.com/assets/18304893/14680409/874352b8-071d-11e6-8a5f-ff426cdfa2d3.jpg)

**Comment by lenck** [comment]
Hi, make sure that your network is in the `test` mode, if it contains dropout... Just a first idea :)

**Comment by alevillard** [comment]
Ok! it was that! Thank you a lot for the precious answer @lenck

**Comment by MichaelLiang12** [comment]
You may need the codes below to test model with BN layer or dropout layer
``` matlab
res = [];
dzdy = [] ;
res = vl_simplenn(net, im_, dzdy, res,  'mode', 'test' ) ;
```
