### ISSUE TITLE
enable "gpus" training option

### ISSUE THREAD

**Issue by aapocketz** [vlfeat/matconvnet#522]
in cnn_mnist/cnn_cifar/cnn_imagenet there is a option value to enable gpus, opts.train.gpus. It appears to error if I try to run the code such as 

`cnn_mnist('gpus', 1);`

I think there is an issue with vl_argparse.

`opts = vl_argparse(opts, varargin) ;
if ~isfield(opts.train, 'gpus'), opts.train.gpus = []; end;`

Firstly, it doesn't appear we set a default value for opts.train.gpus prior to entering vl_argparse, so it will not see it as a valid option. Secondly, if you add a default value, it doesn't appear to properly parse into the recursive substructure before declaring the parameter invalid.

Here is a simple example code that shows this issue in vl_argparse.

```
K>> opts.dummy = 1

opts = 

    dummy: 1

K>> varargin = {'dummy', 2}

varargin = 

    'dummy'    [2]

K>> opts = vl_argparse(opts, varargin)

opts = 

    dummy: 2

K>> opts.train.gpus = []

opts = 

    dummy: 2
    train: [1x1 struct]

K>> varargin = {'gpus', 1}

varargin = 

    'gpus'    [1]

K>> opts = vl_argparse(opts, varargin)
Error using vl_argparse (line 99)
Unknown parameter 'gpus'
 
99        error('Unknown parameter ''%s''', param) ;
K>> 
```

I am not sure what the intended behavior is supposed to be. If you set train to be a struct, it does replace the entire struct as noted in the help doc.

```
>> trainStruct.gpus = 5;
>> varargin = {'train', trainStruct};
>> opts = vl_argparse(opts, varargin);
>> opts.train

ans = 

    gpus: 5

>> 
```

**Comment by lenck** [comment]
Yeah, that's intended behaviour... If you want to set up the GPU, you need to call (a bit clumsily):
```
cnn_mnist('train', struct('gpus', 1));
```

**Comment by aapocketz** [comment]
Ok understood, that is what I ended up doing, but didn't think that was the intended behavior given the whole recursive feature, and the fact you wouldn't be able to chain options with that method. Thanks!

**Comment by lenck** [comment]
You are, only you have to keep the nested structure of the options. If you would allow the options to propagate down to the nested structures, you may end up with conflicts which would behave erratically based on the order of the structure fields...
