### ISSUE TITLE
Theoretical error in cnn_cifar.m and cnn_mnist.m

### ISSUE THREAD

**Issue by eakbas** [vlfeat/matconvnet#53]
In cnn_cifarr.m:115 and cnn_mnist.m:70, the mean of the data should be taken over the training examples only. Currently, it is taken over all set, i.e. training, validation, and testing.

**Comment by bazilas** [comment]
Right. Calculating the mean from the whole dataset (train + validation) brings better results. I have seen it for my problems ;)

It could be nice to fix it for the next version, because we often start writing scripts by modifying the given examples.

**Comment by lenck** [comment]
Hi, thanks for pointing this out!
