### ISSUE TITLE
number of filters

### ISSUE THREAD

**Issue by amar2015** [vlfeat/matconvnet#54]
Some times when I change the number of the filters I have this error:

learning rate changed (0.000000 --> 0.001000): resetting momentum
training: epoch 01: processing batch   1 of  22 ...Error using vl_nnconv
The number of filter groups does not divide the total number of filters.

Error in vl_simplenn (line 153)
      res(i+1).x = vl_nnconv(res(i).x, l.filters, l.biases, 'pad', l.pad, 'stride', l.stride) ;

Error in cnn_train (line 140)
    res = vl_simplenn(net, im, one, res, ...

Error in cnn_pollen (line 158)
[net, info] = cnn_train(net, imdb, @getBatch, ...
 
I just want to understand, why does that happen?

**Comment by lenck** [comment]
Hi, I was just describing this recently in issue #50, but feel free to ask if something wouldn't be clear... :)

**Comment by amar2015** [comment]
thanks a lot. So if I have H x W x D x N features maps I should select the filter banks Fh x Fw x D x K and this always gives me result of Yh x Yw x K x N.

**Comment by lenck** [comment]
Yes, exactly :) Assuming that you don't want to use the 'group' functionality, in which case you can have filters of size Fh x Fw x D\n x K where n is an integer number...

**Comment by amar2015** [comment]
OK, thanks a lot.

**Comment by Cisy** [comment]
Hi, I encountered the same problem. But I checked my net and didn't find anything wrong. Here is my net. I'm wondering what is wrong here. Thanks a lot.


>> vl_simplenn_display(net)
     layer|      1|      2|      3|      4|      5|      6|      7|      8|      9|     10|     11|     12|     13|     14|     15|     16|     17|     18|     19|     20|     21|
      type|    cnv|   relu|    nrm|  mpool|    cnv|   relu|    nrm|  mpool|    cnv|   relu|    cnv|   relu|    cnv|   relu|  mpool|    cnv|   relu|    cnv|   relu|    cnv|   sftm|
   support|  11x11|    1x1|    1x1|    3x3|    5x5|    1x1|    1x1|    3x3|    3x3|    1x1|    3x3|    1x1|    3x3|    1x1|    3x3|    6x6|    1x1|    1x1|    1x1|    1x1|    1x1|
    stride|      4|      1|      1|      2|      1|      1|      1|      2|      1|      1|      1|      1|      1|      1|      2|      1|      1|      1|      1|      1|      1|
       pad|      0|      0|      0|0,1x0,1|      2|      0|      0|      0|      1|      0|      1|      0|      1|      0|      0|      0|      0|      0|      0|      0|      0|
   out dim|     64|     64|     64|     64|    256|    256|    256|    256|    256|    256|    256|    256|    256|    256|    256|   4096|   4096|   4096|   4096|    250|    250|
  filt dim|      1|    n/a|    n/a|    n/a|     64|    n/a|    n/a|    n/a|    256|    n/a|    256|    n/a|    256|    n/a|    n/a|    256|    n/a|   4096|    n/a|   4096|    n/a|
rec. field|     11|     11|     11|     19|     51|     51|     51|     67|     99|     99|    131|    131|    163|    163|    195|    355|    355|    355|    355|    355|    355|
c/g net KB|   31/0|    0/0|    0/0|    0/0| 1601/0|    0/0|    0/0|    0/0| 2305/0|    0/0| 2305/0|    0/0| 2305/0|    0/0|    0/0|147472/0|    0/0|65552/0|    0/0| 4001/0|    0/0|
total network CPU/GPU memory: 221.4/0 MB
