### ISSUE TITLE
vl_simplenn_tidy overwrites fields if the layer is a class

### ISSUE THREAD

**Issue by Relja** [vlfeat/matconvnet#552]
`vl_simplenn_tidy` doesn't work properly when one uses a custom layer implemented as a class, as it overwrites `weights`, `name` and `precious`. The two problems are:

```
if ~isfield(layer, 'weights')
  layer.weights = {} ;
end
```

and

```
if ~isfield(layer, defaults{i})
  layer.(defaults{i}) = defaults{i+1} ;
end
```

For layers which are classes, `isfield` returns false, so even if the layer has weights/name/precious set, they will be overwritten. One solution is to check for `isprop`:

```
if ~isfield(layer, 'weights') && ~isprop(layer, 'weights')
if ~isfield(layer, defaults{i}) && ~isprop(layer, defaults{i})
```

It doesn't fully solve the problem as is `weights` is not a property, then setting it in the following line will fail, though I guess it should fail (maybe more elegantly with a good error message) if having the `weights` property/field is required.

As a side note, one annoying thing about `vl_simplenn_tidy` combined with classes is that any updates to extra fields that `vl_simplenn_tidy` wants (e.g. the requirement that each layer should have `weights`) break the code (one needs to change the class definition to contain the `weights` property). Maybe the function should explicitly skip class layers or custom layers all together, as `vl_simplenn` shouldn't care about their implementation since the interface between that function is only through the forward and backward functions implemented by the layer (though it's not as black and white as that due to the `precious` parameter..).

**Comment by lenck** [comment]
Hi, sorry that it took so long to fix this issue. Is the submitted patch solving the issue for you?

I thought that it would be more reasonable just to ignore all custom layers, as we cannot assume anything about them. The built-in layers are always structures, so there is no reason to check for the properties, and if somebody would like to implement a custom convolution, it can easily be done with a custom layer too...

**Comment by Relja** [comment]
Hi, no problem - yes, all works fine, thanks!
Yes I agree, I think this is the best way to handle it (i.e. not touch custom layers)

**Comment by Relja** [comment]
Hi,
Unfortunately this issue has reappeared, presumably due to: https://github.com/vlfeat/matconvnet/commit/b0a1cf72026422d867a536f92f4efa6e74c2efa0

**Comment by lenck** [comment]
Hi, sorry for reintroduction of this issue. It was clearly a miscommunication...
