### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by raphaeli** [vlfeat/matconvnet#56]
Is there an easy way to add online data augmentation in the code?
basic staff rotations, flipping, shifting etc.
I would appreciate some help in pinpointing the file+ appropriate lines

**Comment by vedaldi** [comment]
Yes, it is definitely possible, and in fact quite easy. If you want to use the example training code (cnn_train) you just have to modify the getBatch function to apply your transformation. However, be careful as this can easily become the computational bottleneck if not implemented very efficiently.

**Comment by ByungtaeAhn** [comment]
@vedaldi 

Hi Vedaldi,
I've modified the 'getBatch' function for data augmentation like below. However, I'm get stuck in a GPU memory problem, even with a small number of augmentation! Could you give me some advises and tips to handle that issue for data augmentation? Thanks!


% --------------------------------------------------------------------
function [im, labels] = getBatch(imdb, batch)
% --------------------------------------------------------------------
im = imdb.images.data(:,:,:,batch) ;

% Data augmentation (crop and scale change)
% image size = 140
n_aug = 4; % # of augmentation
Data_aug = gpuArray(single(zeros(140,140,3,size(im,4)*n_aug)));
lb_aug = zeros(size(imdb.images.labels,1),size(im,4)*n_aug);
for i=1:size(im,4)
    for j=1:n_aug/2
        rnd_x = round(rand*11)+1; rnd_y = round(rand*11)+1;
        Data_aug(:,:,:,(i-1)*n_aug+j) = im(rnd_y:rnd_y+139,rnd_x:rnd_x+139,:,i);
    end
    for j=n_aug/2+1:n_aug
        rnd_x = round(rand*5)+1; rnd_y = round(rand*5)+1;
        Data_aug(:,:,:,(i-1)*n_aug+j) = imresize(im(rnd_y:rnd_y+145,rnd_x:rnd_x+145,:,i), 140/146);
    end
    
    for j=1:n_aug
        lb_aug(:,(i-1)*n_aug+j) = imdb.images.labels(:,batch(i));
    end
end

% Randomize sequence of DB
rnd_idx = randperm(size(Data_aug,4));
Data_rnd = gpuArray(single(zeros(140,140,3,size(Data_aug,4))));
lb_rnd = zeros(size(lb_aug,1),size(lb_aug,2));
for i=1:size(Data_aug,4)
    Data_rnd(:,:,:,i) = Data_aug(:,:,:,rnd_idx(i));
    lb_rnd(:,i) = lb_aug(:,rnd_idx(i));
end

im = Data_rnd;
im = bsxfun(@minus, imresize(im, 1.6), ...
    imresize(imdb.images.data_mean, 224/151) ) ;
labels = lb_rnd;

**Comment by dteney** [comment]
Hi @ByungtaeAhn
There's no need to randomize the elements in getBatch, the SGD implementation provided already does so for you. It looks like your few lines of code for that would duplicate the data while rearranging it, so that's where you may overflow the memory.

**Comment by jellyzhang** [comment]
Hi, @vedaldi , could you open some codes about common practice in data augmentation?
