### ISSUE TITLE
MNIST for two classes

### ISSUE THREAD

**Issue by anselmoferreira** [vlfeat/matconvnet#566]
Is it possible to make MNIST example in matconvnet to work for two classes instead of 10? I changed the cnn_mnist_init.m file to be the following to generate feature vectors for two classes:

```
**net.layers{end+1} = struct('type', 'conv', ...
                       'weights', {{f*randn(1,1,500,2, 'single'), zeros(1,2,'single')}}, ...
                       'stride', 1, ...
                       'pad', 0) ;**
```

But when I run cnn_train I have the following error:

```
**Error in cnn_train>error_multiclass (line 222)
err(2,1) = sum(sum(sum(min(error(:,:,1:5,:),[],3)))) ;

Error in cnn_train>process_epoch (line 302)
error = sum([error, [...

Error in cnn_train (line 153)
[net, stats.train] = process_epoch(opts, getBatch, epoch, train, learningRate, imdb, net) ;

Error in original_image (line 40)
[net, info] = cnn_train(fold, net, imdb, @getBatch, ...

Error in main_original (line 13)
[imdb, net, info] = original_image(fold);**
```

**Comment by enveraydin** [comment]
Possible change opts.errorFunction = 'multiclass'    to      opts.errorFunction = 'binary' ;

**Comment by anselmoferreira** [comment]
I did what you asked (thank you so much) but now the error changed:

    training: epoch 01: batch   1/255: Subscript indices must either be real positive integers or logicals.
    Error in vl_nnsoftmaxloss (line 60)
    t = Xmax + log(sum(ex,3)) - reshape(X(c_), [sz(1:2) 1 sz(4)]) ;
    Error in vl_simplenn (line 191)
    res(i+1).x = vl_nnsoftmaxloss(res(i).x, l.class) ;
    Error in cnn_train>process_epoch (line 291)
    res = vl_simplenn(net, im, dzdy, res, ...
    Error in cnn_train (line 153)
    [net, stats.train] = process_epoch(opts, getBatch, epoch, train, learningRate, imdb, net) ;
    Error in original_image (line 40)
    [net, info] = cnn_train(fold, net, imdb, @getBatch, ...

    Error in main_original (line 13)
    [imdb, net, info] = original_image(fold);
  
    t = Xmax + log(sum(ex,3)) - reshape(X(c_), [sz(1:2) 1 sz(4)]) ;

My y1, y2, x1 and x1 have the following sizes:

          y1=(1,25420)
          y2=(1,9540)
          x1=(28,28,25420)
          x2=(28,28,9540)

What can be happening?

**Comment by luzhi** [comment]
Hi @anselmoferreira , if you are using the error function "_multiclass_" and _softmaxloss.m_ as the loss function, that would be better using the label 0,1,2, ...

**Comment by anselmoferreira** [comment]
Hi everybody,

firstly thank you for your answers so far. 

I did all you asked:

     1- change opts.errorFunction = 'multiclass' to opts.errorFunction = 'binary' ;
     2- I am labelling classes as 1 and 2
     3- The last but one layer in the cnn_mnist_init.m is as follows to consider 2 classes instead of 10

     net.layers{end+1} = struct('type', 'conv', ...
                           'weights', {{f*randn(1,1,500,2, 'single'), zeros(1,2,'single')}}, ...
                           'stride', 1, ...
                           'pad', 0) ; 

Now the error changes to:

    training: epoch 01: batch   1/255: Undefined function 'error_binary' for input arguments of type    'struct'.

     Error in cnn_train>process_epoch (line 321)
     error = sum([error, [...

     Error in cnn_train (line 153)
     [net, stats.train, prediction_vector, score_vector] = process_epoch(opts,
     getBatch, epoch, train, learningRate, imdb, net, prediction_vector,
     score_vector) ;

     Error in original_image_scale1 (line 30)
     [net, info] = cnn_train(net, imdb, @getBatch, ...

**Comment by agpoyraz** [comment]
Did you change your labels in your data.mat file (imdb file)?

**Comment by Addhi86** [comment]
@anselmoferreira 
I am doing binary classification and following MINST example for my own dataset.
i am getting error. 
Can you please tell em how can i change this
`opts.errorFunction = 'multiclass' to opts.errorFunction = 'binary' ;`
