### ISSUE TITLE
cnn_train_dag example syntax error

### ISSUE THREAD

**Issue by omair-kg** [vlfeat/matconvnet#568]
In the cnn_train_dag wrapper in the accumulate_gradients function there is a syntax error in the switch statement (line 288). 

```
  switch net.params(p).trainMethod

    case 'average' % mainly for batch normalization
   ...
    case 'gradient'
   ...
    case 'otherwise'
    ...
  end
```
Instead of case 'otherwise' it should be just 'otherwise'. I found out the hard way when my own training method was overwritten and the error wasn't caught since the switch was looking for otherwise as a case.

**Comment by lenck** [comment]
Good point :) Thanks for spotting this...
