### ISSUE TITLE
Sliding Windows/ NMS

### ISSUE THREAD

**Issue by res97** [vlfeat/matconvnet#57]
Hi, I was wondering that is there any facility available in VLfeat matconvnet for sliding window and NMS, or should I code it by myself?

**Comment by luzhi** [comment]
Hi, I think there is no functions to generate sliding windows or patches in MatConvNet. Maybe you need to code it yourself.

**Comment by vedaldi** [comment]
Yes, there is no such function yet. However, note that all functions are convolutional (there are no “fully connected” layers as such, just larger convolutions), so in practice you get part of that for free.
