### ISSUE TITLE
What is the functionality of the parameter "conserveMemory" in function cnn_train(...)?

### ISSUE THREAD

**Issue by luzhi** [vlfeat/matconvnet#58]
In the example of ImageNet, I find there is an input parameter "conserveMemory" to the function cnn_train(...), which is written like this:

> [net,info] = cnn_train(net, imdb, fn, opts.train, 'conserveMemory', true) ;

Can I please ask what the affect of this parameter to the training performance in terms of speed and accuracy? Thanks!

**Comment by lenck** [comment]
Hi, you are right, this is not documented :)
What it does is that when enabled, it releases the res(_).x buffers when they are not needed (e.g. in forward pass directly after the data were processed by the next layer, in backward pass after the dzdx were computed).
And the influence to the speed - it really depends, basically this should save some memory, so it may also speed-up the matlab memory allocator. But I haven't done any extensive experiments with it myself...

**Comment by luzhi** [comment]
Hi @lenck , got it. Thanks a lot! :)
