### ISSUE TITLE
Dense last layer

### ISSUE THREAD

**Issue by dteney** [vlfeat/matconvnet#60]
I'm trying to implement a CNN where the output is a dense regression, e.g. a single value for each pixel of the input (or a downsized version of it). At some point I have a fully connected layer, with 1x1x4096 dimension data, which thus need to be expanded to hxwx1. What's the correct way to implement this with the available blocks ? I tried a conv. layer initialized in the following way, but it does not expand the data to hxw.

net.layers{end+1} = struct('type', 'conv', ...
                             'filters', 0.01 * randn(round(h),round(w),4096,1,'single'),...
                             'biases', zeros(1, 1, 'single'), ...
                             'stride', 1, ...
                             'pad', [floor(h/2) ceil(h/2) floor(w/2) ceil(w/2)], ...

Would it be reasonable to implement an "upsampling" layer that just expand (replicate) the 1x1x4096 to hxwx4096, and then apply the last one as above ?

**Comment by bazilas** [comment]
One way would be to reshape the output of the fully connected layer to the desired matrix output.

For instance, if you a have an input which is 128X128 and you would like to have half of it as output (64X64), you would need the last fully connected layer to output 4096 values. Then you would reshape the vector of 4096 elements to a 64X64 matrix.

To compare the predicted matrix with the ground-truth, you would need to modify the library and add your own cost function layer. For example, you could use a Mean Squared-Error distance between the predicted and the ground truth values. The ground-truth can be stored in the labels variable in a cell format.

**Comment by dteney** [comment]
Oh right, it's that simple ! Thanks, I guess I was looking for something too complicated.

For the ground truth labels, I don't think you need a cell array, the MatConvNet code already seems to handle matrices of labels of any size.

**Comment by demondan** [comment]
hello, can you tell me how to implement when the output is a dense regression? Thank you!
