### ISSUE TITLE
vl_compilenn documentation error

### ISSUE THREAD

**Issue by panovr** [vlfeat/matconvnet#603]
In "Installing and compiling the library" documentation part of matconvnet, the statement:

> Use vl_compilenn with the cudnnEnable,true option to compile the library; do not forget to use cudaMethod,nvcc as, at it is likely, the CUDA toolkit version is newer than MATLAB's CUDA toolkit. For example, on Mac this may look like:

`> vl_compilenn('enableGpu', true, ...
               'cudaRoot', '/Developer/NVIDIA/CUDA-7.5', ...
               'cudaMethod', 'nvcc', ...
               'enableCudnn', 'true', ...
               'cudnnRoot', 'local/cudnn-rc4') ;`

The parameter for 'enableCudnn' is 'true' (string), but this is incorrect, and it should be true (bool).

**Comment by lenck** [comment]
Fixed in 8905e5c, thanks!
