### ISSUE TITLE
Binary classification with softmaxloss.

### ISSUE THREAD

**Issue by luzhi** [vlfeat/matconvnet#61]
Hi,

I'm doing a binary classification, where the two categories are mutual exclusive. The CNN network is based on the one used in ImageNet, where I changed the number of classes from 1000 to 2. But I have no idea how to determine the class category for a testing image, because the output of the **softmaxloss** layer is a number. Do I need to set up a threshold? The classes labels are set as 1 for positives and 2 for negatives. Thanks!

**Comment by lenck** [comment]
Hi, if you want to get the classification, you should switch the `softmaxloss` for `softmax` which would have then the output of size [1 x 1 x NUM_CLASSES x NUM_EXAMPLES] and will be \in [0,1]...
Hope that this would help! :)

**Comment by luzhi** [comment]
Hi @lenck , thanks for your reply. Sorry for posting duplicate questions. Just one more question, can I use 1 and 2 as the labels, instead of 0 and 1? Thanks!

**Comment by lenck** [comment]
Hmm, I'm surprised that the [0,1] labels work for you, I thought that in softmax the labels are used for indexing, so it needs to be [1, 2]... But I may be wrong :)

**Comment by luzhi** [comment]
Hi @lenck , the labels I am using are 1 and 2, but I've got an error message when I change the "softmaxloss" to "softmax". Could you please have a look? Thank you very much!

> Array dimensions must match for binary array op.

>Error in vl_nnsoftmax (line 30)
>Y = Y .* bsxfun(@minus, dzdY, sum(dzdY .* Y, 3)) ;

>Error in vl_simplenn (line 211)
>        res(i).dzdx = vl_nnsoftmax(res(i).x, res(i+1).dzdx) ;

**Comment by luzhi** [comment]
Hi @lenck , sorry for that I misunderstand the meaning of [0,1] in your comments, which is actually a range. Thanks!

Can I use **softmaxloss** as the last layer when training, and use **softmax** when testing? Thanks!

**Comment by lenck** [comment]
Hi, sorry for late response. Yes, in general, for training you put a loss at top (some scalar which you optimise, therefore `softmaxloss` which is in fact two layers in one (we should try to sell it more ;))) and at testing time you are usually intrested in predictions, so you just use the `softmax`...

**Comment by luzhi** [comment]
@lenck Thanks for your help! Got it. :)
