### ISSUE TITLE
error from softmax loss

### ISSUE THREAD

**Issue by guanggz** [vlfeat/matconvnet#63]
Hi, when I modify the CIFAR example with other database, which include around 70 classes, an error was reported from `vl_softmaxloss.m`, saying

```
learning rate changed (0.000000 --> 0.001000): resetting momentum
training: epoch 01: processing batch   1 of 118 ...Index exceeds matrix dimensions.

Error in vl_nnsoftmaxloss (line 61)
  t = Xmax + log(sum(ex,3)) - reshape(X(c_), [sz(1:2) 1 sz(4)]) ;

Error in vl_simplenn (line 163)
      res(i+1).x = vl_nnsoftmaxloss(res(i).x, l.class) ;

Error in cnn_train (line 141)
    res = vl_simplenn(net, im, one, res, ...
```

I found that the max of `c_` is larger than 1000 and size(X) = [ 1 1 10 100].
In this case if e.g. 

```
c_( c_ > sz(1)*sz(2) * sz(3)*sz(4)) = max(size(X)) ;  % (or  = sz(1)*sz(2) * sz(3)*sz(4))
```

is added in line 57, this error can be avoided. 
I kept my `imdb` the same example, can some one help? Thanks!

**Comment by lenck** [comment]
Hi, this error is usally caused by wrong labels, From the size of `X` it seems that you have only 10 classes, so are all your labels between 1 and 10?

**Comment by guanggz** [comment]
@lenck Thanks!! Forgot to change the constant in net definition.

**Comment by ShasTheMass** [comment]
@guanggz (CC: @lenck), which constant precisely was that please? I keep getting the same "index exceeding matrix dim" issue. I have 16 labels, and my imdb data file is well structured - just as the ones in the MNIST and CIFAR examples - yet I can't find where the problem is.. or, is the net config not taking the number of classes automatically from the classes field in imdb.dat?
Your early attention will be highly appreciated.

**Comment by yalaudah** [comment]
@ShasTheMass Hi, were you able to figure out what the problem was? what constant requires changing to get rid of this error?

I have the same issue, and I've spent a lot of time trying to figure it out, but no luck.

@guanggz @lenck

**Comment by jvdsa** [comment]
Hello everyone,

I'm also getting the same error. Please someone post the solution.

Thanks in advance..

**Comment by FrankMN** [comment]
if dataset is changed, say if from 10 classes to 100 classes. Then in the cnn_cifar_init file, weights of last 2nd layer should be changed accordingly. 
from 
`{0.05*randn(1,1,64,10, 'single'), zeros(1,10,'single')}`
to 
`{0.05*randn(1,1,64,100, 'single'), zeros(1,100,'single')}`
