### ISSUE TITLE
v20 bug - iterations get slower with networks using dropout

### ISSUE THREAD

**Issue by mdflickner** [vlfeat/matconvnet#653]
Using v20,  networks using dropout take 0.3-0.4 sec per iteration at first, but become progressively slower. By 50000 iterations, it's almost 4 seconds per iteration, by 100 000 iterations it's over 12 seconds per iteration.  This is on a K40 gpu.  Running the same network using v18 doesn't lead to this issue.

**Comment by omair-kg** [comment]
refer  to issue [633](https://github.com/vlfeat/matconvnet/issues/633)

**Comment by mdflickner** [comment]
dup of 633
