### ISSUE TITLE
Could Matconvnet train two partially coupled linear ConvNets

### ISSUE THREAD

**Issue by yushuinanrong** [vlfeat/matconvnet#656]
Hi all,

I'm trying to implement the model proposed in section 5.2 of the paper:
http://arxiv.org/pdf/1601.04153v2.pdf
Basically, the model train two linear ConvNets simultaneously which share certain number of filters in each convolutional layer. I don't know if this is possible to do in Matconvnet.
Any idea is greatly appreciated. 

Thanks,
Jiawei

**Comment by Arstead** [comment]
hello, Do you find the way to train twi ConvNets with matconvent? 
I have same problem. I'm doing some research about multi-model recognition. I need to train an pair of ConvNets simultaneously.
Could your please tell me how to train two ConvNets with matconvent?

**Comment by yushuinanrong** [comment]
@Arstead 
Hi Arstead,

Just for the model I refered in the paper (http://arxiv.org/pdf/1601.04153v2.pdf), I feel like the coupled ConvNets is just you train one ConvNet for one epoch/iteration, and then pass a certain ratio of weights to another ConNet, back and forth. The paper claims by doing this the coupled ConvNet can learn a feature mapping between two kinds of input, meanwhile the unshared weights can still learn discriminative features for its specific input. 
I hope this helps.

Thanks,
Jiawei
