### ISSUE TITLE
How to obtain the predictions from DAGnn?

### ISSUE THREAD

**Issue by yushuinanrong** [vlfeat/matconvnet#658]
Hi all,

I want to get the predictions for each train/val samples. I make it work when using simplenn since the code 'cnn_train' is very clear and has the prediction variables inside. However, I feel a little bit difficult to get predictions from DAGnn. I'm pretty sure the predictions are computed somewhere but I cannot find it in cnn_train_dag.m
Any one can help?

Thanks

**Comment by yushuinanrong** [comment]
omg, I just realize I could simply pass any sample to a trained model to get the predictions.
I think this thread are good to close.

**Comment by fengyunxiaozi** [comment]
http://www.vlfeat.org/matconvnet/quick/ refer to this

**Comment by yushuinanrong** [comment]
@fengyunxiaozi 
Great!

Thanks

**Comment by hunterlew** [comment]
@yushuinanrong why can i only get the result in prediction layer?
