### ISSUE TITLE
How to concatenate two Pretrained Dagnn network?

### ISSUE THREAD

**Issue by yushuinanrong** [vlfeat/matconvnet#662]
Hi all,

I have two pretrained Dagnn network and I want to create a new network that fuse the two pretrained networks in fully connected layers. The fusion can be simply element-wise summation operation. 
I know how to define the structure from scratch. But if I want to utilize the pretrained weights, how should I do?

**Comment by yushuinanrong** [comment]
Update:
I tried to first define a dagnn network and then pass the pretrained prameters to the new network manually. It seems work now. But I'm still wondering if there is more smart way to do that.

**Comment by omair-kg** [comment]
One way that I'm doing it is by first giving the layers, parameters and variables in both networks unique names (so there is no conflict when they are merged). Afterwards I do this:

temp_1 = net._1saveobj();
temp_2 = net_2.saveobj();

temp.layers = [temp_1.layers temp_2.layers];
temp.params = [temp_1.params temp_2.params];
temp.vars = [temp_1.vars temp_2.vars];
temp.meta = temp_1.meta;

net = dagnn.DagNN.loadobj(temp);

**Comment by fengyunxiaozi** [comment]
@omair-kg it seems what he wants is Siamese network

**Comment by omair-kg** [comment]
In that case, follow the same procedure i.e. give unique names to all variables and layers except do not rename the parameters, in the merge step do the following:

temp_1 = net._1.saveobj();
temp_2 = net_2.saveobj();

temp.layers = [temp_1.layers temp_2.layers];
**temp.params = [temp_1.params];**
temp.vars = [temp_1.vars temp_2.vars];
temp.meta = temp_1.meta;

net = dagnn.DagNN.loadobj(temp);

The network parameters are then shared. Once fused then you can add the fully connected layer like you normally would.

**Comment by fengyunxiaozi** [comment]
@omair-kg I was trying implementing a Siamese network using simplenn wrapper. Your answer above will be helpful. Thanks!

**Comment by yushuinanrong** [comment]
@omair-kg 
Hi omair,

Thanks for your reply. Your answer is quite inspiring!

regards
jiawei

**Comment by Addhi86** [comment]
hello @yushuinanrong 
 I have completed designing the single architecture and successfully did training and testing on my dataset. After that, I am thinking to combine two architectures. is it possible to do that in MatConvNet?
like the output of first architecture of FC layer will be the input to the second layer of the second architecture.

**Comment by mkarimi1** [comment]
Hi i would like to concatenate FC layer of GoogleNet and  FC layer in Resnet
But there is a serious problem in backpropagation
Error in vl_taccum (line 19)
  a = vl_taccummex(alpha, a, beta, b) ;
I was wondering if you could help me to solve that.

**Comment by JiayongO-O** [comment]
> @omair-kg I was trying implementing a Siamese network using simplenn wrapper. Your answer above will be helpful. Thanks!

hi, have you completed implementing Siamese network using simplnn wrapper, or do you have any suggestions on the implementation, since I met the same problem recently. Thanks~

**Comment by JiayongO-O** [comment]
@fengyunxiaozi 
hi, have you completed implementing Siamese network using simplnn wrapper, or do you have any suggestions on the implementation, since I met the same problem recently. Thanks~

**Comment by iiwindii** [comment]
@JiayongO-O check here  https://github.com/lenck/siamese-mnist

**Comment by JiayongO-O** [comment]
@fengyunxiaozi 
very usefull reply, thank you very much. And I understand it. Thank you~
