### ISSUE TITLE
MatConvNet Training Gets Slower in Each Epoch

### ISSUE THREAD

**Issue by CaglarAytekin** [vlfeat/matconvnet#663]
Hi all,

I'm doing regression on Matconvnet. During training, each epoch processes slower and slower. Sometimes when an epoch is finished, in other epochs this slow down does not occur, but its totally random. I'm reading images from an SSD disk as suggested. I tried clearing the cache after processing each batch, tried switching prefetch, playing with the batch size, nothing works really. I'm using matconvnet beta 20, Matlab R2015b.

Any help much appreciated...

**Comment by omair-kg** [comment]
Please see issue [633](https://github.com/vlfeat/matconvnet/issues/633)
