### ISSUE TITLE
GpuDevice function's problem 

### ISSUE THREAD

**Issue by merobnma** [vlfeat/matconvnet#666]
when I run training function I have this problem 

cnn_train: resetting GPU
Error using gpuDevice (line 26)
An unexpected error occurred during CUDA execution. The CUDA error was:
all CUDA-capable devices are busy or unavailable

Error in cnn_train>prepareGPUs (line 576)
    gpuDevice(opts.gpus)

Error in cnn_train (line 116)
  prepareGPUs(opts, epoch == start+1) ;

Error in am_cnn_imagenet_amiranet_train (line 73)
[net, info] = trainFn(net, imdb, getBatchFn(opts, net.meta), ...

**Comment by fengyunxiaozi** [comment]
try to restart matlab and recompile matconvnet
