### ISSUE TITLE
Error in vl_simplenn_tidy (line 37)   layer = net.layers{l} ;

### ISSUE THREAD

**Issue by zhonhel** [vlfeat/matconvnet#669]
Hi everyone,

I tried to run the Quick start code. It ran successfully.
But when I changed the 'imagenet-vgg-f.mat' model to 'imagenet-resnet-152-dag.mat' model, it got error as below:
```
Cell contents reference from a non-cell array object.

Error in vl_simplenn_tidy (line 37)
  layer = net.layers{l} ;
```
How can it be solved?
Thank you very much!  : )

**Comment by fengyunxiaozi** [comment]
try the DAG wrapper instead of Simplenn wrapper. There is DAG model example in quick start.
By the way, you had better turn to google  discussion forum (https://groups.google.com/forum/#!forum/matconvnet) for such questions.

**Comment by preetivyas** [comment]
I am encountering the same issue and haven't found any considerable solution reading a lot of similar problems and discussion. If anyone has found the solution to it. Please let me know.
