### ISSUE TITLE
usage of errorbar function in vl_simplenn_diagnose

### ISSUE THREAD

**Issue by bazilas** [vlfeat/matconvnet#67]
The vl_simplenn_diagnose function plots: "the average, maximum, and miminum element for all the filters and biases in the network NET". This is done using the function errorbar.

For example:

errorbar(1:n, fmu, fmu, fmx, 'bo') ;

According to Matlab: "L and U contain the lower and upper error ranges for each point in Y. Each error bar is L(i) + U(i) long and is drawn a distance of U(i) above and L(i) below the points in (X,Y)."

This means that the function will plot the mean (fmu), the distance fmu below the mean and the distance fmx above the mean. As a result, the plot won't correspond to the min and max values, unless the mean is very close to 0.

In matlab 2014b (tested in ubuntu and osx), it should be written as:

errorbar(1:n, fmu, abs(fmi) + fmu, fmx - fmu, 'bo') 

OR in matlab 2014a (tested in windows) as:

errorbar(1:n, fmu, fmi-fmu, fmx-fmu, 'bo')

in order to show mean, min and max values.

The same update should apply to all errorbar() function calls in vl_simplenn_diagnose().

cheers,
Vasilis

**Comment by dteney** [comment]
Hi Vasilis,
I concur the original code was not correct, but why would it be different in Matlab 2014a and 2014b ?
Apparenty the 3rd/4th arguments can be positive or negative, matlab uses only their absolute value, but if you want to do it according to the doc and give positive values, you should do:

fmu(i) = mean(x(:)) ;
fmi(i) = min(x(:)) ;
fmx(i) = max(x(:)) ;
(...)
errorbar(1:n, fmu, fmu-fmi, fmx-fmu, 'bo') ;

**Comment by bazilas** [comment]
Hi Damien,

It's weird, but errorbar() gives different output for the same input in Matlab 2014a and 2014b.

We have executed with Felix (@felixachilles) errorbar() in different threes machines (ubuntu and osx with Matlab 2014b and windows with Matlab 2014a) and we have observed different output between Matlab 2014a and 2014b. Anyway, this is a matlab issue..

Vasilis

**Comment by dteney** [comment]
That's odd indeed. I can't test, but maybe you won't get different behaviors by sticking to the documented use, which is to give only *positive* numbers as 3rd/4th arguments, i.e.
errorbar(1:n, fmu, fmu-fmi, fmx-fmu, 'bo') ;

**Comment by lenck** [comment]
I think this can be considered as solved, as the `vl_simplenn_diagnose` has been deprecated.
