### ISSUE TITLE
How to handle large dataset like UCF101?

### ISSUE THREAD

**Issue by yushuinanrong** [vlfeat/matconvnet#671]
Hi all,

I'm facing a problem that Matlab cannot create a 'imdb.mat' file as input for the Matcovnet because of the memory issues.  UCF101 has more than 13000 videos and overall contains ~ 3M 240x320x3 images. I cannot create a imdb.file that aggregates all the preprocessed frames in matlab due to the limit of memory. Is there any hack can handle such problem?

regards,
Jiawei

**Comment by ankush-me** [comment]
You store the image data in files and only store the names of the image files in the imdb.
An example of this can be found in the script to create [imdb for ImageNet](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/cnn_imagenet_setup_data.m).

**Comment by yushuinanrong** [comment]
@vedaldi 

Thank you!
