### ISSUE TITLE
compilation error in windows

### ISSUE THREAD

**Issue by kalov** [vlfeat/matconvnet#678]
compiling matconvnet with Visual Studio 13 gives the error:
imread_helpers.hpp(523) : error C2589: illegal token on right side of '::'

Consider changing:
skip = std::min(skip, q) ;
=>
skip = std::min<int>(skip, q) ;

Read this for related information: http://stackoverflow.com/questions/5004858/stdmin-gives-error

**Comment by lenck** [comment]
Thanks for reporting this bug! And sorry that the Windows version was broken in this version.
