### ISSUE TITLE
Is there any Matlab version for pooling, convolution, and normalization?

### ISSUE THREAD

**Issue by johnny5550822** [vlfeat/matconvnet#68]
I found that pooling, convolution, and normalization layers are implemented in Cuda. Is there any Matlab version?

Thanks!

**Comment by mfigurnov** [comment]
I have ported the CPU version of vl_nnpool to MATLAB: https://gist.github.com/mfigurnov/2863e30ce3f73a473d32 . It mimics the C++ code, so there are lots of loops, and the performance is terrible.

**Comment by lenck** [comment]
@mfigurnov: Wow, so many fors :) 
Just out of curiosity, is there a reason why not to use the CPU implementation?

**Comment by mfigurnov** [comment]
@lenck Prototyping. I wanted to try several pooling schemes, and it's much faster when the pooling code is pure MATLAB.

**Comment by lenck** [comment]
Ah, I see...

**Comment by vedaldi** [comment]
It is indeed a sensible request to have a MATALB version of everything, no matter how slow. We may get to do so eventually, although the performance will likely be atrocious.

Thanks for sharing your code.
