### ISSUE TITLE
Issue with beta21

### ISSUE THREAD

**Issue by chenqifeng22** [vlfeat/matconvnet#682]
a) The version beta21 does not work with the mex compiler Visual Studio 2012. I need to modify three parts to make it work.

1. uncomment "#include<stdbool.h>" in mexutils.h
2. change "skip = std::min(skip, q) ;" to "skip = (std::min)(skip, q) ;" in imread_helpers.hpp
3. add "#define round(r) floor(r+0.5)" in vl_imreadjpeg.cu

b) However, there is a problem when running vl_nnconv in Windows:
Error using vl_nnconv
The option name is not a string (argument number 5)
Error in vl_simplenn (line 300)
      res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, ...
Error in cnn_train>processEpoch (line 316)
    res = vl_simplenn(net, im, dzdy, res, ...
Error in cnn_train (line 132)
    [net, state] = processEpoch(net, state, params, 'train') ;
Error in camvid_train_dilated (line 25)
net=cnn_train(net,imdb,@camvid_dilated_getBatch,trainOpts); 

c) Here is an issue with vl_tacc.m I fix:
if isscalar(a)
  a = alpha * a + beta * b ;
  return ;
elseif isa(a, 'gpuArray')
  vl_taccummex(alpha, a, beta, gpuArray(b), 'inplace') ;
else
  a = vl_taccummex(alpha, a, beta, gather(b)) ;
end

**Comment by lenck** [comment]
Hi, it should be fixed now in the master (it's not in the library distribution package yet).
