### ISSUE TITLE
protability problem ssize_t in mexutils.h

### ISSUE THREAD

**Issue by wszczw** [vlfeat/matconvnet#683]
Hi,

I found a portability problem with the vlmxIsString function in mexutils.h. 

When on Windows, the type ssize_t is defined as signed int, but in this function can be called with a -1 to bypass the length check . This causes to all the option arguments in functions to fail, because they are not recognized as strings (if called with a -1)

Cheers!
F

**Comment by chrirupp** [comment]
Hi F,
this was fixed yesterday: see #677.

**Comment by lenck** [comment]
Yeah, it's on Github master, not in the distribution package yet...
