### ISSUE TITLE
Re-train simplenn in cpu mode

### ISSUE THREAD

**Issue by brannonbarr** [vlfeat/matconvnet#684]
![image](https://cloud.githubusercontent.com/assets/22105123/18398831/741d9538-769c-11e6-8f75-9fe9afba3a1b.png)

**Comment by lenck** [comment]
Hi, are you sure you are passing an array and not a cell array? Just when the e.g. vl_nnconv is being called, the `class` of the input must be `single` or `double`...

**Comment by brannonbarr** [comment]
I was passing a cell array, thanks for your input.
