### ISSUE TITLE
Still some bugs

### ISSUE THREAD

**Issue by chenqifeng22** [vlfeat/matconvnet#688]
In Windows with visual studio 2012, I need to remove

#if defined(_MSC_VER) && _MSC_VER < 1800
#define false 0
#define true 1
#else
#include <stdbool.h>
#endif

Otherwise, the compiler will complain that redefinition of macro keywords.

In addition, I need to comment out %vl_tmove('reset') ; in cnn_train.m to make it work in Windows.

**Comment by lenck** [comment]
Hmm, that's strange, it worked for 2013... Unfortunately I don't have
2012... Msvc is so annoying... I can fix it on Wednesday the earliest...

**Comment by lenck** [comment]
Hi, should be fixed now in master. Can you check if it works?

I was not able to find a version of VS 2012 to test it myself, so it is more of a guess..

**Comment by chenqifeng22** [comment]
We can not include "stdbool.h" or #define false 0 in visual studio 2012. So latest version still complains that stdbool.h is not found. Please use these three lines 

```
#if !defined(_MSC_VER) || _MSC_VER >= 1800
#include <stdbool.h>
#endif
```

to replace

```
#if defined(_MSC_VER) && _MSC_VER < 1800
#define false 0
#define true 1
#else
#include <stdbool.h>
#endif
```

**Comment by lenck** [comment]
Ok, now it should works I hope ;) Bloody VS 2012 (had to install it at the end).

Thanks for the proposed change, however that would break the compilation for newer and older MSVC... It's such a mess with its C99 support...
