### ISSUE TITLE
WRONGLY LOADING the NET

### ISSUE THREAD

**Issue by uiyo** [vlfeat/matconvnet#690]
I have compiled the newest version of matconvnet, and downloaded your pretrained alex-net. After i commanded:

net=load('../models/imagenet-matconvnet-alex.mat');
res=vl_simplenn(net,img);

i got 
Cell contents reference from a non-cell array object.

Error in vl_simplenn (line 296)
  l = net.layers{i} ;

it seems the structure of the net does not match the function's
i modified the network by changing the layers from type stuct to cell but still got a lot of bugs, it is really  annoying and overwhelming to do such a useless job. In future, would you please modified the structure of the networks or just considering all the possibilities of the oldest version while changing the organization of the functions, please?

**Comment by uiyo** [comment]
Above all i would like to thank you for so an excellent job you have done.

**Comment by lenck** [comment]
Hi, it is inevitable that the interface changes as we discover that we have made mistakes in the past and we attempt to improve the overall functionality of the toolbox.
For backwards compatibility we provide the `vl_simplenn_tidy` function which converts models from the old interface to the new format.
