### ISSUE TITLE
vl_simplennwith gpu

### ISSUE THREAD

**Issue by JavierCoronel** [vlfeat/matconvnet#692]
Hi everyone,

I have already trained my network for a binary classification task. The network was trained on a gpu, and now I want to classify a huge amount of data. So I use `res = vl_simplenn(net, im_) ;`, the problem I have is that using cpu or gpu I get the same time for evaluation. Is there a way to use the gpu in the `vl_simplenn` to reduce the evaluation time?

thanks,

**Comment by chenqifeng22** [comment]
Which GPU are you using? If you use Titan X, you should see a significant improvement.

**Comment by JavierCoronel** [comment]
I've already solved it, I had to move the net to the gpu  `vl_simplenn_move()` and also the data `gpuArray(im_)`. The difference is really significant on a Tesla k20c.
