### ISSUE TITLE
error: vl_compilenn

### ISSUE THREAD

**Issue by Roboball** [vlfeat/matconvnet#693]
Hi I get an error  while running vl_compilenn.
Please help.

System: Win7x64, Matlab2013b, Matconvnet1.0beta20, Windows SDK 7.1+patch,Microsoft Visual C++ 2010 Redistributable Package (x64)

error message:
vl_compilenn:	CUDA: MEX config file: 'C:\Program Files\MATLAB\R2013b\toolbox\distcomp\gpu\extern\src\mex\win64\mex_CUDA_win64.sh'
pooling_cpu.cpp 
c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\intrin.h(26) : fatal error C1083: Cannot open include file: 'ammintrin.h': No such file or directory 
 
  C:\PROGRA~1\MATLAB\R2013B\BIN\MEX.PL: Error: Compile of 'C:\UsersDesktop\MatConvNet\matlab\src\bits\impl\pooling_cpu.cpp' failed. 
 
Unable to complete successfully.

Error in vl_compilenn>mex_compile (line 510)
mex(mopts{:}) ;

Error in vl_compilenn (line 471)
    mex_compile(opts, srcs{i}, objfile, flags.mexcc) ;

**Comment by lenck** [comment]
Hi, can you run it with `vl_compilenn(... 'verbose', 1)` or eventually with `vl_compilenn(... 'verbose', 2)`...

**Comment by Roboball** [comment]
hi ok everything re-installed and now `vl_compilenn()` as well as verbose,1 and 2 works.

However after compilation,  if I try to run `Y=vl_nnconv(x1, w1, 0);` , I get this error message:
**Attempt to execute SCRIPT vl_nnconv as a function:**
Now I follow these instructions, but I cannot find the mex directory in the path `matlab/toolbox/mex`:
Any idea??
http://www.vlfeat.org/matconvnet/faq/

**Comment by Roboball** [comment]
for version 1.0 beta21: vl_compilenn() or with verbose1 or 2 gives fatal error fatal error:

vl_nnconv.cpp 
C:\\matlab\matconvnet\matconvnet-1.0-beta21\matlab\src\bits/mexutils.h(19) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory 
 
  C:\PROGRA~1\MATLAB\R2013B\BIN\MEX.PL: Error: Compile of 'C:\Users\Documents\MATLAB\MatConvNet\matconvnet-1.0-beta21\matlab\src\vl_nnconv.cpp' failed. 
 
Unable to complete successfully.

Error in vl_compilenn>mex_compile (line 524)
mex(mopts{:}) ;

Error in vl_compilenn (line 485)
    mex_compile(opts, srcs{i}, objfile, flags.mexcc) ;

Error in run (line 63)
evalin('caller', [script ';']);

**Comment by Roboball** [comment]
ok version 20 works now. the reason seems that you have restart the system, before you can actually use the libary.
