### ISSUE TITLE
Does matconvent support distributed computing where the images of one batch are computed over several GPUs?

### ISSUE THREAD

**Issue by jstudy** [vlfeat/matconvnet#697]

**Comment by lenck** [comment]
Hi, yes, just add more gpu, e.g.:
```
cnn_imagenet_train('train', struct('gpus', [1, 2]))
```
To train on GPU 1 and 2. It splits the batch among them. MatConvNet does not support parallelisation over the model.

**Comment by lenck** [comment]
Duplicate to #128, #101.

**Comment by jacksonjack001** [comment]
how to specify a gpu, 
such as:
cnn_imagenet_train('train', struct('gpus', [0, 2]))
to use the second gpu?
