### ISSUE TITLE
problem in architecture of cnn_imagenet.m

### ISSUE THREAD

**Issue by aosokin** [vlfeat/matconvnet#70]
The output of Block 1 (lines 98 - 114) has 96 channels (as specified in line 99).
The conv layer of block 2 takes 48 channels as input (line 118).

Analogous situation happens between block 3 and 4.

The code works fine as is, but I could not find description of this behavior in documentation.
Is this a bug or undocumented feature?

**Comment by lenck** [comment]
Hi, this is the way how MatConvNet implements filter groups. For details you can see in the (pdf manual)[http://www.vlfeat.org/matconvnet/matconvnet-manual.pdf] in section 2.1 Convolution - Filter groups.

**Comment by aosokin** [comment]
I see, that makes it clear. Thanks.

**Comment by dteney** [comment]
Can I ask for a clarification on this implementation of filter groups ?
Does this mean that the block 2 is actually "duplicated", i.e. that we learn 2 sets of filters 5x5x48x256 ? If this makes allows to implement the "2 stream" architecture of Krizhevsky's paper, where/how are the two streams recombined ?

Thanks !

**Comment by aosokin** [comment]
In my opinion this is not the case. We learn 1 set of filters 5x5x48x256, but this set is applied twice, i.e. for the two different groups of channels coming from the previous layer.
The gradient update for the filters is accumulated from both sets of channels.
> If this allows to implement the "2 stream" architecture of Krizhevsky's paper
I guess this is not directly supported. To do this vl_simplenn.m needs to be modified.

**Comment by dteney** [comment]
Karel, could you confirm this, i.e. that the same filters are just applied twice on the two (or more) groups ??

**Comment by vedaldi** [comment]
Hi,

let me jump in on this one: the architecture should be the same as the multiple streams of AlexNet, just like in Caffe.

Call:

- ID the dimension (depth) of the input tensor
- OD the dimension of the output tensor
- FD the dimension of the filters

Then:

- the number of filters matches the number of output dimensions OD
- there are G = ID / FD groups
- the input tensor is split into G slices (each has ID/G=FD dimensions, matching the filters)
- the filters are split into G groups, each containing OD/G filters of dimensions FD

Each group of filter is applied to the corresponding slice of the input array, generating a corresponding slice of the output array.

So, *no, different filters are applied to different groups*. They are just packed in the same MATLAB array.

Best wishes,

Andrea

**Comment by aosokin** [comment]
Andrea, thanks for the explanation.

Damien, sorry for giving incorrect answer.

**Comment by dteney** [comment]
Thanks !!
