### ISSUE TITLE
Issue compiling CPU version on Windows

### ISSUE THREAD

**Issue by sginsburg** [vlfeat/matconvnet#702]
Hi,

I am trying to compile the CPU version of MatConvNet in Matlab 2015b on Windows 7.  I am using Microsoft Visual C++ 2013 Profession to compile.

Many of the files compile properly, but then I get the following error: 

Error using mex
vl_nnconv.obj : fatal error LNK1143: invalid or corrupt file: no symbol for COMDAT section 0x7

Error in vl_compilenn>mex_link (line 475)
mex(mopts{:}) ;

Error in vl_compilenn (line 427)
  mex_link(opts, objs, mex_dir, flags.link) ;

Please help me compile this library on my machine.  Thank you!

**Comment by oya163** [comment]
You have to select `mex setup -c` and `mex setup -c++` of the same type. This will at least reduce the mex link problem.

**Comment by sginsburg** [comment]
Yes, you are right.  This fixed my problem.  Thank you!
