### ISSUE TITLE
Installing issue with 1.0.9beta

### ISSUE THREAD

**Issue by xcyan** [vlfeat/matconvnet#72]
Hi, 

While running "vl_compilenn('verbose',1)", I got this error message:
In file included from matlab/src/bits/data.cpp:4:
matlab/src/bits/data.cu: In member function ‘void vl::Context::invalidateGpu()’:
matlab/src/bits/data.cu:193: error: invalid use of incomplete type ‘struct vl::CudaHelper’
matlab/src/bits/data.hpp:44: error: forward declaration of ‘struct vl::CudaHelper’

    mex: compile of ' "matlab/src/bits/data.cpp"' failed.

**Comment by vedaldi** [comment]
Tes, I just found this issue (applies only to CPU). I will push a patch shortly. Thanks.

**Comment by vedaldi** [comment]
It is now fixed. I moved the 1.0-beta9 tag to the patched version (sorry)
