### ISSUE TITLE
Can we use an image data without converting to idx3-ubyte format in cnn_train?

### ISSUE THREAD

**Issue by dhruvmullick** [vlfeat/matconvnet#720]
Will the results change if we don't use idx-ubyte format?

**Comment by albanie** [comment]
Hi @dhruvmullick, sorry for the slow response. All `vl_nn*` matconvnet operations work with the `single` data type (and from January 2016 onwards, also with the`double` data type).  If you are referring to the minst example, the downloaded data is converted to the `single` data format before it is used (you can see this conversion [here](https://github.com/vlfeat/matconvnet/blob/master/examples/mnist/cnn_mnist.m#L129)).

**Comment by dhruvmullick** [comment]
Hi @albanie, actually I was referring to [this code](https://github.com/vlfeat/matconvnet/blob/master/examples/mnist/cnn_mnist.m#L123). The labels are  in the format of idx-ubyte. I don't understand what to do in case I don't have the lables in that format. Can you please help me out?

**Comment by albanie** [comment]
Ah, that's actually just the name of the file (it's a little confusing). In the [next line](https://github.com/vlfeat/matconvnet/blob/master/examples/mnist/cnn_mnist.m#L124) you can see that the actual labels are read as `uint8`.  You can have your labels as `uint8`, but other formats will also work - it won't affect the loss layers.

**Comment by dhruvmullick** [comment]
Oh. Makes sense. I was wondering if ubyte was used to refer to uint8. 
Thank you!
