### ISSUE TITLE
how to evaluate cifar example?

### ISSUE THREAD

**Issue by micklexqg** [vlfeat/matconvnet#725]
Hi , guys!
in mnist, it is ok to directly run cnn_mnist_experiments.m, howerver there isn't the script in cifar, and i try to create one just like  cnn_mnist_experiments.m, but it doesn't work.
so how to valuate  the cifar example?

**Comment by micklexqg** [comment]
sorry for my poor english, the title should be how to implement cifar example?

**Comment by ahn19** [comment]
I agree with you. I also need the cifar evaluation example code.
