### ISSUE TITLE
Empty output feature vector for dagnn

### ISSUE THREAD

**Issue by dhruvmullick** [vlfeat/matconvnet#731]
I want to use the features output by the fully connected layer of a pre trained CNN which has 35 layers. (after removing the classifier layers). 

I tried to obtain the output of a layer say 35 using
features = net.vars.value(35);

However the problem is that net.vars.value returns an empty array for all layers after 31. Something to note is that the params is a 1x30 struct.

Note that I am using a pretrained cnn fast-rcnn-vgg16, and the following is the image depicting its structure:  

![screen shot 2016-10-16 at 1 29 35 am](https://cloud.githubusercontent.com/assets/7004024/19413290/64f7832c-9346-11e6-8a38-eb2fab53ee83.png)

**Comment by albanie** [comment]
By default, the features are dropped after computation to conserve memory.  However, you can keep them around in a couple of ways:

1. Set `net.conserveMemory = false` - this will store all feature maps after an evaluation of the network.
2. Set `net.vars(varIndexOfInterest).precious = true` where `varIndexOfInterest` is the index of the variable you would like to keep. This will preserve only the feature maps that you would like to keep.
