### ISSUE TITLE
Can I implement data loading and train computing  in parallel in matconvnet?

### ISSUE THREAD

**Issue by xhhong** [vlfeat/matconvnet#735]
Hi, everyone. I am a new in matconvnet, I find the time bottleneck is train data loading in matconvnet. 
How to implement data loading and train computation in parallel in matconvnet?

thanks!

**Comment by albanie** [comment]
Hi @xhhong - sorry for the slow response. One way to speed up data loading is to make use of the `prefetch` functionality in `vl_imreadjpeg()`, which you can see demonstrated [here](https://github.com/vlfeat/matconvnet/blob/master/examples/imagenet/getImageBatch.m#L59).
