### ISSUE TITLE
Has anybody been successful in using MatConvnet?

### ISSUE THREAD

**Issue by masi96** [vlfeat/matconvnet#737]
Hi,
I've read many forums, found it pretty much nobody has been successful in compiling and running matconvent, I've tried many things and didn't work, that's the last error I get; can anybody help me.
Thanks

Error using mex
MSVCRT.lib(ti_inst.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1900' in vl_nnconv.obj
MSVCRT.lib(tncleanup.obj) : error LNK2038: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1900' in vl_nnconv.obj
   Creating library E:\TextCNN\matconvnet-1.0-beta17\matlab\mex\vl_nnconv.lib and object
   E:\TextCNN\matconvnet-1.0-beta17\matlab\mex\vl_nnconv.exp
vl_nnconv.obj : error LNK2019: unresolved external symbol __imp___stdio_common_vsprintf referenced in function "void __cdecl
vlmxError(enum _VlmxErrorId,char const *,...)" (?vlmxError@@YAXW4_VlmxErrorId@@PEBDZZ)
data.obj : error LNK2001: unresolved external symbol __std_terminate
tinythread.obj : error LNK2001: unresolved external symbol __std_terminate
imread_gdiplus.obj : error LNK2001: unresolved external symbol __std_terminate
data.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl std::_Xbad_alloc(void)"
(__imp_?_Xbad_alloc@std@@YAXXZ) referenced in function "void \* __cdecl std::_Allocate(unsigned __int64,unsigned __int64,bool)"
(?_Allocate@std@@YAPEAX_K0_N@Z)
tinythread.obj : error LNK2019: unresolved external symbol "void __cdecl operator delete(void _,unsigned __int64)" (??3@YAXPEAX_K@Z)
referenced in function "public: __cdecl tthread::thread::thread(void (__cdecl_)(void *),void *)"
(??0thread@tthread@@QEAA@P6AXPEAX@Z0@Z)
imread_gdiplus.obj : error LNK2001: unresolved external symbol "void __cdecl operator delete(void *,unsigned __int64)"
(??3@YAXPEAX_K@Z)
tinythread.obj : error LNK2019: unresolved external symbol __imp_terminate referenced in function "public: __cdecl
tthread::thread::~thread(void)" (??1thread@tthread@@QEAA@XZ)
E:\TextCNN\matconvnet-1.0-beta17\matlab\mex\vl_nnconv.mexw64 : fatal error LNK1120: 5 unresolved externals

Error in vl_compilenn>mex_link (line 475)
mex(mopts{:}) ;

Error in vl_compilenn (line 427)
  mex_link(opts, objs, mex_dir, flags.link) ;

Error in run (line 96)
evalin('caller', [script ';']);

Error in CNN_Run (line 10)
run matlab/vl_compilenn;

I use: 
Matlab 2016b 64
Matconvnet 23

**Comment by nikky4D** [comment]
Hi,
I got similar errors to yours when I compiled with Visual Studio Professional 2015. But, once I switched to VS2013 professional, everything worked well.

So, I used Matlab2016b, on a windows 10, 64bit. I used Matconvnet from Github (downloaded today). I compiled using Visual Studio 2013 professional (I can get it from Microsoft free for students). I picked VS2013 compiler by using the command in matlab. "mex -setup". I could also compile with cuda 8, and cudnn 5, with no errors, using the instructions on the website.

Try using "mex -setup" and change your compiler. That may help.

**Comment by masi96** [comment]
try this, you might need to set your compiler:

% Install and compile MatConvNet (needed once).
untar('http://www.vlfeat.org/matconvnet/download/matconvnet-1.0-beta23.tar.gz') ;
cd matconvnet-1.0-beta23
 mex -setup:'C:\Program Files\MATLAB\R2016b\bin\win64\mexopts\msvc2015.xml' C
 mex -setup:'C:\Program Files\MATLAB\R2016b\bin\win64\mexopts\msvcpp2015.xml' C++


... rest of your code

let me know if it works for you
