### ISSUE TITLE
how to use import-caffe.py

### ISSUE THREAD

**Issue by Necole123** [vlfeat/matconvnet#740]
hi guys, I am a newer in python and caffe, I want to transfer a pre-trained caffemodel to matconvnet format, could anyone tell me how to use import-caffe.py? what are the inputs? Thanks a lot.

**Comment by albanie** [comment]
Hi @Necole123 - no problem.  The usual approach is to write a short shell script that passes the location of your caffe model and the version of caffe you used as inputs to the `import-caffe.py` script.  The [import-ref-models](https://github.com/vlfeat/matconvnet/blob/master/utils/import-ref-models.sh) script gives an example that also downloads the pretrained models from caffe zoo.  Unfortunately the process is often a little fiddly because the protobuf definitions in caffe can vary.

Below is a minimal working example to demonstrate the process for the `vgg-vd-16` model trained with caffe. 

    #! /bin/bash
    
    # set this path to your matconvnet root directory
    matconvnet_root=/your-path-to-matconvnet-root-goes-here
    
    # use the import-caffe.py script as converter
    converter="python $matconvnet_root/utils/import-caffe.py"
    
    # set paths to caffe model prototxt and weights
    model_prototxt=~/data/models/caffe/vgg_vd_16/VGG_ILSVRC_16_layers_deploy.prototxt
    model_weights=~/data/models/caffe/vgg_vd_16/VGG_ILSVRC_16_layers.caffemodel
    
    # set destination for matconvnet model 
    import_dir=~/data/models/caffe-imports
    
    # create destination if it doesn't exist
    mkdir -pv "$import_dir"
    
    # set the name of the converted matconvnet network file
    out="$import_dir/vgg-vd-16-matconvnet.mat"
    
    # run the converter
    $converter \
        --output-format=simplenn \
        --caffe-variant=caffe \
        --caffe-data=$model_weights \
        $model_prototxt \
        $out

**Comment by Necole123** [comment]
@albanie  Thanks a lot, it's really helpful for me.  However, when I try  to run  it , it comes with new errors as follows.

root@ubuntu:~/Desktop/matconvnet/utils# ./rgb-matconvnet.bash
./rgb-matconvnet.bash: line 14: /home/julie/Desktop/matconvnet/utils/caffe-imports: Is a directory
mkdir: cannot create directory ‘’: No such file or directory
Caffe varaint set to caffe
Loading Caffe CNN structure from /home/julie/Desktop/matconvnet/utils/deploy-rgb.prototxt
Loading Caffe CNN parameters from /home/julie/Desktop/matconvnet/utils/s00_rgb.caffemodel
[libprotobuf ERROR google/protobuf/io/coded_stream.cc:208] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Traceback (most recent call last):
  File "/home/julie/Desktop/matconvnet/utils/import-caffe.py", line 330, in <module>
    data.MergeFromString(args.caffe_data.read())
google.protobuf.message.DecodeError: Error parsing message


Does it mean  the google.protobuf not  be  installed correctly? Thanks for your kind reply.

**Comment by Necole123** [comment]
resolved

**Comment by Necole123** [comment]
closed

**Comment by Necole123** [comment]
Fixes#740

**Comment by Necole123** [comment]
Fixes #740

**Comment by zhanglichao** [comment]
@Necole123 so how did you solve it?
