### ISSUE TITLE
Illegal Token while compiling with VS13

### ISSUE THREAD

**Issue by albu5** [vlfeat/matconvnet#743]
matconvnet-1.0-beta21\matlab\src\bits/impl/imread_helpers.hpp(525) : error C2589: '(' :
illegal token on right side of '::'
matconvnet-1.0-beta21\matlab\src\bits/impl/imread_helpers.hpp(525) : error C2059: syntax
error : '::'

I think following change should be made
//     change this -->         skip = std::min(skip, q); 
//     to this -->         skip = (std::min)(skip, q);

in line ~523 of matconvnet-1.0-beta21\matlab\src\bits/impl/imread_helpers.hpp

**Comment by lenck** [comment]
Hi this should be now fixed, hopefully... :) feel free to reopen.

**Comment by albu5** [comment]
Yes I soon realized it was fixed in newer version. Thanks.
