### ISSUE TITLE
logisticlog

### ISSUE THREAD

**Issue by cbenitez81** [vlfeat/matconvnet#744]
The documentation (http://www.vlfeat.org/matconvnet/mfiles/vl_nnloss/) and the help of vl_nnloss specifies a "logisticlog" for attribute classification, however in the actual code the string is just compared with "logistic"

**Comment by JulianoLagana** [comment]
This was not solved. Commit 829798dded42bede7c1b3d69cf91eb17aa527600 only changes the help section of the vl_nnloss file, but the documentation at http://www.vlfeat.org/matconvnet/mfiles/vl_nnloss/ still refers to the attribute as 'logisticlog'.
