### ISSUE TITLE
prepareGPUs takes very long tim

### ISSUE THREAD

**Issue by lyltencent** [vlfeat/matconvnet#746]
Hello, 

I have a problem when running my code. I already compile the MATCONVNET using cuda and it works. However, when I am running the code with GPU mode, the function prepareGPUs in cnn_train take very long time. 

When I type gpuDevie, here is what it shows: 

CUDADevice with properties:

```
                  Name: 'TITAN X (Pascal)'
                 Index: 1
     ComputeCapability: '6.1'
        SupportsDouble: 1
         DriverVersion: 8
        ToolkitVersion: 7.5000
MaxThreadsPerBlock: 1024
      MaxShmemPerBlock: 49152
    MaxThreadBlockSize: [1024 1024 64]
           MaxGridSize: [2.1475e+09 65535 65535]
             SIMDWidth: 32
           TotalMemory: 1.2773e+10
       AvailableMemory: 1.1655e+10
   MultiprocessorCount: 28
          ClockRateKHz: 1531000
           ComputeMode: 'Default'
  GPUOverlapsTransfers: 1
KernelExecutionTimeout: 1
      CanMapHostMemory: 1
       DeviceSupported: 1
        DeviceSelected: 1
```

Since I have only 1 GPU, so the function of prepareGPUs directly runs into the second part: 

if numGpus >= 1 && cold
  fprintf('%s: resetting GPU\n', mfilename) ;
  clearMex() ;
  if numGpus == 1
    disp(gpuDevice(params.gpus)) ;
  else
    spmd
      clearMex() ;
      disp(gpuDevice(params.gpus(labindex))) ;
    end
  end
end

And the gpuDevice and clearMex() takes very long time to run. 

Anyone knows how to solve the problem? any suggestions would be great. 
@vedaldi , @bazilas , @fengyunxiaozi 
Thanks,

**Comment by fengyunxiaozi** [comment]
sorry, I cannot figure out what's wrong, but it seems your codes can run correctly. It would be better if you provide the versions of matconvnet, operating system, cuda, matlab and the compiler. you can update your problem and provide these information. @lyltencent

**Comment by lenck** [comment]
Hey, I've observed this in MATLAB too... But to me it seems that it is because the command `gpuDevice` takes really long :/ 
Sometimes, what helps is to turn on the persistence mode, on Linux machines at least:
```
nvidia-smi -i <target gpu> -pm ENABLED
```
as it keeps the GPU driver loaded.

**Comment by lyltencent** [comment]
Hi @fengyunxiaozi , thank you for your response. 
Operating system: ubuntu 16.04 LTS
Cuda version:  7.5
MATLAB version: 2016a, 
matconvnet verstion: beta 23, which i think is the latest version. 
Compiler: gcc (ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0. 

Thanks,

**Comment by lyltencent** [comment]
Hi Karel, @lenck 

I have only 1 GPU in the system, so what I tried just now is type: nvidia-smi -i  1 -pm ENABLED. 
But it shows that: no devices were found. Any wrong with the command. ?

Thanks,

**Comment by lenck** [comment]
Oh, I think the gpus are zero indexed...
so, maybe try `nvidia-smi -i 0 -pm ENABLED` ...

**Comment by lyltencent** [comment]
Hi @lenck , 

Thanks for your response again. I tried your method to enable the persistant mode of my GPU. However, the function of prepareGPUs function in cnn_train still takes a lot of time. 

function prepareGPUs(params, cold)
% -------------------------------------------------------------------------
numGpus = numel(params.gpus) ;
if numGpus > 1 _**(not my  case since I only have 1 GPU)**_ 
  % check parallel pool integrity as it could have timed out
  pool = gcp('nocreate') ;
  if ~isempty(pool) && pool.NumWorkers ~= numGpus
    delete(pool) ;
  end
  pool = gcp('nocreate') ;
  if isempty(pool)
    parpool('local', numGpus) ;
    cold = true ;
  end
end
if numGpus >= 1 && cold
  fprintf('%s: resetting GPU\n', mfilename) ;
  clearMex() ;
  if numGpus == 1
    **_disp(gpuDevice(params.gpus)) ;_**
  else
    spmd
      clearMex() ;
      disp(gpuDevice(params.gpus(labindex))) ;
    end
  end
end


In this function, the line in bold takes long time. It seems that this line is displaying GPU definitions. _**Can I uncomment this line and still use the toolbox in GPU mode ?**_

Also, I found that the **command single(matrix) takes a lot of time** as well. 
Looking forward to your response. @lenck 

Thank you so much.

**Comment by pxnguyen** [comment]
This is due to the fact that matlab has to recompile its library for Pascal GPU.

Here is the tip I got from my advisor.

"If you run on a GPU architecture (e.g. Pascal) which wasn't supported when the Matlab  software was released, the first time you attempt to run some code, e.g. gpuDevice(), the JIT system will have to recompile those kernels which may take several minutes."

"The good news is that those compiled kernels are cached in the user's home directory.  However, the default cache size is on 32M which is too small to even hold all of Matlab's kernels so you will still have long wait times every time you start Matlab.  To fix this, you can expand it by setting the environment variable, e.g. CUDA_CACHE_MAXSIZE=4200000000."
