### ISSUE TITLE
CUDA error - How to resolve?

### ISSUE THREAD

**Issue by res97** [vlfeat/matconvnet#75]
I am wondering that anyone has insights into how to resolve this error: 

Error using gpuArray
An unexpected error occurred during CUDA execution. The CUDA error was:
an illegal memory access was encountered

Error in vl_simplenn_move>@(x)gpuArray(x) (line 16)
  case 'gpu', moveop = @(x) gpuArray(x) ;

**Comment by lenck** [comment]
Hi, this seems like some Matlab related issue. Can you create a small gpuArray (e.g. by calling`gpuArray.zeros(10,10)`)?
