### ISSUE TITLE
vl_nnconcat() function use

### ISSUE THREAD

**Issue by lkaige** [vlfeat/matconvnet#759]
now, my network model is a three convolution layers and three full connection layers, I want connect the last convolution layer's output and the last connect layer's output, and then as the input of the last layer. when i use the vl_nnconcat() function it tell me that dimensions are not consistent. what should i do? Thank you!

**Comment by lenck** [comment]
Hi, you need to use the dagnn interface...

**Comment by lkaige** [comment]
First of all thank you to answer my question, you can tell me about the specific use of specific steps, it is best to give me a simple example, thank you.

**Comment by lenck** [comment]
Hi, you can start [here](http://www.vlfeat.org/matconvnet/wrappers/) or [here](http://www.vlfeat.org/matconvnet/mfiles/+dagnn/@DagNN/DagNN/). Also the `print('format', 'dot')` is quite useful, once you have dot installed...
