### ISSUE TITLE
queries about vggm and its variant models vggm-128/1024/2048

### ISSUE THREAD

**Issue by fengyunxiaozi** [vlfeat/matconvnet#768]
Hi everyone, I was using vggm and its variant models vggm-128/1024/2048 for transfer learning. However, I got some confusing results. As it is said in the paper "Return of the Devil in the Details:
Delving Deep into Convolutional Nets", to speedup training, all layers aside from full7/full8 were
set to those of the CNN-M net. So the convolutional and full6 layers of these four models should have the same weights, but I got different results on the same dataset by using features extracted from full6 layer of these four models. what's wrong?
thanks in advance!

**Comment by fengyunxiaozi** [comment]
@lenck do you have any ideas about this? thanks!

**Comment by lenck** [comment]
Hi, haven't read that paper, but I assume they were just initialised? So they must have changed quite a bit while learning the dimensionality reduction?

Just guessing, ask the authors probably :)
