### ISSUE TITLE
Using continuous classes?

### ISSUE THREAD

**Issue by bainbri** [vlfeat/matconvnet#774]
How can I set up a CNN that is trained on / predicts a continuous value? For example, at the training level, what do I set as the "classes" for the images if I want it to be a float? Thank you!

**Comment by lenck** [comment]
Hi, you need to use a different loss layer - e.g. the vl_pdist, which implements the Euclidean loss... E.g. in the `simplenn` interface, see [here](https://github.com/vlfeat/matconvnet/blob/master/matlab/simplenn/vl_simplenn.m#L190).
