### ISSUE TITLE
Adding classes to a pretrained net

### ISSUE THREAD

**Issue by Izzy88** [vlfeat/matconvnet#777]
Hi,
I'm trying to include n additional classes to a resnet 152 pretrained on imagenet so that if it originally has 1000 classes, the newly trained net will end up recognising 1000 + n classes. Is there a quick way to obtain this kind of result? Analysing the structure of the pretrained resnet 152 downloaded from your page I noticed that the meta information includes a code representing the classes name and their associated descriptions. Obviously, fine tuning the net with the new number of classes leaves this structure invariant, should I modify it manually from cell 1001 to 1010 then? If it is so, I still don't understand how to associate the new classes in my dataset with the one added manually in the meta cells.
thank you

**Comment by albanie** [comment]
Hi @Izzy88, sorry for the slow response.  

It's a good question.  Unfortunately there isn't really a quick way to achieve this result.  If `n` is small and you wish to keep most of the structure of the resnet the same, the simplest approach is to extend the imagenet dataset with your new classes (i.e. increasing the number of classes to 1000 + n ), retraining the network on this new dataset.  To achieve this, you would probably aim to start with the same weights of the pretrained network except for the final fully connected layer (which can be reset with a random initialisation). For this to work well the new data should have similar statistics to the original imagenet data.  

To prepare the pretrained 152 layer residual network for this retraining, you can modify the final fully connected layer as follows:

    modelPath = '~/data/models/matconvnet/imagenet-resnet-152-dag.mat' ;
    net = dagnn.DagNN.loadobj(modelPath) ;
    
    data = single(imread('peppers.png')) ;
    net.eval({'data', data}) ;
    
    layer = net.layers(net.getLayerIndex('fc1000')) ;
    numClasses = layer.block.size(4) ;
    
    % pick an example value for `n`
    n = 5 ;
    
    % update shape of last fully connected layer
    h = layer.block.size(1) ;
    w = layer.block.size(2) ;
    in = layer.block.size(3) ;
    out = numClasses + n ;
    layer.block.size = [ layer.block.size(1:3) numClasses ] ;
    
    % randomly re-initialise the parameters with your favourite method
    % (here I am using 'xavier imrpoved')
    sc = sqrt(2/(h*w*out)) ;
    filters = randn(h, w, in, out, 'single')*sc ;
    biases = zeros(out, 1, 'single') ;
    params = layer.params ;
    net.params(net.getParamIndex('fc1000_filter')).value = filters ;
    net.params(net.getParamIndex('fc1000_bias')).value = biases ;
    
    % rename the layer to reflect update
    net.renameLayer('fc1000', 'fc1005') ;
    
    % rename params
    net.params(net.getParamIndex('fc1000_filter')).name = 'fc1005_filter' ;
    net.params(net.getParamIndex('fc1000_bias')).name = 'fc1005_bias' ;
    
    % begin training on extended dataset, setting learning rates as desired

There is a lot of interest in the deep learning community about how to train networks to learn new classes and yet still remember the original classes they were trained on.  One nice idea was introduced in the "learning without forgetting" [paper](https://arxiv.org/abs/1606.09282), but there are many other approaches.
