### ISSUE TITLE
vl_compilenn issue on Windows 8.1 Matlab R2014b

### ISSUE THREAD

**Issue by Tar12** [vlfeat/matconvnet#78]
Using the default settings, 

addpath('matlab')
vl_compilenn

Results in:

Building with 'Microsoft Visual C++ 2010'.
Error using mex
data.cpp
matconvnet-master\matlab\src\bits\data.cu(169) : error C4716:
'vl::Context::getCudaHelper' : must return a value

Tried on a different computer with Windows7 and Matlab R2014a and same issue. 

Thanks!

**Comment by pengsun** [comment]
I met the same problem. As a temporary fixing,  I simply add "return *cudaHelper ;" at line 168 of  data.cu and it compiles well.

I believe this minor issue would be fixed in a near commit.

**Comment by Tar12** [comment]
Works, thanks!

**Comment by vedaldi** [comment]
Thanks, fixed in the master branch.
