### ISSUE TITLE
How to use net.eval to get the "pro" of multiple Images

### ISSUE THREAD

**Issue by lenckyym** [vlfeat/matconvnet#781]
Hi,   I want to use net.eval to extract features from a pre-trained model for some image datasets.  But when net.eval used, I am not sure whether the GPU is used. For the case that net.Device=cpu, it works well. But when move(net,'gpu') is used to change the device, matlab error shows: "DATA and FILTERS do not have compatible formats. " for net.eval commend. 

Many thanks.

**Comment by lenck** [comment]
Hi, you probably also need to move the data which you are passing to eval to gpu:
```
x_gpu = gpuArray(x)
```

**Comment by lenckyym** [comment]
many thanks. it works well now.
