### ISSUE TITLE
vl_nnconv & vl_nnconvt

### ISSUE THREAD

**Issue by luckh2** [vlfeat/matconvnet#784]
X=randn(5)
F=randn(2)
C1=vl_conv(X,F,[])
C2=vl_convt(C1,F,[])

assert(isequal(X, C2)) 
Failed...

 X==vl_nnconvt(vl_nnconv(X,F,[]),F,[])
return 0 ...

Why？

**Comment by lenck** [comment]
Those two expressions are equal no?

But convolution transpose is not an inverse convolution, but it is transpose of the convolution if expressed as a linear transformation:
```
  The convolution transpose operator is defined as follows. Let U =
    VL_NNCONV(V, F, []). Since this is a linear operation, there is a
    matrix M such that U(:) = M V(:). The convolution transpose is
    the linear convolution operator that results in Y(:) = M'
    X(:). See the PDF manual for further detials.
```
And I don't think that M would end up that often to be orthogonal...
