### ISSUE TITLE
caffemodel

### ISSUE THREAD

**Issue by sunilrao43** [vlfeat/matconvnet#79]
how can i parse the caffemodel directly to matconvnet 

how can i acess the weights and biases of the pretrained model

**Comment by sunilrao43** [comment]
@vedaldi  can u suggest me a way to parse the .caffemodel or .mat of alexnet in to C code

**Comment by vedaldi** [comment]
Hi, there is a conversion script in the utils subdirectory that may help you importing caffe models. This will require having python and numpy installed.

**Comment by sunilrao43** [comment]
@vedaldi I need to parse to C code .can you help me with a code 
Im a newbie @vedaldi thanks in advance

**Comment by sunilrao43** [comment]
@vedaldi Iam newbie to CNN 
I am having installation isssues of matconvnet 
cant i run matconvnet with CPU 
mymatlab version is 2013a and is it required to have cuda for running on cpu 
though i installed cuda 6.5 will that support matconvnet
when i run vl_test_nnlayers i get the following error
testing vl_nnconv with fully connected identity filters
Attempt to execute SCRIPT vl_nnconv as a function:
C:\Users\Sunil\Desktop\matconvnet-master\matlab\vl_nnconv.m

Error in vl_test_nnlayers (line 124)
      y = vl_nnconv(x,[],b,'verbose') ;

https://github.com/vlfeat/matconvnet/issues/13 

could you help me with that with a step by step procedure iam on windows 
thanks in advance @vedaldi

**Comment by felixachilles** [comment]
Could you try to install Matlab 2014b and see if this resolves the issues?
Might be easier altogether...

2015-02-27 13:16 GMT+01:00 sunilrao43 <notifications@github.com>:

> @vedaldi <https://github.com/vedaldi> Iam newbie to CNN
> I am having installation isssues of matconvnet
> cant i run matconvnet with CPU
> mymatlab version is 2013a and is it required to have cuda for running on
> cpu
> though i installed cuda 6.5 will that support matconvnet
> when i run vl_test_nnlayers i get the following error
> testing vl_nnconv with fully connected identity filters
> Attempt to execute SCRIPT vl_nnconv as a function:
> C:\Users\Sunil\Desktop\matconvnet-master\matlab\vl_nnconv.m
>
> Error in vl_test_nnlayers (line 124)
> y = vl_nnconv(x,[],b,'verbose') ;
>
> #13 <https://github.com/vlfeat/matconvnet/issues/13>
>
> could you help me with that with a step by step procedure iam on windows
> thanks in advance @vedaldi <https://github.com/vedaldi>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vlfeat/matconvnet/issues/79#issuecomment-76386152>.
>



-- 
-------------------------------------------------------------------
---------------------------------------------------------------

*Technische Universität München**Felix Achilles, M.Sc.** · *Faculty of
Informatics *· *Chair for Computer Aided Medical Procedures
Boltzmannstr. 3 *· *85748 Garching b. München · +49 (0)176 623 18 312
achilles@in.tum.de *· *campar.in.tum.de
------------------------------------------------------
----------------------------------------------------------------------------

**Comment by sunilrao43** [comment]
@felixachilles thanks for reply sure i will try .... could you look on to my previous comment issue for parsing caffemodel to C code
