### ISSUE TITLE
problem with vl_nnconv

### ISSUE THREAD

**Issue by jihenbouchtiba** [vlfeat/matconvnet#793]
hi,
i work with myconvnet on medical images. The training goes well. To test my network, i get this error :
Error using vl_nnconv
An input is not a SINGLE array nor it is empty.

Error in vl_simplenn (line 180)
        res(i+1).x = vl_nnconv(res(i).x, l.weights{1}, l.weights{2}, 'pad', l.pad, 'stride', l.stride, 'hole', l.hole) ;

Can you help me please !!

**Comment by albanie** [comment]
Are the inputs to the network in the `single` data format? You can convert it to this format with the following:

    data = single(data) ;

(this could be done, for example, inside your `getBatch()` function).

**Comment by jihenbouchtiba** [comment]
hello,
thank you very much. it was that and i resolved it :)

2016-12-09 16:25 GMT-04:00 Samuel <notifications@github.com>:

**Comment by albanie** [comment]
glad to hear it :)
