### ISSUE TITLE
The number of filter groups does not divide the total number of filters.

### ISSUE THREAD

**Issue by Cisy** [vlfeat/matconvnet#80]
I've seen the answer in https://github.com/vlfeat/matconvnet/issues/54
But I still can't find what is wrong with my net.
Could you please help me with it?
thanks a lot.

>> vl_simplenn_display(net)
     layer|      1|      2|      3|      4|      5|      6|      7|      8|      9|     10|     11|     12|     13|     14|     15|     16|     17|     18|     19|     20|     21|
      type|    cnv|   relu|    nrm|  mpool|    cnv|   relu|    nrm|  mpool|    cnv|   relu|    cnv|   relu|    cnv|   relu|  mpool|    cnv|   relu|    cnv|   relu|    cnv|   sftm|
   support|  11x11|    1x1|    1x1|    3x3|    5x5|    1x1|    1x1|    3x3|    3x3|    1x1|    3x3|    1x1|    3x3|    1x1|    3x3|    6x6|    1x1|    1x1|    1x1|    1x1|    1x1|
    stride|      4|      1|      1|      2|      1|      1|      1|      2|      1|      1|      1|      1|      1|      1|      2|      1|      1|      1|      1|      1|      1|
       pad|      0|      0|      0|0,1x0,1|      2|      0|      0|      0|      1|      0|      1|      0|      1|      0|      0|      0|      0|      0|      0|      0|      0|
   out dim|     64|     64|     64|     64|    256|    256|    256|    256|    256|    256|    256|    256|    256|    256|    256|   4096|   4096|   4096|   4096|    250|    250|
  filt dim|      1|    n/a|    n/a|    n/a|     64|    n/a|    n/a|    n/a|    256|    n/a|    256|    n/a|    256|    n/a|    n/a|    256|    n/a|   4096|    n/a|   4096|    n/a|
rec. field|     11|     11|     11|     19|     51|     51|     51|     67|     99|     99|    131|    131|    163|    163|    195|    355|    355|    355|    355|    355|    355|
c/g net KB|   31/0|    0/0|    0/0|    0/0| 1601/0|    0/0|    0/0|    0/0| 2305/0|    0/0| 2305/0|    0/0| 2305/0|    0/0|    0/0|147472/0|    0/0|65552/0|    0/0| 4001/0|    0/0|

**Comment by Cisy** [comment]
I've found the problem. Thanks a lot.

**Comment by fybaft2012** [comment]
how could you find the solution ? would you mind help me ? Thanks  a lot!
