### ISSUE TITLE
Issues with vl_imreadjpeg

### ISSUE THREAD

**Issue by xcyan** [vlfeat/matconvnet#82]
Hi,

I downloaded the latest version and successfully compiled with CUDA and CUDNN.
However, when I was trying to run "vl_imreadjpeg", Matlab crashed with error message "Segmentation fault (core dumped)". Here is the code:
vl_imreadjpeg({'hello.jpg'})

I was wondering if the command is valid or not? Many thanks!

**Comment by hyeokhyen** [comment]
I also suffered same problem after updating to latest version.

After several batch iterations, it says same error mentioned above.

And clearly their exists jpeg images, where path is input.

Haven't anyone solved this issue??

**Comment by vedaldi** [comment]
Hi, thanks for reporting. I will have a look ASAP, although I do not think that part of the library changed. Could you please share an image that causes the crash?

**Comment by hyeokhyen** [comment]
I was implementing the Convnet introduced in "Computing the Stereo Matching Cost with a Convolutional Neural Network".

As mentioned in the paper,
I first extracted 9x9 sample patches from "Kitti dataset" by imwrite() built-in matlab function with Quality 100% of jpeg format, and also additionally saved patch paths for vl_imreadjpeg(). Like,

imwrite(imgSample, 'imgPath/imageName.jpeg', 'Quality',100);

The examples of image I used are as below,

![imgl_3](https://cloud.githubusercontent.com/assets/11296711/6477708/f71b911c-c269-11e4-9778-92da05d21e3c.jpeg)

![imgrn_4](https://cloud.githubusercontent.com/assets/11296711/6477712/0b712d34-c26a-11e4-8b94-bf7460fe290f.jpeg)

![imgl_7](https://cloud.githubusercontent.com/assets/11296711/6477723/2ff83a26-c26a-11e4-9d49-4cc035b3ac3a.jpeg)

And, they are read by imread() built-in matlab function with no problem.
If you need any more information, please let me know

Thank you!

**Comment by hyeokhyen** [comment]
I have solve the problem. And my problem seems different from 'xcyan's'

My error came from multi-thread process.

In certain iteration, I had more than 2 same file in the batch and it made crush between threads.

Sorry for giving you confusion,
And Thank you for your cares :)

**Comment by vedaldi** [comment]
Hi, there is a new implementation of vl_imreadjpeg in beta10. Does it solve these problems?

**Comment by hyeokhyen** [comment]
I will try and see what happens

Thank you for the updates.

Best,
Hyeokhyen

On Fri, Mar 27, 2015 at 10:22 PM, Andrea Vedaldi <notifications@github.com>
wrote:

> Hi, there is a new implementation of vl_imreadjpeg in beta10. Does it
> solve these problems?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vlfeat/matconvnet/issues/82#issuecomment-86938540>.
>



-- 
-----------------------------------------
HyeokHyen Kwon.
Master's candidate.
Korea Advance Institute of Science and Technology(KAIST).
Daejeon, Korea,Republic of
e-mail: hyeokhyen@gmail.com
Tel: +82-10-4188-1776

**Comment by WendyShang** [comment]
Hi Sorry for the late reply.
We have figured out how to resolve the bug:
(1) make sure all the libraries are correctly installed and linked
(2) cd('path/to/matconvnet-1.0-beta9/');
     vl_compilenn('enableImreadJpeg', true,'ImreadJpegCompileFlags', {'­-I/opt/local/include','-­L/opt/local/lib','-­ljpeg'});

**Comment by vedaldi** [comment]
Hi, ok, brilliant. Thanks for letting us know.

**Comment by lenck** [comment]
@hyeokhyen - Just wanted to ask if the beta10 update solved the issue for you? Just trying to clean some stale issues :)

**Comment by hyeokhyen** [comment]
Oh, yes.

Sorry for late reply. I was busy these days preparing for upcoming
conference.

It works without any bugs.

Thank you for your cares and Your matconvnet library is being big help for
my current research!

Best,
Hyeokhyen

On Thu, Apr 16, 2015 at 6:31 PM, Karel Lenc <notifications@github.com>
wrote:

> @hyeokhyen <https://github.com/hyeokhyen> - Just wanted to ask if the
> beta10 update solved the issue for you? Just trying to clean some stale
> issues :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vlfeat/matconvnet/issues/82#issuecomment-93691258>.
>



-- 
-----------------------------------------
HyeokHyen Kwon.
Master's candidate.
Korea Advance Institute of Science and Technology(KAIST).
Daejeon, Korea,Republic of
e-mail: hyeokhyen@gmail.com
Tel: +82-10-4188-1776

**Comment by lenck** [comment]
Great, good luck with the paper! :)
