### ISSUE TITLE
Iteration speed become slower and slower

### ISSUE THREAD

**Issue by yw155** [vlfeat/matconvnet#820]
I find the iteration speed in training and testing stage becomes slower and slower. I tried to clear all disused variables, but this only mitigates the reduction of speed. I run MatConvNet in Windows. Anyone knows the reason?

**Comment by albanie** [comment]
Hi @yw155, over what kind of time scale is the slow down occurring? Is it immediately obvious or gradual? Are you noticing similar behaviour to #621?

**Comment by yw155** [comment]
Hi, @albanie, the speed is decreased gradually. I use MATLAB R2015b, cuDNN5.1, and MatConvNet beta23 on Windows. I just see the description of MATLAB version in the #621, I will use MATLAB R2016 to test the speed. Thank you!

**Comment by yw155** [comment]
Hi, @albanie, now I use MATLAB R2016b and the iteration speed is not decreased. Thank you!
