### ISSUE TITLE
nvcc fatal   : Unknown option when compiling with CudaMethod

### ISSUE THREAD

**Issue by anselmoferreira** [vlfeat/matconvnet#823]
I can compile Matconvnet perfectly using these two commands: 

```
  >>  vl_compilenn('enableGpu', true)
  >> vl_compilenn('enableGpu',true,'cudaRoot','/usr/local/cuda-8.0')
```

However, when I compile it using the following command:
`   vl_compilenn('enableGpu',true,'cudaRoot','/usr/local/cuda-8.0', 'cudaMethod', 'nvcc', 'verbose', '2')
`The following error appears:

```
vl_compilenn: 	image library link flags: -ljpeg
vl_compilenn: NVCC CC: "/usr/local/cuda-8.0/bin/nvcc" -c "/home/anselmo/matconvnet-master/matlab/src/bits/impl/pooling_gpu.cu" -v,-DNDEBUG,-DENABLE_GPU,- I"/usr/local/MATLAB/R2016a/extern/include",-I"/usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/include",-Xcompiler,-fPIC,-gencode=arch=compute_50,code=\"sm_50,compute_50\"  -o "/home/anselmo/matconvnet-master/matlab/mex/.build/bits/impl/pooling_gpu.o"
nvcc fatal   : Unknown option 'v,-DNDEBUG,-DENABLE_GPU,-I/usr/local/MATLAB/R2016a/extern/include,-I/usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/include,-Xcompiler,-fPIC,-gencode'
Error using vl_compilenn>nvcc_compile (line 445)
Command "/usr/local/cuda-8.0/bin/nvcc" -c "/home/anselmo/matconvnet-master/matlab/src/bits/impl/pooling_gpu.cu"
-v,-DNDEBUG,-DENABLE_GPU,-I"/usr/local/MATLAB/R2016a/extern/include",-I"/usr/local/MATLAB/R2016a/toolbox/distcomp/gpu/extern/include",-Xcompiler,-fPIC,-gencode=arch=compute_50,code=\"sm_50,compute_50\"
-o "/home/anselmo/matconvnet-master/matlab/mex/.build/bits/impl/pooling_gpu.o" failed.

Error in vl_compilenn (line 387)
parfor i = 1:numel(horzcat(lib_src, mex_src))

```     

I really want to compile setting nvcc as CudaMethod because I want to compile it using CUDNN later. What can be happening? 

I am using matlab 2016a on Ubuntu 16.04 with cuda 8.0 and gcc/g++ version 4.7

**Comment by albanie** [comment]
Hi @anselmoferreira, the line `parfor i = 1:numel(horzcat(lib_src, mex_src))` suggests a slightly older version of Matconvnet - is it an option for you to try upgrading to the latest version (which contains some extra fixes in `vl_compilenn`)?

**Comment by anselmoferreira** [comment]
Thanks @albanie for your answer. I really want this version so I will not change my code very much. However, I will try another version and update you very soon.

**Comment by anselmoferreira** [comment]
In the new version (matconvnet 1.0-beta23) I can do the following commands without errors after changing gcc from 4.7 to 5.4
    
   ```
 vl_compilenn
    vl_compilenn('enableGpu',true)
    vl_compilenn('enableGpu',true,'cudaRoot','/usr/local/cuda-8.0')
    vl_compilenn('enableGpu',true,'cudaRoot','/usr/local/cuda-8.0', 'cudaMethod', 'nvcc')
```

   However, when I try the cuDNN support with the command below:
 
      `  vl_compilenn('enableGpu',true,'cudaRoot','/usr/local/cuda-8.0','verbose', '2','enableCudnn','true','cudnnRoot','local/cudnn-rc8/include')`

I have the following error:

```
vl_compilenn: * CUDA configuration *
vl_compilenn:	CUDA: using CUDA Devkit '/usr/local/cuda-8.0'.
vl_compilenn:	CUDA: using NVCC '/usr/local/cuda-8.0/bin/nvcc' (80044).
vl_compilenn:	CUDA: determining GPU compute capability (use the 'CudaArch' option to override)
vl_compilenn:	CUDA: NVCC architecture string: '-gencode=arch=compute_50,code=\"sm_50,compute_50\" '.
Operands to the || and && operators must be convertible to logical scalar values.

Error in vl_compilenn (line 411)
    if opts.enableGpu && opts.enableCudnn
```

**Comment by albanie** [comment]
So close! I think in the command 

    vl_compilenn('enableGpu',true,'cudaRoot','/usr/local/cuda-8.0','verbose', '2','enableCudnn','true','cudnnRoot','local/cudnn-rc8/include')

you want to change `'true'` to `true`, otherwise MATLAB interprets the argument as a string.  So the command would become:
 
    vl_compilenn('enableGpu',true, 'cudaRoot', '/usr/local/cuda-8.0','verbose', 2, 'enableCudnn', true, 'cudnnRoot', 'local/cudnn-rc8/include')

**Comment by anselmoferreira** [comment]
You are right. Unfortunately this solves only for the new matconvnet version. Thanks anyway.
