### ISSUE TITLE
 caffe to .matfile

### ISSUE THREAD

**Issue by sunilrao43** [vlfeat/matconvnet#83]
how do i convert my own model generated in caffe to .matfile
Please provide me a step-by step procedure 
thanks in advance

**Comment by lenck** [comment]
Hi, sorry, but this part of MatConvNet is sort of an utility script which may change any time. Also as not all Caffe layers are supported and in current release the DAG structure is not supported either, it does not have to work for all networks. This is why I cannot give you step by step guide as you would probably need to modificate the provided code yourself as currently it works only for the given networks.
But if you would like to try to convert some AlexNet-like networks, just look how is it done `matconvnet/utils/import-ref-models.sh` where the conversion script `matconvnet/utils/import-caffe.py` is called. In general, the .sh script should be able to generate the networks which are provided on the MatConvNet website...

**Comment by sunilrao43** [comment]
@lenck  thanks for a quick reply i have downloaded the model .. do they replicate same as the caffe website hostes

is matconvnet purely matlab or it uses the cuda libraries

can i install and run matconvet with matlab alone ...
thanks in advance

**Comment by lenck** [comment]
Yes, matconvnet replicates the results of caffe almost exactly (with tiny differences caused by different implementation). You can download the modesl from the [website](http://www.vlfeat.org/matconvnet/pretrained/).
Matconvnet is combination of Matlab, C++ and CUDA code, but when you compile without GPU support you do not need CUDA at all...
And yes, if you have Matlab with working mex compiler you can install MatConvNet.

**Comment by sunilrao43** [comment]
@lenck i am trying to write matlab code to the CNN operations of alexnet using the pretrained model
 i have downloaded the alexnet from caffe website ..
i have downloaded the imagenet.caffemodel.mat from the matconvnet website 
when i apply the filter2 using the net.layer.filter(:,:1,1) on the image in matlab the output results are different from caffe... can you give me small explanation how can see both the results are same and how did you encode the data into the .matfile 
@lenck THANKS IN ADVANCE

**Comment by dteney** [comment]
Could it just be that Matlab's filter2 performs correlations, whereas you rather want to do convolutions ? (you can flip the filter, or pass an argument to filter2 to do convolutions)

**Comment by sunilrao43** [comment]
@dteney thanks for the reply 
I didnt get you ..could explain me what you mean

**Comment by CharlesShang** [comment]
@lenck 

     when you compile without GPU support you do not need CUDA at all

Does that mean MatConvNet can run on non-Nvidia-Card system still using GPU?

**Comment by vedaldi** [comment]
Hi, likely Caffe is using row major and MatConvNet column major to store images. You may need to swap X and Y. Also, Caffe uses BGR and MatConvNet RGB, so in the first layer channels may need swapping. See the conversion script in utils/ to check which kind of transforms we apply upon input. Note, this is done to keep MATLAB “standard” image format as input.

**Comment by vedaldi** [comment]
It means that deep learning people are not necessarily signal processing people and may not carefully distinguish between convolution and correlation filters. In practice, the two are pretty much identical, but convolution would “flip” the filters compared to correlation. MatConvNet implements correlation filtering for compatibility with caffe and similar. (cuDNN explicitly and correctly distinguish between them though)

**Comment by vedaldi** [comment]
Hi, no, I do not see how it could work without CUDA or even compile without it. MATLAB only supports CUDA, not OpenCL or similar.

**Comment by esason** [comment]
Hi,
Suppose I would like to use the convertor matconvnet/utils/import-caffe.py  as it is.
Can u please add your caffe branch u worked with?
I conclude from this post that I need to work with one of them. or to update the converter function.
thanks,
Eli.
