### ISSUE TITLE
HI，i use SimpleNN wrapper,the following error occurred.

### ISSUE THREAD

**Issue by hushunda** [vlfeat/matconvnet#846]
Reference to a field that does not exist 'dilate'。

error vl_simplenn (line 303)
        'dilate', l.dilate, ...

![image](https://cloud.githubusercontent.com/assets/21358656/21960345/cfda345e-db22-11e6-85d8-cf7149990424.png)

**Comment by fengyunxiaozi** [comment]
update your model to the newest version using vl_simplenn_tidy
