### ISSUE TITLE
GPU image cropping and resizing in MatConvNet

### ISSUE THREAD

**Issue by aosokin** [vlfeat/matconvnet#86]
Hello,

I'm applying MatConvNet to an application (object detection) where I have to crop subimages and resize them to the CNN input size at each iteration. I can't afford to do cropping beforehand because it will require too much storage space.
Does MatConvNet have any functionality that could do cropping/resizing?

I've tried using Matlab's imresize function for this, but without much success. 
On CPU imresize is too slow ( batch creation times becomes slower that forward + backward pass). On GPU imresize is of ok speed but does not support non-uniform scaling (rescaling rectangular image to square size).
Ideally I'd prefer to crop/resize many bounding boxes in parallel on GPU.

Do you have any suggestion how this could be done?
Is there any standard software that could solve this task?

Thanks in advance!

**Comment by lenck** [comment]
Hi, unfortunatelly there is nothing for this task in MatConvNet.
From the libraries which support this, there is resize function in CUDA OpenCV, or just quick google search found this [library](http://www.fastcompression.com/solutions/resize/fast-image-resizer.htm). But I would probably just program a CUDA kernel for bilinear interpolation (in case when you are not changing the scale too much) as it would be quite straight forward as you can map the kernels to the output indexes.... That may be probably faster then fighting with the libraries and their dependencies...

**Comment by aosokin** [comment]
Thanks a lot for your answer.
To close the topic, I've found another option: NVIDIA Performance Primitives (NPP) library which is supplied with CUDA has function that can do the job.

**Comment by lenck** [comment]
Cool, good to know :) Thanks for info!

**Comment by aosokin** [comment]
I've created a MATLAB function that performs the operation on a GPU: crop many patches from an image and resize them to the standard size: https://github.com/aosokin/cropRectanglesMex
