### ISSUE TITLE
Where is vl_dagnn.m ?

### ISSUE THREAD

**Issue by pengsun** [vlfeat/matconvnet#88]
Hi @vedaldi, @lenck and all,

I have been worked on the DAG (Directed Acyclic Graph) wrapper for **matconvnet**. But recently I found that there seemed already such a wrapper out there, according to the description of [the doc](http://www.vlfeat.org/matconvnet/developers/). Unfortunately, I can't find the the file `vl_dagnn.m` in any official branch. Could anyone help on that?

**Comment by lenck** [comment]
Hi, `vl_dagnn.m` was and still is under development. But if you would like to try it in the current state (still needs some polishing and more testing, mainly of the BP part) I've pushed it to the `dev-dag` branch.
There is also a [script](https://github.com/vlfeat/matconvnet/blob/dev-dag/utils/import-googlenet.sh) to download and convert the [princeton googlenet network](http://vision.princeton.edu/pvt/GoogLeNet/). So far it seems to run quite fast, but it would be really helpful if you would have any bugreports or comments in general :)
Also, if you would be curious how big the googlenet is, here is a [visualisation](https://www.dropbox.com/s/08civrafi8vlqji/googlenet.svg?dl=1) which is also part of this branch. And, just to compare, here is visualisation of [AlexNet](https://www.dropbox.com/s/31kj823bz7bj8be/alexnet.svg?dl=1).

**Comment by pengsun** [comment]
Great! Thanks so much @lenck, surely I'll be very happy to try it!

**Comment by pengsun** [comment]
Hi @lenck,

I've studied your `vl_dagnn.m` code. It is well written and is consistent with the style of `vl_simplenn.m`. But I found it slightly difficult for the task I'm working on to fit the `vl_dagnn.m` style, mainly because I need build the DAG in a recursive way where the DAG itself is seen as a node embedded in a higher level DAG, and so on. As such, I didn't really run the `vl_dagnn.m` with my own task in hand.

Sorry for having opened the issue and I hope this had not disturbed your schedule:)

**Comment by lenck** [comment]
No worries, I'm glad that you liked it :)
But it sounds to me that you just need a recursive function which will construct the network? I mean, `vl_dagnn` is just to evaluate and train any DAG network, not to construct them, for which you can wtite anything you want as far as you would specify the layer names and inputs... Or use the imported googlenet as example (with its inception modules).

**Comment by dbbert** [comment]
Hi @lenck, I can't seem to find the code for visualizing the DAG-network as an svg graph in the current dag branch. Is it not included?

**Comment by vedaldi** [comment]
Hi, we are reworking the interface to use objects and not all previous DAG features have been ported to the new structure yet.

**Comment by HuiZeng** [comment]
Hi, I make a test of the GoogleNet both in the MatConvNet and caffe, but get different feature value. 
I can always get the same dimensional output but the value are totally different. This difference appears even in the first layers (i.e. conv1_7x7). When testing VGG-19, I can always get identical feature.

For MatConvNet I follow the guides in the "quick start".
For caffe I slightly change a demo to output the features I wanted.

And I find that the converted "imagenet-googlenet-dag [DagNN format]" has 154 layers (net.vars) while the caffemodel has 142 layers in the provided proto file. Is there any difference between this two format model and how to get the same output of them?

Thanks!

**Comment by vedaldi** [comment]
Hi,
> Hi, I make a test of the GoogleNet both in the MatConvNet and caffe, but get different feature value. 
> I can always get the same dimensional output but the value are totally different. This difference appears even in the first layers (i.e. conv1_7x7). When testing VGG-19, I can always get identical feature
> 
Ok it may be a difference in the preprocessing of the image?
> For MatConvNet I follow the guides in the "quick start".
> For caffe I slightly change a demo to output the features I wanted.
> 
> And I find that the converted "imagenet-googlenet-dag [DagNN format]" has 154 layers (net.vars) while the caffemodel has 142 layers in the provided proto file. Is there any difference between this two format model and how to get the same output of them?
> 
The difference is normal. Caffe has some layers “in place” like relu and dropout that essentially overwrite the same variable. For MatConvNet we found that this solution was a bit confusing; instead, we still save the memory (by aggressively forgetting the value of unneeded variables), but explicitly name separately each output of each layer. Hence it appears that there are a few more variables.

**Comment by KhwildiRaoua** [comment]
Hi, i need the vl_dagnn.m code. Can you help me please!
