### ISSUE TITLE
vl_connv

### ISSUE THREAD

**Issue by sunilrao43** [vlfeat/matconvnet#89]
@vedaldi  can you give me details of what happens in the convolution layer 
in purely matlab.
iam basically trying to write a convolution layer in matlab on an input image of 3 channels
and my filter size is 11x11x3 
input image is 227x227x3
what i assume is convolving each channel with respect to each respective channel in the filter and then adding all the results to get the convolved image say in this case 56x56 with a stride of 4 .

is this right if not please provide me info regarding this...thanks in advance @vedaldi

**Comment by lenck** [comment]
Hi, what you may find useful is this [issue](https://github.com/vlfeat/matconvnet/issues/17), or also to get all the details of the vl_nnconv internals you can find in the [manual](http://www.vlfeat.org/matconvnet/matconvnet-manual.pdf) in section 2.1. I hope it would help :)
Though as far as I know there is no support for stride in Matlab's convolution or correlation implementations, so you would have to downsample the output (so it would be quite slow).
