### ISSUE TITLE
Pre-Trained Models of CIFAR and MNIST networks

### ISSUE THREAD

**Issue by anselmoferreira** [vlfeat/matconvnet#890]
I can see on [This Link](http://www.vlfeat.org/matconvnet/pretrained/) that several pre-trained models are available to download, but I can't find the pre-trained models from CIFAR and MNIST networks. Can I get them from anywhere else or should I run the CIFAR and MNIST examples and save their respective models as a .mat file?

**Comment by layumi** [comment]
Hi @anselmoferreira , I think you may have to run the code in /examples. There are no pre-trained models but they are small and fast to train.

**Comment by anselmoferreira** [comment]
Thank you @layumi , but how can I save the net as a .mat file? I tried the following but it doesnt work: 

     save('cifar.mat', 'net')
     net2=load('cifar.mat')           

      net2 = 

    net: [1x1 struct]

**Comment by layumi** [comment]
You are welcome. @anselmoferreira 
I use dagnn model, so I save the model as following.
net_mat = net.saveobj() ; %net is a DagNN class
save('my_alexnet.mat', 'net_mat') ;

%--------when you load the mat
load('my_alexnet.mat') ;
net = dagnn.DagNN.loadobj(net_mat) ;

**Comment by anselmoferreira** [comment]
I am not using dagnn model, when I run your suggestion the following error appears


    reference to non-existent field 'saveobj'.

    Error in cnn_cifar (line 64)
    net_mat = net.saveobj() 

is it possible to save the net anyway?

**Comment by layumi** [comment]
For simplenn, I think `save('cifar.mat', 'net')`  is OK.
When you load the model, just use 'load('cifar.mat')' 
If you use ` net2=load('cifar.mat') `, you can find the model `net = net2.net;`

**Comment by anselmoferreira** [comment]
You are completely right. Thank you!
