### ISSUE TITLE
Labels for binary classification based on Imagenet/ Alexnet - Strange values for binerr and objective

### ISSUE THREAD

**Issue by saskra** [vlfeat/matconvnet#891]
Maybe it is an easy question, but I want to adapt the imagenet example to a binary classification task. I already changed the errorFuntion to binary, but in the other issues on this task it says, that you also have to change the labels to +1 and -1. Where exactly in the code will I do this?

**Comment by layumi** [comment]
Hi @saskra , you can change the label to 1,2. It will work. 
And make sure the output of the final layer of network structure is 2 dimension.

**Comment by saskra** [comment]
Thank you, @layumi ! Maybe I am blind, but where do I change the labels? Currently, I just adapted the directory structure of the original ILSVRC2012 and I thought, that it will automatically count and number the classes 1 and 2.

**Comment by layumi** [comment]
@saskra 
You can change the label when you prepare the imdb. For example, the label may be in the `imdb.images.labels`.
If you want to know how the loss works, you can refer to the `vl_nnloss.m` .  If you check the `ci`, you will know why it is 1 and 2 instead of 1 and -1.

**Comment by saskra** [comment]
Thanks again, @layumi ! So I changed the _1000_ in  _net = add_block(net, opts, '8', 1, 1, 4096, 1000, 1, 0)_  in line 205 in _cnn_imagenet_init.m_ to _2_.

But if I use 1 and 2 as labels, the binerr is always equal to the number of images and the objective is very high. When I use -1 and 1 as labels binerr does not change but the objective is 0. This does not seem right to me.

**Comment by layumi** [comment]
@saskra 
The binary error should have to be [0,1] like 0.5
You may check the output size of network. Is the size of output 1\*1 ?
Sometime the objective is very high because the size of your input is too large.  

I am not sure whether there is a bug in binary error. I usually use the multi-class loss when I use the simplenn.

**Comment by saskra** [comment]
The net is a 1x1 struct and net.meta.inputSize says [227,227,3,32].
