### ISSUE TITLE
MATLAB matconvnet compile for GPU problem -   mex_CUDA_win64.xml missing

### ISSUE THREAD

**Issue by Ellezon** [vlfeat/matconvnet#893]
Hi,

I am able to compile matconvnet for CPU fine but it won't work with GPU enabled ie:

`vl_compilenn('verbose',1,'enableGpu',true);`

I am using MATLAB 2016a with CUDA version 7.5. After running deviceQuery I got:
![image](https://cloud.githubusercontent.com/assets/20472720/23364452/6b933bd6-fcff-11e6-86ba-b514c0554a46.png)
So i think my GPU is fine. 

The error is this:
![image](https://cloud.githubusercontent.com/assets/20472720/23364717/774fc9ac-fd00-11e6-8aaf-671d79ec82df.png)

No mex_CUDA_win64.xml  exists in the directory : C:\Program Files\MATLAB\R2016a\toolbox\distcomp\gpu\extern\src\mex\win64\

How do I get this file please? Any help is greatly appreciated :)

**Comment by muthiyanbhushan** [comment]
Hello  Ellezon,

I am facing similar issue.
Did you resolve it?

Please, guide me if you were able to resolve the issue.

Thank you.

--
Bhushan

**Comment by Ellezon** [comment]
I believe i deleted all the files in the mex folder and ran it again. Good luck!
