### ISSUE TITLE
Wrong vgg-s, vgg-m net architecture parameter 

### ISSUE THREAD

**Issue by micklexqg** [vlfeat/matconvnet#897]
Hi,
in vgg-s and vgg-m, the first conv layer set is net.layers = {} ;
net = add_block(net, opts, '1', 7, 7, 3, 96, 2, 0) ; and the variable of add_block is (net, opts, id, h, w, in, out, stride, pad). however, according to the formula (hi+2*pad_h-kernel_h)/stride_h + 1, the result will be (224+2x0-7)/2 +1= 109.5. so, is there anything wrong?
does anybody encounter the same confusion?

**Comment by ankush-me** [comment]
The formula you have is missing a floor operation: 
H_out = 1 + floor( (H_in - H_kernel + Pad_top + Pad_bottom) /stride )

Reference: pg. 28 of the MatConvNet [manual](http://www.vlfeat.org/matconvnet/matconvnet-manual.pdf)

**Comment by micklexqg** [comment]
@ankush-me ,thanks, but in cs231n, http://cs231n.github.io/convolutional-networks/, it says it's invalid if the hyperparameter is not a integer.

**Comment by ankush-me** [comment]
It really depends on the implementation details, i.e., how such cases are actually handled in code.

**Comment by micklexqg** [comment]
@ankush-me ,thanks!
