### ISSUE TITLE
how to visualize the network feature with matconvnet?

### ISSUE THREAD

**Issue by eroszip** [vlfeat/matconvnet#898]
First,to my knowledge,with the Dagnn，we can set net.conserveMemory = 0;   then we can use net.var() this function to obtain the interlayer feature. but i wonder how to get the feature with simplenn?
second,with the classification task, how to label the samples,for example,label with [-1,1]or[0,1]or[1,2],or there is nothing with the marked label?

**Comment by eroszip** [comment]
the default parameter conserveMemory is true,should i use  this sentence like this  res    = vl_simplenn(net,input,[],[],'conserveMemory',false);

**Comment by jotaf98** [comment]
1) With simplenn you can get the intermediate features of layer i as res(i).x; this is returned by vl_simplenn.
2) For binary classes use -1,1 and set 'loss' to 'logistic'; see help vl_nnloss

BTW these questions are best reserved to the discussion forum :)
https://groups.google.com/forum/#!forum/matconvnet
