### ISSUE TITLE
compilation on windows fails due to incorrect cl.exe found

### ISSUE THREAD

**Issue by pengsun** [vlfeat/matconvnet#90]
Hi,

The compilation fails on my computer with the command
``` Matlab
vl_compilenn('enableGpu',true, 'cudaMethod','nvcc', 'Verbose',1)
``` 

I tracked into `vl_compilenn.m` and found that it's due to some suspicious code in the sub function `check_clpath()` and the `parfor` used at line 337. Below are details:

The code showing up twice in check_clpath()`
``` Matlab
if status == 1
```
could better be
``` Matlab
if (status ~= 0)
```
because an error dialog popped up while running `system('cl.exe')` and it returned a weird large number.

Also, 
``` Matlab
cl_path = fullfile(cc.Location, 'VC','bin', 'x86_amd64')
```
could better be 
``` Matlab
cl_path = fullfile(cc.Location, 'VC','bin', cc.Details.CommandLineShellArg);
```
For example, on my computer the arch is simply 'amd64'.

Finally, I had to change the `parfor` to `for` at line 337, or the compilation still failed because 'cl.exe' cannot be found even if it had been added to path in `check_clpath()`, I didn't find out why this happened.

**Comment by lenck** [comment]
Hi, the proposed changes does not work on my VM. As there is no which command on all Windows systems, the `status == 1` is the only way how to find out that the `cl.exe` is not on path.
But you are right that there is not point using the 32bit compiler for `amd64` architecture. However, the option `cc.Details.CommandLineShellArg` is not documented, so it may be dangerous to use it.
