### ISSUE TITLE
creating IMDB structure for MatconvNet

### ISSUE THREAD

**Issue by raaju-shiv** [vlfeat/matconvnet#909]
Hi,
I have written a new createIMDB function fllowing an online tutorial on Deep Learning by German Ros. The original imdb was written for a binary classification problem. I attempted to change it for a three class problem. Each of my class 'cat', 'dog' and 'rat' contain say, three images, for simplicity. My function goes like this:

function imdb = createIMDB_RAM1(folder)
	% imdb is a matlab struct with several fields, such as:
	%	- images: contains data, labels, ids dataset mean, etc.
	%	- meta: contains meta info useful for statistics and visualization
	%	- any other you want to add
	imdb = struct();

	% let's assume we have a folder with three
	% subfolders "cat" "dog" and "rat" containing images
	% for a multi-class problem
	positives = dir([folder '/cat/*.jpg']);
	negatives = dir([folder '/dog/*.jpg']);
        neutral = dir([folder '/rat/*.jpg']);
	imref = imread([folder '/cat/', positives(1).name]);
	[H, W, CH] = size(imref);

	% number of images
	NPos = numel(positives);
	NNeg = numel(negatives);
        NNeu = numel(neutral);
	N = NPos + NNeg + NNeu;

	% we can initialize part of the structures already
	meta.sets = {'train', 'val'};
	meta.classes = {'cat', 'dog', 'rat'};

	% images go here
	images.data = zeros(H, W, CH, N, 'single');
	% this will contain the mean of the training set
	images.data_mean = zeros(H, W, CH, 'single');
	% a label per image
	images.labels = zeros(1, N);
	% vector indicating to which set an image belong, i.e.,
	% training, validation, etc.
	images.set = zeros(1, N);

	numImgsTrain = 0;
	% loading positive samples
	for i=1:numel(positives)
		im = single(imread([folder '/cat/', positives(i).name]));
		images.data(:,:,:, i) = im;
		images.labels(i) = 2;

		% in this case we select the set (train/val) randomly
		if(randi(10, 1) > 6) (% 60% for training and 40% for validation)
			images.set(i) = 1;
			images.data_mean = images.data_mean + im;
			numImgsTrain = numImgsTrain + 1;
		else
			images.set(i) = 2;
		end
 	end

	% loading negative samples
	for i=1:numel(negatives)
		im = single(imread([folder '/dog/', negatives(i).name]));
		**images.data(:,:,:, NPos+NNeu+i) = im;
		images.labels(NPos+NNeu+i) = 1;**
    
		% in this case we select the set (train/val) randomly
		if(randi(10, 1) > 6)
			**images.set(NPos+NNeu+i) = 1;**
			images.data_mean = images.data_mean + im;
			numImgsTrain = numImgsTrain + 1;
		else
			**images.set(NPos+NNeu+i) = 2;**
		end
    end
    
    
    % loading neutral samples
	for i=1:numel(neutral)
		im = single(imread([folder '/rat/', neutral(i).name]));
		**images.data(:,:,:, NPos+NNeg+i) = im;**
		**images.labels(NPos+NNeu+i) = 3;**

		% in this case we select the set (train/val) randomly
		if(randi(10, 1) > 6)
			**images.set(NPos+NNeg+i) = 1;**
			images.data_mean = images.data_mean + im;
			numImgsTrain = numImgsTrain + 1;
		else
			**images.set(NPos+NNeu+i) = 2;**
		end
	end

	% let's finish to compute the mean
	images.data_mean = images.data_mean ./ numImgsTrain;

	% now let's add some randomization 
	indices = randperm(N);
	images.data(:,:,:,:) = images.data(:,:,:,indices);
	images.labels(:) = images.labels(indices);
	images.set(:) = images.set(indices);

	imdb.meta = meta;
	imdb.images = images;
	
end

I'm trying to give labels '1', '2', '3' for 'cat', 'dog' and 'rat' respectively. When i run the function, all the other meta-parameters including the number of sets (train, val), labels ('cat', 'dog', 'rat') are declared properly however the 'labels' and 'sets' are improperly assigned to the images. I'm pretty sure I am committing mistake in assigning the labels and sets inside the 'for' loop, which i have highlighted in bold. Kindly help rectifying the issue. Thanks for your assistance.

**Comment by jotaf98** [comment]
Hi, in the case of multi-class problems there's no need to consider positive/negative splits, you just assign different classes to samples and the multi-class losses will take care of things.

You also don't need to permute the data, since cnn_train does that automatically.

Here's a 3-class IMDB example that you might have better luck with:
http://www.robots.ox.ac.uk/~joao/cnn_toy_data.m

Also these questions are better put in the forum ;)
https://groups.google.com/forum/#!forum/matconvnet

**Comment by raaju-shiv** [comment]
Hi, 
For the imdb function you have written, as a part of the cnn_toy_data program, how do I have to specify the path to the folders and sub-folders, if I store this imdb has a separate function to be modified for different applications? 
For instance, if I have my root folder at 'C:\animals' and sub_folders 'cat', 'dog', rat', inside this root folder, how do I need to declare it in a separate imdb function, written based on your code?

Also, I have a few questions with respect to the code. Do you have a documentation on the code? for instance,
rng('default') ; rng(0) ; % what is the purpose of these lines?
n = 5000 ; % is this the number of samples in an individual classes or all together?
num_points = [3, 4, 50] ; %what do these values signify?
% Generate image as a regular polygon, with random rotation and scale radius = randi([11, 14]) ;  % do we need to do this for all problems?
angles = rand(1) + (0 : 2 * pi / num_points(labels(i)) : 2 * pi) ; 
xs = 16.5 + cos(angles) * radius ; 
ys = 16.5 + sin(angles) * radius ; 
images(:,:,:,i) = poly2mask(xs, ys, 32, 32) ; % what is the purpose of these lines

I sincerely hope for your assistance. Looking forward.
