### ISSUE TITLE
error in compiling CPU version with windows 7 + matlab 2014a

### ISSUE THREAD

**Issue by slmjlf** [vlfeat/matconvnet#92]
Hi! I met some errors in compiling in Windows 7. Matlab 2014a and Visual Studio 2013 have both been installed in my computer. Could anybody help? Thank you! My error information is as follows:

vl_compilenn
Error using vl_compilenn>objext (line 404)
Unsupported architecture PCWIN.

Error in vl_compilenn>toobj (line 367)
objs = strrep(objs,'.cpp',['.' objext]) ;

Error in vl_compilenn>(parfor body) (line 345)
mex_compile(opts, srcs{i}, toobj(bld_dir,srcs{i}), flags.mexcc) ;

Error in vl_compilenn (line 337)
parfor i = 1:numel(horzcat(lib_src, mex_src))

![20150312122236](https://cloud.githubusercontent.com/assets/7233963/6612462/85aab716-c8b7-11e4-8646-1e38054a46b6.jpg)

**Comment by lenck** [comment]
Hi, this error is caused by the fact that we didn't have any X86 Windows machine for testing, only it's 64 bit version.
If you are going to use just the CPU version, probably just changing line 402 to:
```
 case {'win64','pcwin'}, ext = 'obj';
```
Should probably work...

**Comment by slmjlf** [comment]
Thanks @lenck I modified line 402 but the errors still exist. I have tried capital letters PCWIN but it didn't work.

**Comment by slmjlf** [comment]
@lenck I can find other lines with "win64" in it, such as line 219, 277, 312, 415, 454, 480, 536. Is it necessary to make some modifications to all these lines?

**Comment by vedaldi** [comment]
Hi, we never tested a 32-bit build. Is there a particular reason why you are not running MATLAB 64 bit? Note that MATLAB 32 bit will be phased out by Mathwork in one of the upcoming releases. There does not seem much incentive in creating a 32 bit version of the code, although I am sure it could be done with  relatively little effort. Also, in most applications of deep learning 4GB of addressable memory seem a little too little.

**Comment by slmjlf** [comment]
I bought a new Thinkpad laptop with 64-bit OS. Problems solved! Thanks @lenck @vedaldi I am a new learner to CNNs.

**Comment by willard-yuan** [comment]
I also faced with the same problem. My OS is Windows 7 64-bit and matlab version is R2012b. The error throws out is as follows:

```matlab
Error using mex (line 206)
Unable to complete successfully.

Error in vl_compilenn>mex_compile (line 411)
mex(mopts{:}) ;

Error in vl_compilenn>(parfor body) (line 380)
    mex_compile(opts, srcs{i}, toobj(bld_dir,srcs{i}), flags.mexcc) ;

Error in parallel_function (line 470)
            F(base, limit, supply(base, limit));

Error in vl_compilenn (line 371)
parfor i = 1:numel(horzcat(lib_src, mex_src))
```

Anyone helps me?

**Comment by khouloud123** [comment]
Hi! I met some errors in compiling in Windows 7(32bit). Matlab 2014a and Visual Studio 2013 have both been installed in my computer. Could anybody help? Thank you! My error information is as follows:

Error using vl_compilenn>objext (line 383)
Unsupported architecture PCWIN.

Error in vl_compilenn>mex_compile (line 314)
  objs{i} = fullfile(bld_dir, [base '.' objext]) ;

Error in vl_compilenn (line 270)
obj_files = mex_compile(opts, cpp_src, bld_dir, mex_opts);

Error in setup (line 15)
  vl_compilenn('enableGpu', opts.useGpu, 'verbose', opts.verbose) ;

Error in run (line 63)
evalin('caller', [script ';']);

**Comment by lenck** [comment]
Unfortunately we do not support the 32bit Windows, as nobody from the developers has its copy. Sorry that we are not able to help.
