### ISSUE TITLE
out of memory when i use cnn_train .but i has finish a epoch train .

### ISSUE THREAD

**Issue by hushunda** [vlfeat/matconvnet#929]
i finish cnn_train in example by using gpu.but when i use cnn to train my image,Actually i train  fcn net by calling cnn_tain.
i think the gpu has train a epoch,the memory of gpu is ok.
![image](https://cloud.githubusercontent.com/assets/21358656/24205756/44f265dc-0f57-11e7-995f-f8b554a5d0da.png)
then i attach my device

![image](https://cloud.githubusercontent.com/assets/21358656/24206219/8a79612c-0f58-11e7-8003-5f2007cb11e6.png)

@vedaldi

**Comment by zz-kuku** [comment]
Maybe you can try using less batchsize to verify whether is the cause of GPU memory

**Comment by hushunda** [comment]
@zz-kuku i try （batchsize=1）,but  happen  same  error.i donot know how to deal with,

**Comment by hushunda** [comment]
I find the reason that is the memory is Insufficient.in first epoch,the parament is less than second.

**Comment by priyam1994** [comment]
Hello, I have a similar issue. Here is how it looks for me. Reducing batch size to 8 too doesn't help, how did you solve it?
Thanks

parameter memory|378MB (9.9e+07 parameters)|
     data memory|  112MB (for batch size 8)|


ans = 

  CUDADevice with properties:

                      Name: 'GeForce 920M'
                     Index: 1
         ComputeCapability: '3.5'
            SupportsDouble: 1
             DriverVersion: 8
            ToolkitVersion: 8
        MaxThreadsPerBlock: 1024
          MaxShmemPerBlock: 49152
        MaxThreadBlockSize: [1024 1024 64]
               MaxGridSize: [2.1475e+09 65535 65535]
                 SIMDWidth: 32
               TotalMemory: 2.1015e+09
           AvailableMemory: 1.6053e+09
       MultiprocessorCount: 2
              ClockRateKHz: 954000
               ComputeMode: 'Default'
      GPUOverlapsTransfers: 1
    KernelExecutionTimeout: 1
          CanMapHostMemory: 1
           DeviceSupported: 1
            DeviceSelected: 1

train: epoch 01:   1/3822: Error using *
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling
'gpuDevice(1)'.

**Comment by hushunda** [comment]
@priyam1994 ，I'm sorry,I can't help you.because I change a GPU to  solve the problem,My problem is really the GPU out of memory.
