### ISSUE TITLE
Please How used Matconvnet in custom Dataset ?

### ISSUE THREAD

**Issue by alfredeep** [vlfeat/matconvnet#935]
Hello,
I am a beginner in CNN with Matconvnet, and I want to use my own dataset to realize a CNN model.
Please, what are the steps to follow and especially in my own dataset and not a pre-trained model. 

Thank you very much

**Comment by bazilas** [comment]
You could study one of the given examples (e.g. cifar or mnist) to understand the important steps (1. define network, 2. generate imdb, 3. train with simplenn or dagnn).

**Comment by lenck** [comment]
Hi, @jotaf98 created a new example just for this problem...
https://github.com/vlfeat/matconvnet/tree/master/examples/custom_imdb
