### ISSUE TITLE
Descriptors of LFW images using VGG_Face CNN

### ISSUE THREAD

**Issue by JCRNeves** [vlfeat/matconvnet#938]
I would like to know how to compute the descriptors of LFW using the vgg_face.

By reading the paper "Deep Face Recognition" I assume I should remove the classification layer and keep the 4096 descriptor of the last FC layer.

However, by using this approach I am not able to reproduce the results reported in the original paper.

Can somebody explain me how to proceed ?

**Comment by bazilas** [comment]
It might be better to directly contact the first author (Omkar) of the paper. This is not a MatConvNet issue.
