### ISSUE TITLE
Is there any implementation to visualize the filter?

### ISSUE THREAD

**Issue by johnny5550822** [vlfeat/matconvnet#94]
Is there any way to visualize the trained filters? As way as the output images?

**Comment by dteney** [comment]
You can just recover the filters and use Matlab's function to display them as images. For example after loading pretrained net from http://www.vlfeat.org/matconvnet/pretrained/:
imshow( net.layers{1}.filters(:, :, 3, 1), [] ) ;
You may find the VLFeat function vl_imarraysc useful to display several filters. See also the tutorial:
http://www.robots.ox.ac.uk/~vgg/practicals/cnn/index.html

**Comment by johnny5550822** [comment]
Great, thanks! I will try them.

**Comment by myway0101** [comment]
Hi dteney
this tutorial only include visualizing first layer.
http://www.robots.ox.ac.uk/~vgg/practicals/cnn/index.html

Anyone know how second or third layer can visualize??

**Comment by freedomn** [comment]
Hi @myway0101, did you find out how to visualize second layer?

**Comment by Addhi86** [comment]
@myway0101 @freedomn 

Have you got the solution to visualize the second and third layer?

**Comment by myway0101** [comment]
No not yet..

2017-06-07 5:20 GMT+02:00 Addhi86 <notifications@github.com>:

**Comment by freedomn** [comment]
Me neither. However, I used deep goggle code for reconstructing images with each layer and it was interesting .

**Comment by myway0101** [comment]
Oh nice. can you share where can i find it?

2017-06-07 13:37 GMT+02:00 freedomn <notifications@github.com>:

**Comment by freedomn** [comment]
https://github.com/aravindhm/deep-goggle
