### ISSUE TITLE
GPU comlie error with win7_64+matlab2014a

### ISSUE THREAD

**Issue by jedol** [vlfeat/matconvnet#95]
Hi, I have some trouble in compiling GPU version.
When compile CPU version, there are no problem.
But, when I compile GPU version, running after 'Intermediate object files' step in 'vl_compilenn.m', object files were not created. Nevertheless, the 'Intermediate object files' step was completed.
So error has occurred at 'Link into MEX files' step as follows.

![image](https://cloud.githubusercontent.com/assets/11476586/6652540/7508c740-cab5-11e4-8a90-8325f63da793.png)

I have CUDA toolkit 6.0.
Could anybody help?
Thank you.

**Comment by lenck** [comment]
Hi, did you manage to solve this issue? Sorry I was not able to help, but it seems to be caused by old version of Visual C++? Plus I do not understand the Korean Error message... :(
