### ISSUE TITLE
GPU utilisation is around 30%

### ISSUE THREAD

**Issue by MaxChu719** [vlfeat/matconvnet#950]
I am using matconvnet doing human pose estimation.
1. I am using the latest code.
1. GPU: gtx 1080, cuda 8.0, cudnn 5.1.
1. Compiled on windows 10 using VS2013 professional.
1. getBatch function seems not a bottle-neck. It should be on the forward and backprop.
1. Input image is 192x192x3. Model is not similar to ResNet.
1. I only get 20 images/s in training.
1. GPU utilisation is around 30%.
Any ideas? What other information should i provided?
![screenshot](https://cloud.githubusercontent.com/assets/1996865/24895203/7f47645a-1ed2-11e7-950d-acb0327fe895.png)

**Comment by lenck** [comment]
Apparently the IO is the issue. Usually that's caused by your storage being too slow. We usually solve it by moving data to a ramdisk or faster SSD. 

Maybe this may be of help, if you have enough RAM:
https://en.wikipedia.org/wiki/List_of_RAM_drive_software

**Comment by MaxChu719** [comment]
I am already using a ssd and i have implemented a prefetch function in getbatch.

**Comment by MaxChu719** [comment]
Any response?
