### ISSUE TITLE
error when loading png files using vl_imreadjpeg

### ISSUE THREAD

**Issue by talenz** [vlfeat/matconvnet#952]
How to avoid these error informations?

![vl_imreadjpeg_error](https://cloud.githubusercontent.com/assets/6121158/24938054/67206e18-1f67-11e7-9662-9f40e61763af.png)

**Comment by lenck** [comment]
Hi, `vl_imreadjpeg` does not support png files currently. Only jpeg files. If you want to use png files you can use the slower imread method (by editing getbatch function).
