### ISSUE TITLE
Error while running vl_nnsoftmaxloss() function.

### ISSUE THREAD

**Issue by Arathyds** [vlfeat/matconvnet#954]
Sir,
I am doing project lung cancer detection using semantic segmentation. Using matconvnet i've successfully obtained the forward and backward pass, but while entering to the softmaxloss function it is showing me an error as below. Please help me to get through this. Thanks in advance.

**Error using  + 
Integers can only be combined with integers of the same class, or scalar doubles.

Error in vl_nnsoftmaxloss (line 66)
c_ = 1 + ...**

**Comment by jotaf98** [comment]
You'll need to convert your labels to double() in your getBatch function.

Please note that this should not be an Issue, but a question in the forum:
https://groups.google.com/forum/#!forum/matconvnet
