### ISSUE TITLE
hinge and MSE loss 

### ISSUE THREAD

**Issue by itaykez** [vlfeat/matconvnet#97]
Hi There,

I started playing with your great machinery,
Is there a way to integrate a "hinge-loss" loss into the framework?
Moreover, 
I want my net to handle a regression task, is there a way to integrate a MSE loss?

Thanks,
Itay

**Comment by AnanS** [comment]
Have a look at https://github.com/vlfeat/matconvnet/issues/15 for MSE.

**Comment by itaykez** [comment]
Thanks!
