### ISSUE TITLE
weight and bias update rules

### ISSUE THREAD

**Issue by drohit92** [vlfeat/matconvnet#98]
Hello everyone,

I am exploring the mnist example. The weight and bias update rules that I see are:

net.layers{l}.filtersMomentum = ...
        opts.momentum * net.layers{l}.filtersMomentum ...
          - (lr * net.layers{l}.filtersLearningRate) * ...
          (opts.weightDecay * net.layers{l}.filtersWeightDecay) * net.layers{l}.filters ...
          - (lr * net.layers{l}.filtersLearningRate) / numel(batch) * res(l).dzdw{1} ;

      net.layers{l}.biasesMomentum = ...
        opts.momentum * net.layers{l}.biasesMomentum ...
          - (lr * net.layers{l}.biasesLearningRate) * ....
          (opts.weightDecay * net.layers{l}.biasesWeightDecay) * net.layers{l}.biases ...
          - (lr * net.layers{l}.biasesLearningRate) / numel(batch) * res(l).dzdw{2} ;

      net.layers{l}.filters = net.layers{l}.filters + net.layers{l}.filtersMomentum ;
      net.layers{l}.biases = net.layers{l}.biases + net.layers{l}.biasesMomentum ;

I understand the global learning rates, momentum like opts.momentum which is 0.9 and opts.weightDecay, lr etc
I don't get what are the individual biasesLearningRate , biasesWeightDecay ??

@vedaldi If possible Can you mention the exact mathematical equations that are being used? It will help a lot.

Thanks.

**Comment by dteney** [comment]
biasesLearningRate and biasesWeightDecay are set individually for each layer of the network, and they allow you to enable/disable the learning/regularizer of individual layers. You typically set them to either 0 or 1.
