### ISSUE TITLE
MatConvNet for Octave

### ISSUE THREAD

**Issue by wajahat57** [vlfeat/matconvnet#992]
Hi
Is it possible to use MatconvNet in Octave?
Best Regards
Wajahat

**Comment by bazilas** [comment]
Hi, 

No, it's not possible. Parts of MatConvNet use toolboxes that are not available in Octave (e.g. parallel computing).

**Comment by wajahat57** [comment]
But I think parallel computing toolbox is used for operation on multiple GPUs. 
For CPU, or single GPU operation, MatConvNet does not seem to be using any other toolbox.

**Comment by CognitiveClouds-Prasad** [comment]
If this can work on Octave, then we can support users not having MATLAB licenses.
